// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:09 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { Rect } from "../../Foundation/Rect";

@GenerateShim('Windows.UI.ViewManagement.InputPaneVisibilityEventArgs')
export class InputPaneVisibilityEventArgs { 
    ensuredFocusedElementInView: boolean = null;
    occludedRect: Rect = null;
}
