// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------


export interface IFUEConfiguration {
    acceptedEula: boolean;
    acceptedPrivacyStatement: boolean;
    freeStreamingIsGoneAnnouncementDismissed: boolean;
    minMusicAppSupportedVersion: string;
    minVersionBlockAllAppUse: string;
    minVideoAppSupportedVersion: string;
    musicAvailableOfflineFlyoutFilterShown: boolean;
    musicCloudContentV1CleanupDialogDismissed: boolean;
    musicCloudContentV2FlyoutFilterShown: boolean;
    settingsVersion: number;
    showFUE: boolean;
    showFirstLaunchVideo: boolean;
    showLXFUE: boolean;
}
