// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:00 2021
// </auto-generated>
// --------------------------------------------------

import { ResourceMap } from "./ResourceMap";
import { IIterable } from "../../../Foundation/Collections/IIterable`1";
import { IIterator } from "../../../Foundation/Collections/IIterator`1";
import { IKeyValuePair } from "../../../Foundation/Collections/IKeyValuePair`2";
import { IMapView } from "../../../Foundation/Collections/IMapView`2";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.ApplicationModel.Resources.Core.ResourceMapMapView')
export class ResourceMapMapView implements IMapView<string, ResourceMap>, IIterable<IKeyValuePair<string, ResourceMap>> { 
    size: number = null;
    [Symbol.iterator]() {
        return null;
    }
    lookup(key: string): ResourceMap {
        throw new Error('ResourceMapMapView#lookup not implemented')
    }
    hasKey(key: string): boolean {
        throw new Error('ResourceMapMapView#hasKey not implemented')
    }
    split(): { first: IMapView<string, ResourceMap>, second: IMapView<string, ResourceMap> } {
        throw new Error('ResourceMapMapView#split not implemented')
    }
    first(): IIterator<IKeyValuePair<string, ResourceMap>> {
        throw new Error('ResourceMapMapView#first not implemented')
    }
}
