// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:00 2021
// </auto-generated>
// --------------------------------------------------

import { ResourceContext } from "./ResourceContext";
import { ResourceMap } from "./ResourceMap";
import { IIterable } from "../../../Foundation/Collections/IIterable`1";
import { IMapView } from "../../../Foundation/Collections/IMapView`2";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";
import { IStorageFile } from "../../../Storage/IStorageFile";
import { Dictionary } from "../../../Foundation/Interop/Dictionary`2";

export class ResourceManager { 
    allResourceMaps: IMapView<string, ResourceMap> = new Dictionary();
    defaultContext: ResourceContext = new ResourceContext();
    mainResourceMap: ResourceMap = new ResourceMap();    
    static current: ResourceManager = new ResourceManager();
    loadPriFiles(files: IIterable<IStorageFile>): void {
        console.warn('ResourceManager#loadPriFiles not implemented')
    }
    unloadPriFiles(files: IIterable<IStorageFile>): void {
        console.warn('ResourceManager#unloadPriFiles not implemented')
    }
    static isResourceReference(resourceReference: string): boolean {
        throw new Error('ResourceManager#isResourceReference not implemented')
    }
}
