// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:11 2021
// </auto-generated>
// --------------------------------------------------

import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { AsyncOperation } from "winrt/Windows/Foundation/Interop/AsyncOperation`1";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Platform.Resources.PlatformResourceManager')
export class PlatformResourceManager implements IStringable { 
    static readonly instance: PlatformResourceManager = null;
    initializeAsync(): IAsyncOperation<boolean> {
        return AsyncOperation.from(async () => { throw new Error('PlatformResourceManager#initializeAsync not implemented') });
    }
    toString(): string {
        throw new Error('PlatformResourceManager#toString not implemented')
    }
}
