// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:09 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { Uri } from "../../Foundation/Uri";
import { Color } from "../Color";
import { ForegroundText } from "./ForegroundText";

@GenerateShim('Windows.UI.StartScreen.SecondaryTileVisualElements')
export class SecondaryTileVisualElements { 
    wide310x150Logo: Uri = null;
    square70x70Logo: Uri = null;
    square310x310Logo: Uri = null;
    square30x30Logo: Uri = null;
    square150x150Logo: Uri = null;
    showNameOnWide310x150Logo: boolean = null;
    showNameOnSquare310x310Logo: boolean = null;
    showNameOnSquare150x150Logo: boolean = null;
    foregroundText: ForegroundText = null;
    backgroundColor: Color = null;
}
