// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:37 2021
// </auto-generated>
// --------------------------------------------------

import { ConfigArea } from "./ConfigArea";
import { ConfigCloud } from "./ConfigCloud";
import { IConfigInstance } from "./IConfigInstance";
import { IConfigObject } from "./IConfigObject";
import { IObject } from "./IObject";
import { ITransientObjectHolder } from "./ITransientObjectHolder";
import { ObjectChangedHandler } from "./ObjectChangedHandler";
import { Enumerable } from "winrt/Windows/Foundation/Interop/Enumerable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";
import { IStorageFile } from "winrt/Windows/Storage/IStorageFile";
import { IBuffer } from "winrt/Windows/Storage/Streams/IBuffer";

@GenerateShim('Microsoft.WindowsLive.Platform.ConfigInstance')
export class ConfigInstance implements IConfigInstance, IConfigObject, IObject { 
    uri: string = null;
    readonly area_String: string = null;
    readonly buffer: IBuffer = null;
    readonly cloud_String: string = null;
    readonly file: IStorageFile = null;
    readonly market_String: string = null;
    readonly area: ConfigArea = null;
    readonly beginDate: Date = null;
    readonly cloud: ConfigCloud = null;
    readonly endDate: Date = null;
    readonly feature: string = null;
    readonly hash: string = null;
    readonly market: number = null;
    readonly xmlData: string = null;
    readonly canDelete: boolean = null;
    readonly canEdit: boolean = null;
    readonly isObjectValid: boolean = null;
    readonly objectId: string = null;
    readonly objectType: string = null;
    put_BeginDate(value: Date): void {
        console.warn('ConfigInstance#put_BeginDate not implemented')
    }
    put_EndDate(value: Date): void {
        console.warn('ConfigInstance#put_EndDate not implemented')
    }
    put_File(value: IStorageFile): void {
        console.warn('ConfigInstance#put_File not implemented')
    }
    put_Buffer(value: IBuffer): void {
        console.warn('ConfigInstance#put_Buffer not implemented')
    }
    put_XmlData(value: string): void {
        console.warn('ConfigInstance#put_XmlData not implemented')
    }
    put_Hash(value: string): void {
        console.warn('ConfigInstance#put_Hash not implemented')
    }
    updateXmlDataWithHash(xmlData: string, hash: string): void {
        console.warn('ConfigInstance#updateXmlDataWithHash not implemented')
    }
    commit(): void {
        console.warn('ConfigInstance#commit not implemented')
    }
    deleteObject(): void {
        console.warn('ConfigInstance#deleteObject not implemented')
    }
    getKeepAlive(): ITransientObjectHolder {
        throw new Error('ConfigInstance#getKeepAlive not implemented')
    }

    private __changed: Set<ObjectChangedHandler> = new Set();
    @Enumerable(true)
    set onchanged(handler: ObjectChangedHandler) {
        this.__changed.add(handler);
    }

    private __deleted: Set<ObjectChangedHandler> = new Set();
    @Enumerable(true)
    set ondeleted(handler: ObjectChangedHandler) {
        this.__deleted.add(handler);
    }

    addEventListener(name: string, handler: any) {
        switch (name) {
            case 'changed':
                this.__changed.add(handler);
                break;
            case 'deleted':
                this.__deleted.add(handler);
                break;
        }
    }

    removeEventListener(name: string, handler: any) {
        switch (name) {
            case 'changed':
                this.__changed.delete(handler);
                break;
            case 'deleted':
                this.__deleted.delete(handler);
                break;
        }
    }
}
