// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:37 2021
// </auto-generated>
// --------------------------------------------------

import { CalendarFolderType } from "./CalendarFolderType";
import { ContactFolderType } from "./ContactFolderType";
import { FolderAction } from "./FolderAction";
import { FolderType } from "./FolderType";
import { ICollection } from "./ICollection";
import { IFolder } from "./IFolder";
import { IObject } from "./IObject";
import { ITransientObjectHolder } from "./ITransientObjectHolder";
import { MailFolderType } from "./MailFolderType";
import { ObjectChangedHandler } from "./ObjectChangedHandler";
import { Enumerable } from "winrt/Windows/Foundation/Interop/Enumerable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";
import { PlatformObject } from "./PlatformObject";
import { MailView } from "./MailView";

@GenerateShim('Microsoft.WindowsLive.Platform.Folder')
export class Folder extends PlatformObject implements IFolder {
    constructor(view?: MailView) {
        super("Folder");
        if (view) {
            this.accountId = view.accountId;
            this.folderType = FolderType.mail;
            this.folderName = "Inbox";
            this.syncStatus = 0;
            this.specialMailFolderType = MailFolderType.inbox;
            this.hasSynced = true;
            this.isLocalMailFolder = true;
            this.selectionDisabled = false;
            this.syncFolderContents = true;
        }
    }
    syncStatus: number = null;
    specialCalendarFolderType: CalendarFolderType = null;
    parentFolder: IFolder = null;
    folderType: FolderType = null;
    folderName: string = null;
    accountId: string = null;
    readonly canHaveChildren: boolean = true;
    readonly canMove: boolean = true;
    readonly canRename: boolean = true;
    readonly hasProcessedConversations: boolean = true;
    readonly hasSynced: boolean = true;
    readonly isFolderThreadingCapable: boolean = true;
    readonly isLocalMailFolder: boolean = true;
    readonly isPinnedToNavPane: boolean = false;
    readonly selectionDisabled: boolean = false;
    readonly specialContactFolderType: ContactFolderType = null;
    readonly specialMailFolderType: MailFolderType = null;
    readonly syncFolderContents: boolean = null;
    readonly underDeletedItems: boolean = null;
    markViewed(): void {
        console.warn('Folder#markViewed not implemented')
    }
    getChildFolderCollection(fAllTypes: boolean): ICollection {
        throw new Error('Folder#getChildFolderCollection not implemented')
    }
    startSyncFolderContents(fForceSynchronization: boolean): void {
        console.warn('Folder#startSyncFolderContents not implemented')
    }
    recordAction(value: FolderAction): void {
        console.warn('Folder#recordAction not implemented')
    }
    ensureNameUnique(): void {
        console.warn('Folder#ensureNameUnique not implemented')
    }
}
