// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:38 2021
// </auto-generated>
// --------------------------------------------------

import { CalendarFolderType } from "./CalendarFolderType";
import { ContactFolderType } from "./ContactFolderType";
import { FolderType } from "./FolderType";
import { IAccount } from "./IAccount";
import { ICollection } from "./ICollection";
import { IFolder } from "./IFolder";
import { MailFolderType } from "./MailFolderType";

export interface IFolderManager {
    getRootFolderCollection(pAccount: IAccount): ICollection;
    getRootFolderCollection_ByType(pAccount: IAccount, eType: FolderType): ICollection;
    getRootUserMailFolderCollection(pAccount: IAccount): ICollection;
    getAllFoldersCollection(eType: FolderType): ICollection;
    getAllFoldersCollection_ByAccount(eType: FolderType, pAccount: IAccount): ICollection;
    getSpecialMailFolder(pAccount: IAccount, eType: MailFolderType): IFolder;
    getSpecialContactFolder(pAccount: IAccount, eType: ContactFolderType): IFolder;
    getSpecialCalendarFolder(pAccount: IAccount, eType: CalendarFolderType): IFolder;
    createFolder(pAccount: IAccount): IFolder;
    loadFolder(hstrId: string): IFolder;
    getAllFoldersNotUnderDeletedItemsCollection(eType: FolderType): ICollection;
    getAllFoldersNotUnderDeletedItemsCollection_ByAccount(eType: FolderType, pAccount: IAccount): ICollection;
    getImapSpecialFolderId(pAccount: IAccount, eType: MailFolderType): string;
    setImapSpecialFolderPath(pAccount: IAccount, eType: MailFolderType, hstrFolderId: string): void;
}
