// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:38 2021
// </auto-generated>
// --------------------------------------------------

import { IMailRule } from "./IMailRule";
import { IObject } from "./IObject";

export interface IMailRuleQueued extends IMailRule, IObject {
    scopeFolderId: string;
}
