// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:38 2021
// </auto-generated>
// --------------------------------------------------

export enum IncludeSentItemsInConversationCache {
    min = 0x0,
    enabled = 0x0,
    disabled = 0x1,
    rebuildingEnabled = 0x2,
    rebuildingDisabled = 0x3,
    max = 0x3,
}
