// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:39 2021
// </auto-generated>
// --------------------------------------------------

import { IRecipient } from "./IRecipient";
import { IIterable } from "winrt/Windows/Foundation/Collections/IIterable`1";
import { IIterator } from "winrt/Windows/Foundation/Collections/IIterator`1";
import { IVectorView } from "winrt/Windows/Foundation/Collections/IVectorView`1";
import { IVector } from "winrt/Windows/Foundation/Collections/IVector`1";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";
import { Vector } from "winrt/Windows/Foundation/Interop/Vector`1";

@GenerateShim('Microsoft.WindowsLive.Platform.RecipientVector')
export class RecipientVector extends Vector<IRecipient> {
    
}
