// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:39 2021
// </auto-generated>
// --------------------------------------------------

import { AsyncActionCompletedHandler } from "winrt/Windows/Foundation/AsyncActionCompletedHandler";
import { AsyncStatus } from "winrt/Windows/Foundation/AsyncStatus";
import { IAsyncAction } from "winrt/Windows/Foundation/IAsyncAction";
import { IAsyncInfo } from "winrt/Windows/Foundation/IAsyncInfo";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.WindowsLive.Platform.SearchResultsMonitor')
export class SearchResultsMonitor implements IAsyncAction, IAsyncInfo { 
    completed: AsyncActionCompletedHandler = null;
    readonly errorCode: number = null;
    readonly id: number = null;
    readonly status: AsyncStatus = null;
    getResults(): void {
        console.warn('SearchResultsMonitor#getResults not implemented')
    }
    cancel(): void {
        console.warn('SearchResultsMonitor#cancel not implemented')
    }
    close(): void {
        console.warn('SearchResultsMonitor#close not implemented')
    }
}
