// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { IMediaStreamDescriptor } from "./IMediaStreamDescriptor";
import { MediaStreamSample } from "./MediaStreamSample";
import { MediaStreamSourceSampleRequestDeferral } from "./MediaStreamSourceSampleRequestDeferral";

@GenerateShim('Windows.Media.Core.MediaStreamSourceSampleRequest')
export class MediaStreamSourceSampleRequest { 
    sample: MediaStreamSample = null;
    streamDescriptor: IMediaStreamDescriptor = null;
    getDeferral(): MediaStreamSourceSampleRequestDeferral {
        throw new Error('MediaStreamSourceSampleRequest#getDeferral not implemented')
    }
    reportSampleProgress(progress: number): void {
        console.warn('MediaStreamSourceSampleRequest#reportSampleProgress not implemented')
    }
}
