// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:09 2021
// </auto-generated>
// --------------------------------------------------

import { IAdSource } from "./IAdSource";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Media.Advertising.AdFailureEventArgs')
export class AdFailureEventArgs implements IStringable { 
    readonly adSource: IAdSource = null;
    readonly error: number = null;
    constructor(adSource: IAdSource, error: number) {
        console.warn('AdFailureEventArgs.ctor not implemented')
    }
    toString(): string {
        throw new Error('AdFailureEventArgs#toString not implemented')
    }
}
