// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:09 2021
// </auto-generated>
// --------------------------------------------------

import { Companion } from "./Companion";
import { CompanionAdsRequired } from "./CompanionAdsRequired";
import { ICreative } from "./ICreative";
import { IVector } from "winrt/Windows/Foundation/Collections/IVector`1";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Media.Advertising.CreativeCompanions')
export class CreativeCompanions implements ICreative, IStringable { 
    id: string = null;
    sequence: number | null = null;
    adId: string = null;
    readonly companions: IVector<Companion> = null;
    required: CompanionAdsRequired = null;
    toString(): string {
        throw new Error('CreativeCompanions#toString not implemented')
    }
}
