// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:10 2021
// </auto-generated>
// --------------------------------------------------

import { FWAsset } from "./FWAsset";
import { FWCreativeApi } from "./FWCreativeApi";
import { FWParameter } from "./FWParameter";
import { FWPreference } from "./FWPreference";
import { IVector } from "winrt/Windows/Foundation/Collections/IVector`1";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Media.Advertising.FWCreativeRendition')
export class FWCreativeRendition implements IStringable { 
    creativeApi: FWCreativeApi = null;
    contentType: string = null;
    wrapperType: string = null;
    wrapperUrl: string = null;
    id: string = null;
    height: number = null;
    width: number = null;
    adReplicaId: string = null;
    preference: FWPreference = null;
    asset: FWAsset = null;
    readonly otherAssets: IVector<FWAsset> = null;
    readonly parameters: IVector<FWParameter> = null;
    toString(): string {
        throw new Error('FWCreativeRendition#toString not implemented')
    }
}
