// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:09 2021
// </auto-generated>
// --------------------------------------------------

import { IHttpCookie } from "./IHttpCookie";
import { IMapView } from "winrt/Windows/Foundation/Collections/IMapView`2";
import { IVectorView } from "winrt/Windows/Foundation/Collections/IVectorView`1";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";
import { Uri } from "winrt/Windows/Foundation/Uri";
import { IInputStream } from "winrt/Windows/Storage/Streams/IInputStream";

@GenerateShim('Microsoft.Media.AdaptiveStreaming.DownloaderResponse')
export class DownloaderResponse { 
    readonly bypassBandwidthMeasurement: boolean = null;
    readonly contentLength: number = null;
    readonly contentType: string = null;
    readonly cookies: IVectorView<IHttpCookie> = null;
    readonly headers: IMapView<string, string> = null;
    readonly responseStream: IInputStream = null;
    readonly uri: Uri = null;
    // constructor(pRequestUri: Uri, pHttpHeaders: IMapView<string, string>, pHttpCookies: IVectorView<IHttpCookie>);
    // constructor(pResponseUri: Uri, pResponseStream: IInputStream, contentLength: number, contentType: string, pHttpHeaders: IMapView<string, string>, bypassBandwidthMeasurement: boolean);
    constructor(...args) { }
}
