// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Wed Sep 15 17:20:26 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { AnalyticsVersionInfo } from "./AnalyticsVersionInfo";

@GenerateShim('Windows.System.Profile.AnalyticsInfo')
export class AnalyticsInfo { 
    static readonly deviceForm: string = null;
    static readonly versionInfo: AnalyticsVersionInfo = new AnalyticsVersionInfo();
}
