// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:12 2021
// </auto-generated>
// --------------------------------------------------

import { IMapView } from "winrt/Windows/Foundation/Collections/IMapView`2";
import { IVectorView } from "winrt/Windows/Foundation/Collections/IVectorView`1";
import { IVector } from "winrt/Windows/Foundation/Collections/IVector`1";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('SqliteWrapper.SqlResults')
export class SqlResults { 
    values: IVector<any> = null;
    columnNames: IVector<string> = null;
    columns: number = null;
    rows: number = null;
    getValue(row: number, column: number): any {
        throw new Error('SqlResults#getValue not implemented')
    }
    createDataReader(): IVectorView<IMapView<string, any>> {
        throw new Error('SqlResults#createDataReader not implemented')
    }
}
