// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:07 2021
// </auto-generated>
// --------------------------------------------------

import { IIterable } from "../../Foundation/Collections/IIterable`1";
import { IIterator } from "../../Foundation/Collections/IIterator`1";
import { IVectorView } from "../../Foundation/Collections/IVectorView`1";
import { IVector } from "../../Foundation/Collections/IVector`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Storage.Pickers.FileExtensionVector')
export class FileExtensionVector implements IVector<string>, IIterable<string> { 
    size: number = null;
    [Symbol.iterator](): Iterator<string> {
        return null;
    }
    getAt(index: number): string {
        throw new Error('FileExtensionVector#getAt not implemented')
    }
    getView(): IVectorView<string> {
        throw new Error('FileExtensionVector#getView not implemented')
    }
    setAt(index: number, value: string): void {
        console.warn('FileExtensionVector#setAt not implemented')
    }
    insertAt(index: number, value: string): void {
        console.warn('FileExtensionVector#insertAt not implemented')
    }
    removeAt(index: number): void {
        console.warn('FileExtensionVector#removeAt not implemented')
    }
    append(value: string): void {
        console.warn('FileExtensionVector#append not implemented')
    }
    removeAtEnd(): void {
        console.warn('FileExtensionVector#removeAtEnd not implemented')
    }
    clear(): void {
        console.warn('FileExtensionVector#clear not implemented')
    }
    getMany(startIndex: number): { returnValue: number, items: string[] } {
        throw new Error('FileExtensionVector#getMany not implemented')
    }
    replaceAll(items: string[]): void {
        console.warn('FileExtensionVector#replaceAll not implemented')
    }
    first(): IIterator<string> {
        throw new Error('FileExtensionVector#first not implemented')
    }
}
