// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:07 2021
// </auto-generated>
// --------------------------------------------------

import { IIterable } from "../../Foundation/Collections/IIterable`1";
import { IIterator } from "../../Foundation/Collections/IIterator`1";
import { IKeyValuePair } from "../../Foundation/Collections/IKeyValuePair`2";
import { IMapView } from "../../Foundation/Collections/IMapView`2";
import { IMap } from "../../Foundation/Collections/IMap`2";
import { IVector } from "../../Foundation/Collections/IVector`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Storage.Pickers.FilePickerFileTypesOrderedMap')
export class FilePickerFileTypesOrderedMap implements IMap<string, IVector<string>>, IIterable<IKeyValuePair<string, IVector<string>>> { 
    [Symbol.iterator]() {
        return null;
    }

    size: number = null;
    lookup(key: string): IVector<string> {
        throw new Error('FilePickerFileTypesOrderedMap#lookup not implemented')
    }
    hasKey(key: string): boolean {
        throw new Error('FilePickerFileTypesOrderedMap#hasKey not implemented')
    }
    getView(): IMapView<string, IVector<string>> {
        throw new Error('FilePickerFileTypesOrderedMap#getView not implemented')
    }
    insert(key: string, value: IVector<string>): boolean {
        throw new Error('FilePickerFileTypesOrderedMap#insert not implemented')
    }
    remove(key: string): void {
        console.warn('FilePickerFileTypesOrderedMap#remove not implemented')
    }
    clear(): void {
        console.warn('FilePickerFileTypesOrderedMap#clear not implemented')
    }
    first(): IIterator<IKeyValuePair<string, IVector<string>>> {
        throw new Error('FilePickerFileTypesOrderedMap#first not implemented')
    }
}
