// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:07 2021
// </auto-generated>
// --------------------------------------------------

import { IVector } from "../../Foundation/Collections/IVector`1";
import { IAsyncOperation } from "../../Foundation/IAsyncOperation`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { PickerLocationId } from "./PickerLocationId";
import { PickerViewMode } from "./PickerViewMode";
import { StorageFolder } from "../StorageFolder";

@GenerateShim('Windows.Storage.Pickers.FolderPicker')
export class FolderPicker { 
    viewMode: PickerViewMode = null;
    suggestedStartLocation: PickerLocationId = null;
    settingsIdentifier: string = null;
    commitButtonText: string = null;
    fileTypeFilter: IVector<string> = null;
    pickSingleFolderAsync(): IAsyncOperation<StorageFolder> {
        throw new Error('FolderPicker#pickSingleFolderAsync not implemented')
    }
}
