// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Thu Apr  8 00:47:24 2021
// </auto-generated>
// --------------------------------------------------

export enum IntendedUse {
    _Invalid = 4294967295,
    stream = 0,
    download = 1,
    _Count = 2,
}
