// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:11 2021
// </auto-generated>
// --------------------------------------------------

import { LoginStatus } from "./LoginStatus";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Platform.Paywall.PaywallResponse')
export class PaywallResponse implements IStringable { 
    success: boolean = null;
    errorCode: number = null;
    readonly message: string = null;
    readonly errorMessageResourceKey: string = null;
    status: LoginStatus = null;
    toString(): string {
        throw new Error('PaywallResponse#toString not implemented')
    }
}
