// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Media.AdaptiveStreaming 255.255.255.255 at Mon Mar 29 16:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { AdaptiveSource } from "./AdaptiveSource";
import { AdaptiveSourceStatusUpdateType } from "./AdaptiveSourceStatusUpdateType";
import { HResult } from "winrt/Windows/Foundation/HResult";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Media.AdaptiveStreaming.AdaptiveSourceStatusUpdatedEventArgs')
export class AdaptiveSourceStatusUpdatedEventArgs { 
    adaptiveSource: AdaptiveSource = null;
    additionalInfo: string = null;
    endTime: number = null;
    httpResponse: number = null;
    result: number = null;
    startTime: number = null;
    updateType: AdaptiveSourceStatusUpdateType = null;
}
