// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Media.AdaptiveStreaming 255.255.255.255 at Mon Mar 29 16:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { IHttpCookie } from "./IHttpCookie";
import { IMapView } from "winrt/Windows/Foundation/Collections/IMapView`2";
import { IVectorView } from "winrt/Windows/Foundation/Collections/IVectorView`1";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";
import { Uri } from "winrt/Windows/Foundation/Uri";
import { IInputStream } from "winrt/Windows/Storage/Streams/IInputStream";

@GenerateShim('Microsoft.Media.AdaptiveStreaming.DownloaderResponse')
export class DownloaderResponse { 
    bypassBandwidthMeasurement: boolean = null;
    contentLength: number = null;
    contentType: string = null;
    cookies: IVectorView<IHttpCookie> = null;
    headers: IMapView<string, string> = null;
    responseStream: IInputStream = null;
    uri: Uri = null;
    // constructor(pRequestUri: Uri, pHttpHeaders: IMapView<string, string>, pHttpCookies: IVectorView<IHttpCookie>);
    // constructor(pResponseUri: Uri, pResponseStream: IInputStream, contentLength: number, contentType: string, pHttpHeaders: IMapView<string, string>, bypassBandwidthMeasurement: boolean);
    constructor(...args) { }
}
