// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Media.AdaptiveStreaming 255.255.255.255 at Mon Mar 29 16:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { IPropertySet } from "winrt/Windows/Foundation/Collections/IPropertySet";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";
import { IMediaExtension } from "winrt/Windows/Media/IMediaExtension";

@GenerateShim('Microsoft.Media.AdaptiveStreaming.SmoothSchemeHandler')
export class SmoothSchemeHandler implements IMediaExtension { 
    setProperties(configuration: IPropertySet): void {
        console.warn('SmoothSchemeHandler#setProperties not implemented')
    }
}
