// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:11 2021
// </auto-generated>
// --------------------------------------------------

import { IStringable } from "../../../Foundation/IStringable";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Web.Http.Headers.HttpConnectionOptionHeaderValue')
export class HttpConnectionOptionHeaderValue implements IStringable { 
    token: string = null;
    constructor(token: string) {
        console.warn('HttpConnectionOptionHeaderValue.ctor not implemented')
    }
    toString(): string {
        throw new Error('HttpConnectionOptionHeaderValue#toString not implemented')
    }
    static parse(input: string): HttpConnectionOptionHeaderValue {
        throw new Error('HttpConnectionOptionHeaderValue#parse not implemented')
    }
    static tryParse(input: string): { succeeded: boolean, connectionOptionHeaderValue: HttpConnectionOptionHeaderValue } {
        throw new Error('HttpConnectionOptionHeaderValue#tryParse not implemented')
    }
}
