// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { IVectorView } from "../../Foundation/Collections/IVectorView`1";
import { Enumerable } from "../../Foundation/Interop/Enumerable";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { TypedEventHandler } from "../../Foundation/TypedEventHandler`2";
import { AudioEffect } from "./AudioEffect";

@GenerateShim('Windows.Media.Effects.AudioRenderEffectsManager')
export class AudioRenderEffectsManager { 
    getAudioRenderEffects(): IVectorView<AudioEffect> {
        throw new Error('AudioRenderEffectsManager#getAudioRenderEffects not implemented')
    }

    #audioRenderEffectsChanged: Set<TypedEventHandler<AudioRenderEffectsManager, any>> = new Set();
    @Enumerable(true)
    set onaudiorendereffectschanged(handler: TypedEventHandler<AudioRenderEffectsManager, any>) {
        this.#audioRenderEffectsChanged.add(handler);
    }

    addEventListener(name: string, handler: any) {
        switch (name) {
            case 'audiorendereffectschanged':
                this.#audioRenderEffectsChanged.add(handler);
                break;
        }
    }

    removeEventListener(name: string, handler: any) {
        switch (name) {
            case 'audiorendereffectschanged':
                this.#audioRenderEffectsChanged.delete(handler);
                break;
        }
    }
}
