// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IEntitlementId } from "./IEntitlementId";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Common.Fulfillment.EntitlementId')
export class EntitlementId implements IEntitlementId { 
    hasSkuId: boolean = null;
    productId: string = null;
    skuId: string = null;
    value: string = null;
    // constructor();
    // constructor(entitlementIdValue: string);
    // constructor(productId: string, skuId: string);
    constructor(...args) { }
    isSubclassOf(entitlementId: IEntitlementId): boolean {
        throw new Error('EntitlementId#isSubclassOf not implemented')
    }
}
