// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:08 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../Foundation/Interop/GenerateShim";
import { Color } from "./Color";

@GenerateShim('Windows.UI.ColorHelper')
export class ColorHelper { 
    static fromArgb(a: number, r: number, g: number, b: number): Color {
        throw new Error('ColorHelper#fromArgb not implemented')
    }
}
