// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { SocketQualityOfService } from "./SocketQualityOfService";

@GenerateShim('Windows.Networking.Sockets.DatagramSocketControl')
export class DatagramSocketControl { 
    qualityOfService: SocketQualityOfService = null;
    outboundUnicastHopLimit: number = null;
    inboundBufferSizeInBytes: number = null;
    dontFragment: boolean = null;
}
