// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { IAsyncAction } from "../../Foundation/IAsyncAction";
import { IClosable } from "../../Foundation/IClosable";
import { TypedEventHandler } from "../../Foundation/TypedEventHandler`2";
import { Uri } from "../../Foundation/Uri";
import { WebSocketClosedEventArgs } from "./WebSocketClosedEventArgs";
import { IOutputStream } from "../../Storage/Streams/IOutputStream";

export interface IWebSocket extends IClosable {
    outputStream: IOutputStream;
    connectAsync(uri: Uri): IAsyncAction;
    setRequestHeader(headerName: string, headerValue: string): void;
    closeWithStatus(code: number, reason: string): void;
    onclosed: TypedEventHandler<IWebSocket, WebSocketClosedEventArgs>;
    addEventListener(name: string, handler: any)
    removeEventListener(name: string, handler: any)
}
