// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { IAsyncAction } from "../../Foundation/IAsyncAction";
import { IClosable } from "../../Foundation/IClosable";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { NetworkAdapter } from "../Connectivity/NetworkAdapter";
import { EndpointPair } from "../EndpointPair";
import { HostName } from "../HostName";
import { SocketProtectionLevel } from "./SocketProtectionLevel";
import { StreamSocketControl } from "./StreamSocketControl";
import { StreamSocketInformation } from "./StreamSocketInformation";
import { IInputStream } from "../../Storage/Streams/IInputStream";
import { IOutputStream } from "../../Storage/Streams/IOutputStream";

@GenerateShim('Windows.Networking.Sockets.StreamSocket')
export class StreamSocket implements IClosable { 
    control: StreamSocketControl = null;
    information: StreamSocketInformation = null;
    inputStream: IInputStream = null;
    outputStream: IOutputStream = null;
    connectWithEndpointPairAsync(endpointPair: EndpointPair): IAsyncAction {
        throw new Error('StreamSocket#connectWithEndpointPairAsync not implemented')
    }
    connectAsync(remoteHostName: HostName, remoteServiceName: string): IAsyncAction {
        throw new Error('StreamSocket#connectAsync not implemented')
    }
    connectWithEndpointPairAndProtectionLevelAsync(endpointPair: EndpointPair, protectionLevel: SocketProtectionLevel): IAsyncAction {
        throw new Error('StreamSocket#connectWithEndpointPairAndProtectionLevelAsync not implemented')
    }
    connectWithProtectionLevelAsync(remoteHostName: HostName, remoteServiceName: string, protectionLevel: SocketProtectionLevel): IAsyncAction {
        throw new Error('StreamSocket#connectWithProtectionLevelAsync not implemented')
    }
    upgradeToSslAsync(protectionLevel: SocketProtectionLevel, validationHostName: HostName): IAsyncAction {
        throw new Error('StreamSocket#upgradeToSslAsync not implemented')
    }
    close(): void {
        console.warn('StreamSocket#close not implemented')
    }
    connectWithProtectionLevelAndAdapterAsync(remoteHostName: HostName, remoteServiceName: string, protectionLevel: SocketProtectionLevel, adapter: NetworkAdapter): IAsyncAction {
        throw new Error('StreamSocket#connectWithProtectionLevelAndAdapterAsync not implemented')
    }
}
