// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:07 2021
// </auto-generated>
// --------------------------------------------------

import { IImageProvider } from "../../IImageProvider";
import { InlineVideoAttributes } from "../BlockAttributes/InlineVideoAttributes";
import { ImageResourceDescriptor } from "../ImageResourceDescriptor";
import { IVector } from "winrt/Windows/Foundation/Collections/IVector`1";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('AppEx.Common.ArticleReader.Model.Block.InlineVideoBlock')
export class InlineVideoBlock implements IImageProvider, IStringable { 
    readonly type: string = null;
    attributes: InlineVideoAttributes = null;
    getImages(): IVector<ImageResourceDescriptor> {
        throw new Error('InlineVideoBlock#getImages not implemented')
    }
    toString(): string {
        throw new Error('InlineVideoBlock#toString not implemented')
    }
}
