// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.PerfTrack 255.255.255.255 at Mon Mar 29 22:41:48 2021
// </auto-generated>
// --------------------------------------------------

import { PerfTrackLogger } from "./PerfTrackLogger";

export interface IPerfTrackFactory {
    makeLogger(dataUploadEnabled: boolean): PerfTrackLogger;
}
