// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { IIterable } from "../../Foundation/Collections/IIterable`1";
import { IAsyncAction } from "../../Foundation/IAsyncAction";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { RegionOfInterest } from "./RegionOfInterest";

@GenerateShim('Windows.Media.Devices.RegionsOfInterestControl')
export class RegionsOfInterestControl { 
    autoExposureSupported: boolean = null;
    autoFocusSupported: boolean = null;
    autoWhiteBalanceSupported: boolean = null;
    maxRegions: number = null;
    setRegionsAsync(regions: IIterable<RegionOfInterest>): IAsyncAction {
        throw new Error('RegionsOfInterestControl#setRegionsAsync not implemented')
    }
    setRegionsWithLockAsync(regions: IIterable<RegionOfInterest>, lockValues: boolean): IAsyncAction {
        throw new Error('RegionsOfInterestControl#setRegionsWithLockAsync not implemented')
    }
    clearRegionsAsync(): IAsyncAction {
        throw new Error('RegionsOfInterestControl#clearRegionsAsync not implemented')
    }
}
