// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { Rect } from "../../Foundation/Rect";

@GenerateShim('Windows.Media.Devices.RegionOfInterest')
export class RegionOfInterest { 
    bounds: Rect = null;
    autoWhiteBalanceEnabled: boolean = null;
    autoFocusEnabled: boolean = null;
    autoExposureEnabled: boolean = null;
}
