(function(n){"use strict";var i='Invalid construction: AdSdkPlugin constructor must be called using the "new" operator.',r=WinJS.Application,t;r.addEventListener("activated",function(){var n=new MicrosoftNSJS.Advertising.AdSettingsControl({flyoutHtmlTemplateURI:"ms-appx:///MicrosoftAdvertising.SDK.Plugins.MMPPF.JS/html/MSASettingsPanel.html",resourceLoaderURI:"MicrosoftAdvertising/UIStrings"})});t=WinJS.Class.derive(n.PluginBase,function(t){if(!(this instanceof n.Plugins.AdSDKPlugin))throw i;n.PluginBase.call(this,t)},{_setOptions:function(t){n.Utilities.setOptions(this,t,{isEnabled:!0})},_onActivate:function(){return this._bindEvent("loading",this.mediaPlayer,this._onMediaPlayerLoading),!0},_onDeactivate:function(){this._cancelActiveLoad();this._unbindEvent("loading",this.mediaPlayer,this._onMediaPlayerLoading)},_onLoad:function(){},_onUnload:function(){},_onErrorOccurred:function(n){this.dispatchEvent("erroroccurred",n)},_onAdRefreshed:function(){this.dispatchEvent("adrefreshed")},_onUpdate:function(){this._cancelActiveLoad()},_cancelActiveLoad:function(){this._activeLoadPromise&&(this._activeLoadPromise.cancel(),this._activeLoadPromise=null)},_onMediaPlayerLoading:function(n){this._activeLoadPromise=this.playAd();this._activeLoadPromise&&n.detail.setPromise(this._activeLoadPromise)},playAd:function(){if(this.adTags!==null&&typeof this.adTags!="undefined")return this._getAdManifest().then(function(t){var r,u,i;try{switch(t.type.toLowerCase()){case"vmap":return i=this.mediaPlayer.vmapSchedulerPlugin,i.loadAds(t.uri);case"vast":if(r=new Microsoft.PlayerFramework.Js.Advertising.RemoteAdSource,r.type=Microsoft.Media.Advertising.VastAdPayloadHandler.adType,r.uri=new Windows.Foundation.Uri(t.uri),r.headers.insert("User-Agent","Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)"),this.mediaPlayer.playerState===n.PlayerState.unloaded)return this.mediaPlayer.adHandlerPlugin.playAd(r);i=this.mediaPlayer.adSchedulerPlugin;u=new n.Advertising.PrerollAdvertisement;u.source=r;i.advertisements.push(u);break;case"smartxml":return i=this.mediaPlayer.freeWheelPlugin,i.loadAds(t.uri);default:this._onErrorOccurred({errorMessage:"Invalid source uri type",errorCode:"Other"})}}catch(f){}}.bind(this),function(n){this.dispatchEvent("loadfailure",n)}.bind(this))},_isAdError:function(n){if(n===null||typeof n!="object")throw Error("Ad is null");return n.errorCode===null||typeof n.errorCode=="undefined"||n.errorCode===""?!1:!0},_getAdManifest:function(){var n=this,u=new MicrosoftAdvertising_MMPPF.MultimediaAdClient,r=new MicrosoftAdvertising_MMPPF.RendererOptions,t=new MicrosoftAdvertising_MMPPF.Placement,i;t.adUnitId=this.adUnitId;t.applicationId=this.applicationId;try{if(this.adTags!==null&&typeof this.adTags!="undefined")for(i in this.adTags)r.addRendererOption(i,this.adTags[i])}catch(err){n._onErrorOccurred({errorMessage:err,errorCode:"Other"})}return u.getAdAsync(t,r).then(function(t){if(n._isAdError(t)){n._onErrorOccurred({errorMessage:t.errorMessage,errorCode:t.errorCode});throw t.errorMessage;}else return n._onAdRefreshed(),{uri:t.sourceURI,type:t.sourceURIType}},function(){n._onErrorOccurred({errorMessage:err,errorCode:"Other"})})}});WinJS.Class.mix(n.MediaPlayer,{adSDKPlugin:{value:null,writable:!0,configurable:!0,adUnitId:null,applicationId:null,adTags:{}}});WinJS.Class.mix(t,n.Utilities.createEventProperties(["loadfailure","adrefreshed","erroroccurred"]));WinJS.Namespace.define("PlayerFramework.Plugins",{AdSDKPlugin:t})})(PlayerFramework);
/*!
  Copyright (C) Microsoft. All rights reserved.
  This library is supported for use in Windows Store apps only.
*/
(function(n){"use strict";var t=n.Class.define(function(n){if(!this._isNullOrUndefined(window)){if(this._isNullOrUndefined(window._msAdsAdSettingsControl)||window._msAdsAdSettingsControl.isInitialized!==!0){if(this._isNullOrUndefined(window._msAdsAdSettingsControl)||window._msAdsAdSettingsControl._objectName===MicrosoftNSJS.Advertising.AdSettingsControl.OBJECT_NAME){if(!this._isNullOrUndefined(window._msAdsAdSettingsControl)&&window._msAdsAdSettingsControl.isInitialized===!1)return this._logError("warning: window._msAdsAdSettingsControl already exists but is not initialized yet (are all promises complete?). Try again later or dispose and re-create."),window._msAdsAdSettingsControl}else this._logError("window._msAdsAdSettingsControl already exists but is not of correct object type [{0}]. Overwriting.",MicrosoftNSJS.Advertising.AdSettingsControl.OBJECT_NAME);try{this._objectName=MicrosoftNSJS.Advertising.AdSettingsControl.OBJECT_NAME;this._isInitialized=!1;window._msAdsAdSettingsControl=this;this._initialize(n);MicrosoftAdvertising.Shared.WinRT.UserInfoProvider.initialize().then(function(){this._isInitialized=!0;this._addSettingsFlyout()}.bind(this),function(n){this._logError("could not initialize UserInfoProvider. Error:",n);this._dispose()}.bind(this))}catch(t){this._dispose();this._logError("could not initialize AdSettingsControl error: {0}",t)}}return window._msAdsAdSettingsControl}},{_flyoutHtmlTemplateURI:"",_resourceLoader:null,_userInfoProvider:null,_targetingOptInState:null,_eventHandlers:{optToggle_Toggled:null,signInLink_Clicked:null,settingsFlyout_Activated:null},isInitialized:{get:function(){return this._isInitialized}},dispose:function(){try{this._dispose()}catch(n){try{this._logError("Could not dispose, exception thrown [{0}].",n)}catch(n){}}},_initialize:function(n){if(!this._isNullOrUndefined(n)&&(this._isNullOrUndefined(n.flyoutHtmlTemplateURI)||(this._flyoutHtmlTemplateURI=n.flyoutHtmlTemplateURI),!this._isNullOrUndefined(n.resourceLoaderURI)))try{this._resourceLoader=Windows.ApplicationModel.Resources.ResourceLoader(n.resourceLoaderURI)}catch(t){this._logError("Could not initialize, error: [{0}].",t)}this._userInfoProvider=MicrosoftAdvertising.Shared.WinRT.UserInfoProvider;this._targetingOptInState=MicrosoftAdvertising.Shared.WinRT.TargetingOptInState;this._createSettingsFlyoutEvent()},_addSettingsFlyout:function(){n.Application.addEventListener("settings",this._eventHandlers.settingsFlyout_Activated)},_createSettingsFlyoutEvent:function(){this._eventHandlers.settingsFlyout_Activated=function(t){try{if(MicrosoftAdvertising.Shared.WinRT.UserInfoProvider.isUserOptOutControlVisible()===!1)return;var i={name:"msaAdSettings",title:this._resourceLoader.getString("AdSettings_CommandText"),href:this._flyoutHtmlTemplateURI},r=Windows.UI.ApplicationSettings,u=new r.SettingsCommand(i.name,i.title,function(){n.UI.SettingsFlyout.showSettings(i.name,i.href)});t.detail.e.request.applicationCommands.append(u);this._wirePanelScript()}catch(f){this._logError("could not add settings flyout html in WinJS.Application.onsettings handler")}}.bind(this)},_wirePanelScript:function(){this._createPageEvents();var t=n.UI.Pages.define(this._flyoutHtmlTemplateURI,{ready:function(){document.getElementById("optToggle").winControl.addEventListener("change",this._eventHandlers.optToggle_Toggled);document.getElementById("signInLink").addEventListener("click",this._eventHandlers.signInLink_Clicked);this._updateResourceStrings();this._toggleProgress(!0);this._userInfoProvider.getGlobalTargetingOptInStateAsync().then(function(n){this._updateUI(n)}.bind(this),function(){this._showUnknownState()}.bind(this))}.bind(this),unload:function(){document.getElementById("optToggle").winControl.removeEventListener("change",this._eventHandlers.optToggle_Toggled);document.getElementById("signInLink").removeEventListener("click",this._eventHandlers.signInLink_Clicked)}.bind(this)})},_createPageEvents:function(){this._eventHandlers.optToggle_Toggled=function(n){try{this._userInfoProvider.setLocalTargetingOptInStateAsync(n.target.winControl.checked)}catch(i){var t=document.getElementById("optToggle");t.winControl.checked=!t.winControl.checked}}.bind(this);this._eventHandlers.signInLink_Clicked=function(){this._userInfoProvider.requestUserSignInAsync()}.bind(this)},_updateResourceStrings:function(){this._updateElementText("mainLabel","AdSettings_Flyout_Title",this._resourceLoader);this._updateElementText("heading1Label","AdSettings_Flyout_SectionName",this._resourceLoader);this._updateElementText("signInPrompt1","AdSettings_Flyout_SignInPrompt1",this._resourceLoader);this._updateElementText("signInLink","AdSettings_Flyout_SignInPrompt_SignIn",this._resourceLoader);this._updateElementText("signInPrompt2","AdSettings_Flyout_SignInPrompt2",this._resourceLoader);this._updateElementText("optedOutPrompt1","AdSettings_Flyout_OptedOut_Message1",this._resourceLoader);this._updateElementText("optOutMoreInfoLink","AdSettings_Flyout_OptedOut_Message_Here",this._resourceLoader);this._updateElementText("optedOutPrompt2","AdSettings_Flyout_OptedOut_Message2",this._resourceLoader);this._updateElementText("statusUnknownPrompt","AdSettings_Flyout_StatusUnknown_Message",this._resourceLoader);var n=document.getElementById("optToggle").winControl;n.title=this._resourceLoader.getString("AdSettings_Flyout_OptInSwitch_Header");n.labelOff=this._resourceLoader.getString("AdSettings_Flyout_OptInSwitch_Off");n.labelOn=this._resourceLoader.getString("AdSettings_Flyout_OptInSwitch_On");this._updateElementText("privacyStatementLink","AdSettings_Flyout_Privacy",this._resourceLoader)},_updateElementText:function(n,t,i){try{document.getElementById(n).innerText=i.getString(t)}catch(r){}},_updateUI:function(n){this._toggleProgress();var t=document.getElementById("optToggle");n===this._targetingOptInState.optedIn?(document.getElementById("optedOutPrompt").style.display="none",document.getElementById("signInPrompt").style.display="none",document.getElementById("statusUnknownPrompt").style.display="none",this._userInfoProvider.getLocalTargetingOptInStateAsync().then(function(n){t.winControl.checked=n!==this._targetingOptInState.optedOut?!0:!1;t.winControl.disabled=!1;t.style.display="block"}.bind(this))):n===this._targetingOptInState.userNotSignedIn?(document.getElementById("optedOutPrompt").style.display="none",document.getElementById("signInPrompt").style.display="block",document.getElementById("statusUnknownPrompt").style.display="none",t.winControl.disabled=!0,t.winControl.checked=!1,t.style.display="block"):n===this._targetingOptInState.optedOut?(document.getElementById("optedOutPrompt").style.display="block",document.getElementById("signInPrompt").style.display="none",document.getElementById("statusUnknownPrompt").style.display="none",t.winControl.disabled=!0,t.winControl.checked=!1,t.style.display="block"):n===this._targetingOptInState.unknown?this._showUnknownState():this._showUnknownState()},_showUnknownState:function(){var n=document.getElementById("optToggle");document.getElementById("optedOutPrompt").style.display="none";document.getElementById("signInPrompt").style.display="none";document.getElementById("statusUnknownPrompt").style.display="block";n.winControl.disabled=!0;n.winControl.checked=!1;n.style.display="block"},_toggleProgress:function(n){document.getElementById("progressRing").style.display=n?"block":"none"},_dispose:function(){n.Application.removeEventListener("settings",this._eventHandlers.settingsFlyout_Activated);this._isInitialized=!1;window._msAdsAdSettingsControl=null},_isNullOrUndefined:function(n){return typeof n=="undefined"||n===null?!0:!1},_logError:function(){}},{OBJECT_NAME:"MicrosoftNSJS.Advertising.AdSettingsControl"});n.Namespace.define("MicrosoftNSJS.Advertising",{AdSettingsControl:t})})(WinJS);
// SIG // Begin signature block
// SIG // MIIaqwYJKoZIhvcNAQcCoIIanDCCGpgCAQExCzAJBgUr
// SIG // DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
// SIG // gjcCAR4wJAIBAQQQEODJBs441BGiowAQS9NQkAIBAAIB
// SIG // AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFPjHik0J7LBP
// SIG // ZhLtv2SkVlRpxCZWoIIVgjCCBMMwggOroAMCAQICEzMA
// SIG // AAA0JDFAyaDBeY0AAAAAADQwDQYJKoZIhvcNAQEFBQAw
// SIG // dzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UEAxMYTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBMB4XDTEzMDMyNzIw
// SIG // MDgyNVoXDTE0MDYyNzIwMDgyNVowgbMxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xDTALBgNVBAsTBE1PUFIxJzAlBgNVBAsT
// SIG // Hm5DaXBoZXIgRFNFIEVTTjpCOEVDLTMwQTQtNzE0NDEl
// SIG // MCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
// SIG // dmljZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
// SIG // ggEBAOUaB60KlizUtjRkyzQg8rwEWIKLtQncUtRwn+Jc
// SIG // LOf1aqT1ti6xgYZZAexJbCkEHvU4i1cY9cAyDe00kOzG
// SIG // ReW7igolqu+he4fY8XBnSs1q3OavBZE97QVw60HPq7El
// SIG // ZrurorcY+XgTeHXNizNcfe1nxO0D/SisWGDBe72AjTOT
// SIG // YWIIsY9REmWPQX7E1SXpLWZB00M0+peB+PyHoe05Uh/4
// SIG // 6T7/XoDJBjYH29u5asc3z4a1GktK1CXyx8iNr2FnitpT
// SIG // L/NMHoMsY8qgEFIRuoFYc0KE4zSy7uqTvkyC0H2WC09/
// SIG // L88QXRpFZqsC8V8kAEbBwVXSg3JCIoY6pL6TUAECAwEA
// SIG // AaOCAQkwggEFMB0GA1UdDgQWBBRfS0LeDLk4oNRmNo1W
// SIG // +3RZSWaBKzAfBgNVHSMEGDAWgBQjNPjZUkZwCu1A+3b7
// SIG // syuwwzWzDzBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
// SIG // Y3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0
// SIG // cy9NaWNyb3NvZnRUaW1lU3RhbXBQQ0EuY3JsMFgGCCsG
// SIG // AQUFBwEBBEwwSjBIBggrBgEFBQcwAoY8aHR0cDovL3d3
// SIG // dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNyb3Nv
// SIG // ZnRUaW1lU3RhbXBQQ0EuY3J0MBMGA1UdJQQMMAoGCCsG
// SIG // AQUFBwMIMA0GCSqGSIb3DQEBBQUAA4IBAQAPQlCg1R6t
// SIG // Fz8fCqYrN4pnWC2xME8778JXaexl00zFUHLycyX25IQC
// SIG // xXUccVhDq/HJqo7fym9YPInnL816Nexm19Veuo6fV4aU
// SIG // EKDrUTetV/YneyNPGdjgbXYEJTBhEq2ljqMmtkjlU/JF
// SIG // TsW4iScQnanjzyPpeWyuk2g6GvMTxBS2ejqeQdqZVp7Q
// SIG // 0+AWlpByTK8B9yQG+xkrmLJVzHqf6JI6azF7gPMOnleL
// SIG // t+YFtjklmpeCKTaLOK6uixqs7ufsLr9LLqUHNYHzEyDq
// SIG // tEqTnr+cg1Z/rRUvXClxC5RnOPwwv2Xn9Tne6iLth4yr
// SIG // sju1AcKt4PyOJRUMIr6fDO0dMIIE7DCCA9SgAwIBAgIT
// SIG // MwAAAMps1TISNcThVQABAAAAyjANBgkqhkiG9w0BAQUF
// SIG // ADB5MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSMwIQYDVQQDExpN
// SIG // aWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQTAeFw0xNDA0
// SIG // MjIxNzM5MDBaFw0xNTA3MjIxNzM5MDBaMIGDMQswCQYD
// SIG // VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
// SIG // A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMQ0wCwYDVQQLEwRNT1BSMR4wHAYD
// SIG // VQQDExVNaWNyb3NvZnQgQ29ycG9yYXRpb24wggEiMA0G
// SIG // CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCWcV3tBkb6
// SIG // hMudW7dGx7DhtBE5A62xFXNgnOuntm4aPD//ZeM08aal
// SIG // IV5WmWxY5JKhClzC09xSLwxlmiBhQFMxnGyPIX26+f4T
// SIG // UFJglTpbuVildGFBqZTgrSZOTKGXcEknXnxnyk8ecYRG
// SIG // vB1LtuIPxcYnyQfmegqlFwAZTHBFOC2BtFCqxWfR+nm8
// SIG // xcyhcpv0JTSY+FTfEjk4Ei+ka6Wafsdi0dzP7T00+Lnf
// SIG // NTC67HkyqeGprFVNTH9MVsMTC3bxB/nMR6z7iNVSpR4o
// SIG // +j0tz8+EmIZxZRHPhckJRIbhb+ex/KxARKWpiyM/gkmd
// SIG // 1ZZZUBNZGHP/QwytK9R/MEBnAgMBAAGjggFgMIIBXDAT
// SIG // BgNVHSUEDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUH17i
// SIG // XVCNVoa+SjzPBOinh7XLv4MwUQYDVR0RBEowSKRGMEQx
// SIG // DTALBgNVBAsTBE1PUFIxMzAxBgNVBAUTKjMxNTk1K2I0
// SIG // MjE4ZjEzLTZmY2EtNDkwZi05YzQ3LTNmYzU1N2RmYzQ0
// SIG // MDAfBgNVHSMEGDAWgBTLEejK0rQWWAHJNy4zFha5TJoK
// SIG // HzBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1p
// SIG // Y3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWND
// SIG // b2RTaWdQQ0FfMDgtMzEtMjAxMC5jcmwwWgYIKwYBBQUH
// SIG // AQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1p
// SIG // Y3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY0NvZFNpZ1BD
// SIG // QV8wOC0zMS0yMDEwLmNydDANBgkqhkiG9w0BAQUFAAOC
// SIG // AQEAd1zr15E9zb17g9mFqbBDnXN8F8kP7Tbbx7UsG177
// SIG // VAU6g3FAgQmit3EmXtZ9tmw7yapfXQMYKh0nfgfpxWUf
// SIG // tc8Nt1THKDhaiOd7wRm2VjK64szLk9uvbg9dRPXUsO8b
// SIG // 1U7Brw7vIJvy4f4nXejF/2H2GdIoCiKd381wgp4Yctgj
// SIG // zHosQ+7/6sDg5h2qnpczAFJvB7jTiGzepAY1p8JThmUR
// SIG // dwmPNVm52IaoAP74MX0s9IwFncDB1XdybOlNWSaD8cKy
// SIG // iFeTNQB8UCu8Wfz+HCk4gtPeUpdFKRhOlludul8bo/En
// SIG // UOoHlehtNA04V9w3KDWVOjic1O1qhV0OIhFeezCCBbww
// SIG // ggOkoAMCAQICCmEzJhoAAAAAADEwDQYJKoZIhvcNAQEF
// SIG // BQAwXzETMBEGCgmSJomT8ixkARkWA2NvbTEZMBcGCgmS
// SIG // JomT8ixkARkWCW1pY3Jvc29mdDEtMCsGA1UEAxMkTWlj
// SIG // cm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
// SIG // MB4XDTEwMDgzMTIyMTkzMloXDTIwMDgzMTIyMjkzMlow
// SIG // eTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEjMCEGA1UEAxMaTWlj
// SIG // cm9zb2Z0IENvZGUgU2lnbmluZyBQQ0EwggEiMA0GCSqG
// SIG // SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCycllcGTBkvx2a
// SIG // YCAgQpl2U2w+G9ZvzMvx6mv+lxYQ4N86dIMaty+gMuz/
// SIG // 3sJCTiPVcgDbNVcKicquIEn08GisTUuNpb15S3GbRwfa
// SIG // /SXfnXWIz6pzRH/XgdvzvfI2pMlcRdyvrT3gKGiXGqel
// SIG // cnNW8ReU5P01lHKg1nZfHndFg4U4FtBzWwW6Z1KNpbJp
// SIG // L9oZC/6SdCnidi9U3RQwWfjSjWL9y8lfRjFQuScT5EAw
// SIG // z3IpECgixzdOPaAyPZDNoTgGhVxOVoIoKgUyt0vXT2Pn
// SIG // 0i1i8UU956wIAPZGoZ7RW4wmU+h6qkryRs83PDietHdc
// SIG // pReejcsRj1Y8wawJXwPTAgMBAAGjggFeMIIBWjAPBgNV
// SIG // HRMBAf8EBTADAQH/MB0GA1UdDgQWBBTLEejK0rQWWAHJ
// SIG // Ny4zFha5TJoKHzALBgNVHQ8EBAMCAYYwEgYJKwYBBAGC
// SIG // NxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQU/dExTtMm
// SIG // ipXhmGA7qDFvpjy82C0wGQYJKwYBBAGCNxQCBAweCgBT
// SIG // AHUAYgBDAEEwHwYDVR0jBBgwFoAUDqyCYEBWJ5flJRP8
// SIG // KuEKU5VZ5KQwUAYDVR0fBEkwRzBFoEOgQYY/aHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvbWljcm9zb2Z0cm9vdGNlcnQuY3JsMFQGCCsGAQUF
// SIG // BwEBBEgwRjBEBggrBgEFBQcwAoY4aHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNyb3NvZnRS
// SIG // b290Q2VydC5jcnQwDQYJKoZIhvcNAQEFBQADggIBAFk5
// SIG // Pn8mRq/rb0CxMrVq6w4vbqhJ9+tfde1MOy3XQ60L/svp
// SIG // LTGjI8x8UJiAIV2sPS9MuqKoVpzjcLu4tPh5tUly9z7q
// SIG // QX/K4QwXaculnCAt+gtQxFbNLeNK0rxw56gNogOlVuC4
// SIG // iktX8pVCnPHz7+7jhh80PLhWmvBTI4UqpIIck+KUBx3y
// SIG // 4k74jKHK6BOlkU7IG9KPcpUqcW2bGvgc8FPWZ8wi/1wd
// SIG // zaKMvSeyeWNWRKJRzfnpo1hW3ZsCRUQvX/TartSCMm78
// SIG // pJUT5Otp56miLL7IKxAOZY6Z2/Wi+hImCWU4lPF6H0q7
// SIG // 0eFW6NB4lhhcyTUWX92THUmOLb6tNEQc7hAVGgBd3TVb
// SIG // Ic6YxwnuhQ6MT20OE049fClInHLR82zKwexwo1eSV32U
// SIG // jaAbSANa98+jZwp0pTbtLS8XyOZyNxL0b7E8Z4L5UrKN
// SIG // MxZlHg6K3RDeZPRvzkbU0xfpecQEtNP7LN8fip6sCvsT
// SIG // J0Ct5PnhqX9GuwdgR2VgQE6wQuxO7bN2edgKNAltHIAx
// SIG // H+IOVN3lofvlRxCtZJj/UBYufL8FIXrilUEnacOTj5XJ
// SIG // jdibIa4NXJzwoq6GaIMMai27dmsAHZat8hZ79haDJLmI
// SIG // z2qoRzEvmtzjcT3XAH5iR9HOiMm4GPoOco3Boz2vAkBq
// SIG // /2mbluIQqBC0N1AI1sM9MIIGBzCCA++gAwIBAgIKYRZo
// SIG // NAAAAAAAHDANBgkqhkiG9w0BAQUFADBfMRMwEQYKCZIm
// SIG // iZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJbWlj
// SIG // cm9zb2Z0MS0wKwYDVQQDEyRNaWNyb3NvZnQgUm9vdCBD
// SIG // ZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMDcwNDAzMTI1
// SIG // MzA5WhcNMjEwNDAzMTMwMzA5WjB3MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSEwHwYDVQQDExhNaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
// SIG // ggEKAoIBAQCfoWyx39tIkip8ay4Z4b3i48WZUSNQrc7d
// SIG // GE4kD+7Rp9FMrXQwIBHrB9VUlRVJlBtCkq6YXDAm2gBr
// SIG // 6Hu97IkHD/cOBJjwicwfyzMkh53y9GccLPx754gd6udO
// SIG // o6HBI1PKjfpFzwnQXq/QsEIEovmmbJNn1yjcRlOwhtDl
// SIG // KEYuJ6yGT1VSDOQDLPtqkJAwbofzWTCd+n7Wl7PoIZd+
// SIG // +NIT8wi3U21StEWQn0gASkdmEScpZqiX5NMGgUqi+YSn
// SIG // EUcUCYKfhO1VeP4Bmh1QCIUAEDBG7bfeI0a7xC1Un68e
// SIG // eEExd8yb3zuDk6FhArUdDbH895uyAc4iS1T/+QXDwiAL
// SIG // AgMBAAGjggGrMIIBpzAPBgNVHRMBAf8EBTADAQH/MB0G
// SIG // A1UdDgQWBBQjNPjZUkZwCu1A+3b7syuwwzWzDzALBgNV
// SIG // HQ8EBAMCAYYwEAYJKwYBBAGCNxUBBAMCAQAwgZgGA1Ud
// SIG // IwSBkDCBjYAUDqyCYEBWJ5flJRP8KuEKU5VZ5KShY6Rh
// SIG // MF8xEzARBgoJkiaJk/IsZAEZFgNjb20xGTAXBgoJkiaJ
// SIG // k/IsZAEZFgltaWNyb3NvZnQxLTArBgNVBAMTJE1pY3Jv
// SIG // c29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eYIQ
// SIG // ea0WoUqgpa1Mc1j0BxMuZTBQBgNVHR8ESTBHMEWgQ6BB
// SIG // hj9odHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
// SIG // bC9wcm9kdWN0cy9taWNyb3NvZnRyb290Y2VydC5jcmww
// SIG // VAYIKwYBBQUHAQEESDBGMEQGCCsGAQUFBzAChjhodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01p
// SIG // Y3Jvc29mdFJvb3RDZXJ0LmNydDATBgNVHSUEDDAKBggr
// SIG // BgEFBQcDCDANBgkqhkiG9w0BAQUFAAOCAgEAEJeKw1wD
// SIG // RDbd6bStd9vOeVFNAbEudHFbbQwTq86+e4+4LtQSooxt
// SIG // YrhXAstOIBNQmd16QOJXu69YmhzhHQGGrLt48ovQ7DsB
// SIG // 7uK+jwoFyI1I4vBTFd1Pq5Lk541q1YDB5pTyBi+FA+mR
// SIG // KiQicPv2/OR4mS4N9wficLwYTp2OawpylbihOZxnLcVR
// SIG // DupiXD8WmIsgP+IHGjL5zDFKdjE9K3ILyOpwPf+FChPf
// SIG // wgphjvDXuBfrTot/xTUrXqO/67x9C0J71FNyIe4wyrt4
// SIG // ZVxbARcKFA7S2hSY9Ty5ZlizLS/n+YWGzFFW6J1wlGys
// SIG // OUzU9nm/qhh6YinvopspNAZ3GmLJPR5tH4LwC8csu89D
// SIG // s+X57H2146SodDW4TsVxIxImdgs8UoxxWkZDFLyzs7BN
// SIG // Z8ifQv+AeSGAnhUwZuhCEl4ayJ4iIdBD6Svpu/RIzCzU
// SIG // 2DKATCYqSCRfWupW76bemZ3KOm+9gSd0BhHudiG/m4LB
// SIG // J1S2sWo9iaF2YbRuoROmv6pH8BJv/YoybLL+31HIjCPJ
// SIG // Zr2dHYcSZAI9La9Zj7jkIeW1sMpjtHhUBdRBLlCslLCl
// SIG // eKuzoJZ1GtmShxN1Ii8yqAhuoFuMJb+g74TKIdbrHk/J
// SIG // mu5J4PcBZW+JC33Iacjmbuqnl84xKf8OxVtc2E0bodj6
// SIG // L54/LlUWa8kTo/0xggSVMIIEkQIBATCBkDB5MQswCQYD
// SIG // VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
// SIG // A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMSMwIQYDVQQDExpNaWNyb3NvZnQg
// SIG // Q29kZSBTaWduaW5nIFBDQQITMwAAAMps1TISNcThVQAB
// SIG // AAAAyjAJBgUrDgMCGgUAoIGuMBkGCSqGSIb3DQEJAzEM
// SIG // BgorBgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgor
// SIG // BgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEWBBSjBsNiIDDm
// SIG // w+hia/j+tDdrpjNKvjBOBgorBgEEAYI3AgEMMUAwPqAe
// SIG // gBwAQQBkAFMARABLAFAAbAB1AGcAaQBuAC4AagBzoRyA
// SIG // Gmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS8gMA0GCSqG
// SIG // SIb3DQEBAQUABIIBAGTa17VHUM1KRnODUCi6C+bucjZy
// SIG // Gu+POEq+MSSlanrPTRptJXq7URmylwmlR6H9DMd2JxYl
// SIG // 9QTrAVPLTyjLaho0r3lOTkuQF2pZxEWEHUV1+sq55li2
// SIG // p9jypQIPfnVUXkcdbYyCv/XGYrRwfzxBUVVjytEAKmxy
// SIG // 3KrWUvGO9ALmTbK2OEdaWBB9/ZrvHRRilkzVdvqzLvko
// SIG // wBas76RtmOowsShQyG6Z5FmVYdzM7tdDMOR6RufnUQMr
// SIG // yoEZtopXzovCkDhvSqIeYi5W7+NxaQYZP4cu+ETDkDcz
// SIG // 4+VByc3Pk3JgDtzP18oOrZVqtuuWNL0akH6Sj6NIsiTI
// SIG // l+dPuRChggIoMIICJAYJKoZIhvcNAQkGMYICFTCCAhEC
// SIG // AQEwgY4wdzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
// SIG // c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
// SIG // BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UE
// SIG // AxMYTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBAhMzAAAA
// SIG // NCQxQMmgwXmNAAAAAAA0MAkGBSsOAwIaBQCgXTAYBgkq
// SIG // hkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJ
// SIG // BTEPFw0xNDA2MDUwMTUzMjdaMCMGCSqGSIb3DQEJBDEW
// SIG // BBSOwr6IwYAIorf2PAY8q1UgEEaaxDANBgkqhkiG9w0B
// SIG // AQUFAASCAQAlfb/B9j38O8y9kWWXRthPlV43Aw9YPYbJ
// SIG // k3NrBaYeTLpA8/ja2Kw4pnxY9lNNPKHQYEgiB1mm7QHw
// SIG // aMixGX5OkwX55QDfzt+f7clyRXhBuUWzWTMrdTeLoq4R
// SIG // xS7rYfW6AS8ao5546PLgy7DHae/uFLT058rzRxozeAuW
// SIG // zgpfhzYiRGtcHZQabsyhxztogAwvHEH59Lu7bLp+uAxe
// SIG // BbV6QskvSrb0uVdDOUVUOmDgSKrFJuCvDGI2E+/xdRV7
// SIG // L4Hc5y6eUZlRDltZHI2R/wQf67n9klEbw7LgAk44OnQ5
// SIG // 3sJDzwEIyeDtsiZgioWdOqZIVM6w9/ejH0aar0pp6G9Y
// SIG // End signature block
