// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { AsyncActionCompletedHandler } from "../../Foundation/AsyncActionCompletedHandler";
import { AsyncStatus } from "../../Foundation/AsyncStatus";
import { HResult } from "../../Foundation/HResult";
import { IAsyncAction } from "../../Foundation/IAsyncAction";
import { IAsyncInfo } from "../../Foundation/IAsyncInfo";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Devices.Sms.DeleteSmsMessagesOperation')
export class DeleteSmsMessagesOperation implements IAsyncAction { 
    completed: AsyncActionCompletedHandler = null;
    errorCode: number = null;
    id: number = null;
    status: AsyncStatus = null;
    getResults(): void {
        console.warn('DeleteSmsMessagesOperation#getResults not implemented')
    }
    cancel(): void {
        console.warn('DeleteSmsMessagesOperation#cancel not implemented')
    }
    close(): void {
        console.warn('DeleteSmsMessagesOperation#close not implemented')
    }
}
