// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { SmsDevice } from "./SmsDevice";
import { AsyncOperationCompletedHandler } from "../../Foundation/AsyncOperationCompletedHandler`1";
import { AsyncStatus } from "../../Foundation/AsyncStatus";
import { HResult } from "../../Foundation/HResult";
import { IAsyncInfo } from "../../Foundation/IAsyncInfo";
import { IAsyncOperation } from "../../Foundation/IAsyncOperation`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Devices.Sms.GetSmsDeviceOperation')
export class GetSmsDeviceOperation implements IAsyncOperation<SmsDevice>  { 
    errorCode: number = null;
    id: number = null;
    status: AsyncStatus = null;
    completed: AsyncOperationCompletedHandler<SmsDevice> = null;
    getResults(): SmsDevice {
        throw new Error('GetSmsDeviceOperation#getResults not implemented')
    }
    cancel(): void {
        console.warn('GetSmsDeviceOperation#cancel not implemented')
    }
    close(): void {
        console.warn('GetSmsDeviceOperation#close not implemented')
    }
}
