// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { ISmsBinaryMessage } from "./ISmsBinaryMessage";
import { ISmsMessage } from "./ISmsMessage";
import { SmsDataFormat } from "./SmsDataFormat";
import { SmsMessageClass } from "./SmsMessageClass";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Devices.Sms.SmsBinaryMessage')
export class SmsBinaryMessage implements ISmsBinaryMessage, ISmsMessage { 
    format: SmsDataFormat = null;
    id: number = null;
    messageClass: SmsMessageClass = null;
    getData(): number[] {
        throw new Error('SmsBinaryMessage#getData not implemented')
    }
    setData(value: number[]): void {
        console.warn('SmsBinaryMessage#setData not implemented')
    }
}
