// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IApplicationLifetimeManager } from "./IApplicationLifetimeManager";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.ApplicationLifetimeManager')
export class ApplicationLifetimeManager implements IApplicationLifetimeManager { 
    raiseActivated(args: any): void {
        console.warn('ApplicationLifetimeManager#raiseActivated not implemented')
    }
    raiseResuming(): void {
        console.warn('ApplicationLifetimeManager#raiseResuming not implemented')
    }
    raiseSuspending(): void {
        console.warn('ApplicationLifetimeManager#raiseSuspending not implemented')
    }
}
