// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

export enum CollectionSyncError {
    maxPlaylistsReached = 3238068560,
    collectionFull = 3238068561,
    accountMerged = 3238068608,
    syncError = 3238068624,
}
