// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:37 2021
// </auto-generated>
// --------------------------------------------------

export enum Platform {
    backgroundTask = 12000,
    lockScreen = 12001,
    cancelBackgroundTask = 200081,
    accountDialogStep = 200100,
    accountDialogOverall = 200101,
    wldcdbmigrationHresult = 200102,
    wldctableMigrationErrors = 200103,
}
