// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:37 2021
// </auto-generated>
// --------------------------------------------------

export enum SkyDrive {
    callbackError = 13000,
    moskyCommandusage = 200110,
    moSkySearchAction = 200109,
    fileExtensionUsed = 13003,
    moskyAuthentication = 200049,
    moskyFilemanagementmovedelete = 200048,
    moSkyFREVideoPercentage = 200116,
}
