// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { FilesQueryCountOperation } from "./FilesQueryCountOperation";
import { IFilesQuery } from "./IFilesQuery";
import { IQuery } from "./IQuery";
import { IQueryChangedEventArgs } from "./IQueryChangedEventArgs";
import { IQueryPage } from "./IQueryPage";
import { IQueryResult } from "./IQueryResult";
import { EventHandler } from "winrt/Windows/Foundation/EventHandler`1";
import { IAsyncAction } from "winrt/Windows/Foundation/IAsyncAction";
import { AsyncOperationWithProgress, IAsyncOperationWithProgress } from "winrt/Windows/Foundation/IAsyncOperationWithProgress`2";
import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";
import { IClosable } from "winrt/Windows/Foundation/IClosable";
import { Enumerable } from "winrt/Windows/Foundation/Interop/Enumerable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Queries.FilesQuery')
export class FilesQuery implements IFilesQuery, IQuery, IClosable { 
    watchAll: number = null;
    trackId: number = null;
    pageSize: number = null;
    currentPage: IQueryPage = null;
    nextPage: IQueryPage = null;
    previousPage: IQueryPage = null;
    executeAsync(): IAsyncOperationWithProgress<IQueryResult, number> {
        return AsyncOperationWithProgress.from(async () => { return { json: "[]" }; })
    }
    getCountAsync(): FilesQueryCountOperation {
        throw new Error('FilesQuery#getCountAsync not implemented')
    }
    setCursorPosition(index: number): void {
        console.warn('FilesQuery#setCursorPosition not implemented')
    }
    getGroupsAsync(): IAsyncOperationWithProgress<IQueryResult, number> {
        throw new Error('FilesQuery#getGroupsAsync not implemented')
    }
    refreshAsync(): IAsyncAction {
        throw new Error('FilesQuery#refreshAsync not implemented')
    }
    getItemIndexAsync(objectId: number): IAsyncOperation<number> {
        throw new Error('FilesQuery#getItemIndexAsync not implemented')
    }
    execute(): IAsyncOperationWithProgress<IQueryResult, number> {
        throw new Error('FilesQuery#execute not implemented')
    }
    pauseAsync(): IAsyncAction {
        throw new Error('FilesQuery#pauseAsync not implemented')
    }
    resumeAsync(): IAsyncAction {
        throw new Error('FilesQuery#resumeAsync not implemented')
    }
    close(): void {
        console.warn('FilesQuery#close not implemented')
    }

    private __queryChanged: Set<EventHandler<IQueryChangedEventArgs>> = new Set();
    @Enumerable(true)
    set onquerychanged(handler: EventHandler<IQueryChangedEventArgs>) {
        this.__queryChanged.add(handler);
    }

    addEventListener(name: string, handler: any) {
        switch (name) {
            case 'querychanged':
                this.__queryChanged.add(handler);
                break;
        }
    }

    removeEventListener(name: string, handler: any) {
        switch (name) {
            case 'querychanged':
                this.__queryChanged.delete(handler);
                break;
        }
    }
}
