// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { GenreDataset } from "./GenreDataset";
import { IGenresQuery } from "./IGenresQuery";
import { IGenresQueryOperation } from "./IGenresQueryOperation";
import { IQueryResult } from "./IQueryResult";
import { AsyncOperationProgressHandler } from "winrt/Windows/Foundation/AsyncOperationProgressHandler`2";
import { AsyncOperationWithProgressCompletedHandler } from "winrt/Windows/Foundation/AsyncOperationWithProgressCompletedHandler`2";
import { AsyncStatus } from "winrt/Windows/Foundation/AsyncStatus";
import { HResult } from "winrt/Windows/Foundation/HResult";
import { IAsyncInfo } from "winrt/Windows/Foundation/IAsyncInfo";
import { IAsyncOperationWithProgress } from "winrt/Windows/Foundation/IAsyncOperationWithProgress`2";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Queries.GenresQueryOperation')
export class GenresQueryOperation implements IGenresQueryOperation, IAsyncOperationWithProgress<IQueryResult, number>, IAsyncInfo { 
    query: IGenresQuery = null;
    errorCode: number = null;
    id: number = null;
    status: AsyncStatus = null;
    progress: AsyncOperationProgressHandler<IQueryResult, number> = null;
    completed: AsyncOperationWithProgressCompletedHandler<IQueryResult, number> = null;
    wait(): GenreDataset {
        throw new Error('GenresQueryOperation#wait not implemented')
    }
    getResults(): IQueryResult {
        throw new Error('GenresQueryOperation#getResults not implemented')
    }
    cancel(): void {
        console.warn('GenresQueryOperation#cancel not implemented')
    }
    close(): void {
        console.warn('GenresQueryOperation#close not implemented')
    }
}
