// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

export enum ObjectType {
    video = 100,
    tvseries = 101,
    tvseason = 102,
    track = 103,
    album = 104,
    person = 105,
    genre = 106,
    playlist = 107,
    review = 108,
    bio = 109,
    editorial = 110,
    game = 111,
    smartDJ = 112,
    closedCaption = 113,
    folder = 114,
    smartVJ = 115,
    bundle = 116,
}
