// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { IQueryResult } from "./IQueryResult";
import { IVideosQuery } from "./IVideosQuery";
import { IVideosQueryOperation } from "./IVideosQueryOperation";
import { VideoDataset } from "./VideoDataset";
import { AsyncOperationProgressHandler } from "winrt/Windows/Foundation/AsyncOperationProgressHandler`2";
import { AsyncOperationWithProgressCompletedHandler } from "winrt/Windows/Foundation/AsyncOperationWithProgressCompletedHandler`2";
import { AsyncStatus } from "winrt/Windows/Foundation/AsyncStatus";
import { HResult } from "winrt/Windows/Foundation/HResult";
import { IAsyncInfo } from "winrt/Windows/Foundation/IAsyncInfo";
import { IAsyncOperationWithProgress } from "winrt/Windows/Foundation/IAsyncOperationWithProgress`2";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Queries.VideosQueryGroupsOperation')
export class VideosQueryGroupsOperation implements IVideosQueryOperation, IAsyncOperationWithProgress<IQueryResult, number>, IAsyncInfo { 
    progress: AsyncOperationProgressHandler<IQueryResult, number> = null;
    completed: AsyncOperationWithProgressCompletedHandler<IQueryResult, number> = null;
    query: IVideosQuery = null;
    errorCode: number = null;
    id: number = null;
    status: AsyncStatus = null;
    wait(): VideoDataset {
        throw new Error('VideosQueryGroupsOperation#wait not implemented')
    }
    getResults(): IQueryResult {
        throw new Error('VideosQueryGroupsOperation#getResults not implemented')
    }
    cancel(): void {
        console.warn('VideosQueryGroupsOperation#cancel not implemented')
    }
    close(): void {
        console.warn('VideosQueryGroupsOperation#close not implemented')
    }
}
