// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { AsyncOperationCompletedHandler } from "winrt/Windows/Foundation/AsyncOperationCompletedHandler`1";
import { AsyncStatus } from "winrt/Windows/Foundation/AsyncStatus";
import { HResult } from "winrt/Windows/Foundation/HResult";
import { IAsyncInfo } from "winrt/Windows/Foundation/IAsyncInfo";
import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Queries.WatchlistsQueryCountOperation')
export class WatchlistsQueryCountOperation implements IAsyncOperation<number>, IAsyncInfo { 
    completed: AsyncOperationCompletedHandler<number> = null;
    errorCode: number = null;
    id: number = null;
    status: AsyncStatus = null;
    getResults(): number {
        throw new Error('WatchlistsQueryCountOperation#getResults not implemented')
    }
    cancel(): void {
        console.warn('WatchlistsQueryCountOperation#cancel not implemented')
    }
    close(): void {
        console.warn('WatchlistsQueryCountOperation#close not implemented')
    }
}
