// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { IQuery } from "./IQuery";
import { IQueryChangedEventArgs } from "./IQueryChangedEventArgs";
import { IQueryPage } from "./IQueryPage";
import { IQueryResult } from "./IQueryResult";
import { IWatchlistItemsQuery } from "./IWatchlistItemsQuery";
import { ObjectType } from "./ObjectType";
import { WatchlistItemsQueryCountOperation } from "./WatchlistItemsQueryCountOperation";
import { WatchlistItemsSortBy } from "./WatchlistItemsSortBy";
import { EventHandler } from "winrt/Windows/Foundation/EventHandler`1";
import { IAsyncAction } from "winrt/Windows/Foundation/IAsyncAction";
import { IAsyncOperationWithProgress } from "winrt/Windows/Foundation/IAsyncOperationWithProgress`2";
import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";
import { IClosable } from "winrt/Windows/Foundation/IClosable";
import { Enumerable } from "winrt/Windows/Foundation/Interop/Enumerable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Queries.WatchlistItemsQuery')
export class WatchlistItemsQuery implements IWatchlistItemsQuery, IQuery, IClosable { 
    watchlistId: number = null;
    watchAll: number = null;
    primarySortBy: WatchlistItemsSortBy = null;
    pageSize: number = null;
    mediaItemObjectType: ObjectType = null;
    currentPage: IQueryPage = null;
    nextPage: IQueryPage = null;
    previousPage: IQueryPage = null;
    executeAsync(): IAsyncOperationWithProgress<IQueryResult, number> {
        throw new Error('WatchlistItemsQuery#executeAsync not implemented')
    }
    getCountAsync(): WatchlistItemsQueryCountOperation {
        throw new Error('WatchlistItemsQuery#getCountAsync not implemented')
    }
    setCursorPosition(index: number): void {
        console.warn('WatchlistItemsQuery#setCursorPosition not implemented')
    }
    getGroupsAsync(): IAsyncOperationWithProgress<IQueryResult, number> {
        throw new Error('WatchlistItemsQuery#getGroupsAsync not implemented')
    }
    refreshAsync(): IAsyncAction {
        throw new Error('WatchlistItemsQuery#refreshAsync not implemented')
    }
    getItemIndexAsync(objectId: number): IAsyncOperation<number> {
        throw new Error('WatchlistItemsQuery#getItemIndexAsync not implemented')
    }
    execute(): IAsyncOperationWithProgress<IQueryResult, number> {
        throw new Error('WatchlistItemsQuery#execute not implemented')
    }
    pauseAsync(): IAsyncAction {
        throw new Error('WatchlistItemsQuery#pauseAsync not implemented')
    }
    resumeAsync(): IAsyncAction {
        throw new Error('WatchlistItemsQuery#resumeAsync not implemented')
    }
    close(): void {
        console.warn('WatchlistItemsQuery#close not implemented')
    }

    private __queryChanged: Set<EventHandler<IQueryChangedEventArgs>> = new Set();
    @Enumerable(true)
    set onquerychanged(handler: EventHandler<IQueryChangedEventArgs>) {
        this.__queryChanged.add(handler);
    }

    addEventListener(name: string, handler: any) {
        switch (name) {
            case 'querychanged':
                this.__queryChanged.add(handler);
                break;
        }
    }

    removeEventListener(name: string, handler: any) {
        switch (name) {
            case 'querychanged':
                this.__queryChanged.delete(handler);
                break;
        }
    }
}
