// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

export enum WatchlistsSortBy {
    none = 11200,
    nameAscending = 11201,
    nameDescending = 11202,
    dateCreatedAscending = 11203,
    dateCreatedDescending = 11204,
}
