// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:07 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Storage.SystemMusicProperties')
export class SystemMusicProperties { 
    albumArtist: string = null;
    albumTitle: string = null;
    artist: string = null;
    composer: string = null;
    conductor: string = null;
    displayArtist: string = null;
    genre: string = null;
    trackNumber: string = null;
}
