// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:07 2021
// </auto-generated>
// --------------------------------------------------

import { StreamedFileFailureMode } from "./StreamedFileFailureMode";

export interface IStreamedFileDataRequest {
    failAndClose(failureMode: StreamedFileFailureMode): void;
}
