// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { DateTime } from "../../Foundation/DateTime";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { PlayToSource } from "./PlayToSource";
import { PlayToSourceDeferral } from "./PlayToSourceDeferral";

@GenerateShim('Windows.Media.PlayTo.PlayToSourceRequest')
export class PlayToSourceRequest { 
    deadline: Date = null;
    displayErrorString(errorString: string): void {
        console.warn('PlayToSourceRequest#displayErrorString not implemented')
    }
    getDeferral(): PlayToSourceDeferral {
        throw new Error('PlayToSourceRequest#getDeferral not implemented')
    }
    setSource(value: PlayToSource): void {
        console.warn('PlayToSourceRequest#setSource not implemented')
    }
}
