// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:11 2021
// </auto-generated>
// --------------------------------------------------

import { IMap } from "../../Foundation/Collections/IMap`2";
import { IClosable } from "../../Foundation/IClosable";
import { IStringable } from "../../Foundation/IStringable";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { Uri } from "../../Foundation/Uri";
import { HttpRequestHeaderCollection } from "./Headers/HttpRequestHeaderCollection";
import { HttpMethod } from "./HttpMethod";
import { HttpTransportInformation } from "./HttpTransportInformation";
import { IHttpContent } from "./IHttpContent";

@GenerateShim('Windows.Web.Http.HttpRequestMessage')
export class HttpRequestMessage implements IClosable, IStringable { 
    requestUri: Uri = null;
    method: HttpMethod = null;
    content: IHttpContent = null;
    headers: HttpRequestHeaderCollection = null;
    properties: IMap<string, any> = null;
    transportInformation: HttpTransportInformation = null;
    // constructor();
    // constructor(method: HttpMethod, uri: Uri);
    constructor(...args) { }
    close(): void {
        console.warn('HttpRequestMessage#close not implemented')
    }
    toString(): string {
        throw new Error('HttpRequestMessage#toString not implemented')
    }
}
