// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:08 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";
import { Point } from "../../../Foundation/Point";

@GenerateShim('Windows.UI.Input.Inking.InkStrokeRenderingSegment')
export class InkStrokeRenderingSegment { 
    bezierControlPoint1: Point = null;
    bezierControlPoint2: Point = null;
    position: Point = null;
    pressure: number = null;
    tiltX: number = null;
    tiltY: number = null;
    twist: number = null;
}
