export namespace WindowsLive {
    export namespace Cid {
        export enum CidFormat {
            hexidecimal,
            decimal,
            guid,
        }
    }
    export namespace Config {
        export namespace Shared {
            export enum AppId {
                chat,
                call,
                mail,
                calendar,
                people,
                photo,
                skydrive,
                testapp1,
                testapp2,
                testapp3,
                max,
            }
            export enum ApplicationId {
                chat,
                call,
                mail,
                calendar,
                people,
                photo,
                skydrive,
                testapp1,
                testapp2,
                testapp3,
                livecomm,
                max,
            }
        }
    }
    export enum FallbackLogic {
        countryRegion,
        language,
    }
    export namespace Instrumentation {
        export enum ApiId {
            unknown,
            unitTest,
            skyDrive_Json_GetItems = 2501013,
            skyDrive_Json_DeleteItems = 2501025,
            si_ScenarioQos = 3701400,
            storage_Dav_Get = 4202000,
            storage_Dav_Put,
            shareAnything_Status = 9800000,
            facebook_Graph_PostComment = 11500005,
            facebook_Fql_Multiquery_GetComments = 11500007,
            facebook_Fql_MultiQuery_GetLikes = 11500026,
            facebook_Graph_PostLike,
            facebook_Graph_DeleteLike,
            facebook_Fql_Multiquery_GetContactsActivities = 11500035,
            facebook_Fql_Multiquery_GetActivities,
            facebook_Fql_Multiquery_GetSocialNotifications,
            facebook_Fql_Multiquery_GetPhotos = 11500043,
            facebook_Fql_Multiquery_GetAlbums,
            facebook_Fql_Multiquery_GetPhotosAlbumsVideos = 11500046,
            facebook_Fql_Multiquery_GetActivity = 11500048,
            facebook_Fql_Multiquery_GetPhoto,
            facebook_Fql_Multiquery_GetAlbum,
            facebook_Fql_Query_GetUnreadNotificationCount,
            facebook_LegacyRest_MarkNotificationsRead,
            facebook_Graph_PostFeed,
            psa_SN_ReactionsAPI_Retweets_Get = 29300009,
            psa_SN_ReactionsAPI_Retweets_Post,
            psa_SN_ReactionsAPI_Replies_Get,
            psa_SN_ReactionsAPI_Replies_Post,
            psa_SN_ActivityStreamAPI_RecentActivity,
            psa_SN_ActivityStreamAPI_WhatsNew,
            psa_SN_ActivityStreamAPI_Notifications = 29300016,
            psa_SN_ReactionsAPI_Favorites_Get,
            psa_SN_ReactionsAPI_Favorites_Post,
            psa_SN_ReactionsAPI_Favorites_Delete,
            psa_SN_ReactionsAPI_Comments_Get,
            psa_SN_ReactionsAPI_Comments_Post,
            psa_SN_ReactionsAPI_Forwards_Get,
            psa_SN_ReactionsAPI_Forwards_Post,
            fms_LoadSurvey = 29700000,
        }
        export enum ErrorType {
            success,
            client,
            server,
            network,
            fault,
        }
        export namespace Ids {
            export enum Calendar {
                calendarSnapshotNumEvents = 200132,
                calendarSnapshotEventDuration,
                calendarSnapshotEventService,
                calendarEventExit = 200147,
                calendarViewClick = 200145,
                calendarViewLaunch = 200144,
                calendarCreateEvent = 200146,
                calendarFreeBusyAPICall = 200154,
                calendarPlatformErrors = 200238,
                calendarDatePickerClosed = 200258,
                calendarDatePickerLaunch,
                calendarBackgroundFlyout,
                calendarAgendaShowMore,
                calendarNavAndAppBarInvoke = 200283,
                inviteResponse = 200333,
                showCalendar,
                calendarProviderCreateEvent = 200329,
                calendarProviderCreateEventUpdate,
            }
            export enum Common {
                experienceId = 1,
                referringAppId,
                osVersion,
                osProductType,
                osBuildNumber,
                osServicePack,
                osSku,
                wloemId,
                appVersion,
                windowsOemId,
                pcModel,
                osLanguage,
                wloemDealId,
                winOobeDate,
                wlsuiteLang,
                osInfo,
                optInStatus,
                wloobeDate,
                brandId,
                msftInternal,
                mcam,
                uploadId,
                buildVersion,
                buildArchitecture,
                buildType,
                buildBranch,
                buildComputerName,
                buildUserName,
                buildWin8Branch,
                buildWin8Build,
                buildLocalTimeStamp,
                appIdString,
                environment,
                localUserId,
                roamingUserId,
            }
            export enum Contact {
                instanceCount = 6001,
                serverExperienceId,
            }
            export enum General {
                productMinutes = 1000,
                cid,
                anid,
                muid,
                shipAssert,
                appStart,
                shipAssertOverall,
                httpCallComplete,
                sendSmile = 1010,
                sendSmileErrorCount,
                thirdPartyAPICall = 1015,
                thirdPartyAPICall2,
                thirdPartyAPICall3 = 200130,
                visibleMinutes = 1017,
                resumeCount,
                modernPackage,
            }
            export enum Mail {
                syncComplete = 200228,
                modernMailEmailOperations = 200087,
                modernMailNavigate = 200335,
                initSyncComplete = 8002,
                sendButtonActive,
                fileSent = 8005,
                addressWellSelectionMade = 8008,
                sendMailModern,
                sendMailWithAttachment,
                skyDriveMailLeaveOutbox,
                addressWellSuggestionRank = 200159,
                modernMailActiveAccounts = 200104,
                modernMailConversationThreadingEnabled = 200121,
                mailTriageCommand = 200311,
                modernMailCommand = 200292,
                mailFormatCommand = 200291,
                shareToMailOnSend = 200229,
                modernUserLogin = 200297,
                connectedMailAccountsOnMailVisible = 200299,
                composeMailSent = 200331,
                composeCommandSend = 8503,
                composeCommandDiscard,
                composeCommandCloseSave,
                composeBoldUseCount = 8510,
                composeItalicsUseCount,
                composeUnderlineUseCount,
                composeFontFamilyUseCount,
                composeFontSizeUseCount,
                composeFontColorUseCount,
                composeAddFilesUseCount,
                composeAddPhotosAndVideosUseCount,
                composeLeftAlignUseCount,
                composeCenterUseCount,
                composeRightAlignUseCount,
                composeNumberedListUseCount,
                composeBulletedListUseCount,
                composeHighlightUseCount,
                composeInsertLinkUseCount,
                composePriorityHighUseCount,
                composePriorityLowUseCount,
                composePriorityNormalUseCount,
                composeRedoUseCount,
                composePeoplePickerUseCount,
                composeEmojiUseCount,
                composeUndoUseCount,
                composeIndentUseCount,
                composeOutdentUseCount,
                composeClearFormattingUseCount,
                composeSelectAllUseCount,
                composeToggleBccUseCount,
                easConnectionDead = 8540,
                pushConnection = 200052,
                wnsGetchannel = 200056,
                triggerManualBackgroundTask = 200080,
                backgroundSyncRecoveryDetails = 200091,
                communicationsFolder = 200235,
                mailAppBarInvoke = 200280,
            }
            export enum ModernPhotoDevices {
                modernPhotosNumberOfDevices = 200029,
                dmxconsumerConsumercallhresult = 200033,
            }
            export enum ModernPhotoImport {
                photosImportSessionData = 200057,
                photosImportFileExtensions = 200062,
                photosImportErrors,
            }
            export enum Package {
                dynamicConfigMetaData = 200041,
                mandatoryUpdateShownCount = 3001,
                launchstatuschange = 200040,
            }
            export enum People {
                identityControlActivate = 9000,
                contactAddSave = 9100,
                profileDetailsView,
                profileDetailsViewFavorite,
                profileDetailsViewNonFavorite,
                profileDetailsDeleteContact,
                profileDetailsActions,
                profileEditSave,
                profileEditCancel,
                socialPageViewed = 9500,
                socialReactionUpdated,
                socialShare = 200105,
                peopleClickthrough = 200082,
            }
            export enum Photo {
                rehydrationCount = 10001,
                failedRehydrationCount,
                playToSessionInteraction,
                searchZeroResults,
                searchSomeResults,
                commandClicked,
                playToItemFailure,
                folderDepth,
                openWithInsideLibraryCount = 10015,
                openWithOutsideLibraryCount,
                photosDatabaseSize = 10018,
                grovelFailure = 10020,
                dataRetrieval,
                platformP2PTelemetry = 200046,
                photosDataSystemGrovel = 200067,
                photosSourcesLaunch = 200114,
            }
            export enum Pimt {
                modernMSNPConnectToServer = 11000,
                messagingplatformBackgroundexecution = 200026,
            }
            export enum Platform {
                backgroundTask = 12000,
                lockScreen,
                cancelBackgroundTask = 200081,
                accountDialogStep = 200100,
                accountDialogOverall,
                wldcdbmigrationHresult,
                wldctableMigrationErrors,
            }
            export enum Self {
                configHash = 2000,
                numberOfThrottledQosCalls,
                biciErrorCount,
                lastBiciErrorCode,
                deletedLogCount,
                lastBiciErrorLocation,
            }
            export enum SkyDrive {
                callbackError = 13000,
                moskyCommandusage = 200110,
                moSkySearchAction = 200109,
                fileExtensionUsed = 13003,
                moskyAuthentication = 200049,
                moskyFilemanagementmovedelete = 200048,
                moSkyFREVideoPercentage = 200116,
            }
            export enum Video {
                photosVideoPlayback = 200123,
            }
        }
        export enum PropertyId {
            unknown,
            skyDrive = 25,
            storage = 42,
            modernSkydrive = 55,
            modernPeople = 57,
            shareAnything = 98,
            facebook = 115,
            psa = 294,
            fms = 298,
        }
        export enum QosHeaderType {
            dependentApi = 1,
            internalApi,
            incomingApi,
            scenario,
        }
        export enum ScenarioId {
            unknown,
            si_UnitTest = 50200,
            si_Unknown,
            modernSkyDrive_Viewing_GetItems = 50500,
            modernSkyDrive_DownloadFile,
            modernSkyDrive_UploadFile,
            modernSkyDrive_FileManagement_Move = 50510,
            modernSkyDrive_FileManagement_Copy,
            modernSkyDrive_FileManagement_Rename,
            modernSkyDrive_FileManagement_Delete,
            modernSkyDrive_FileManagement_CreateNewFolder,
            modernSendaSmile_ShowSurvey = 50600,
            modernPeople_GetWhatsNewActivities = 50700,
            modernPeople_GetRecentActivities,
            modernPeople_GetComments,
            modernPeople_GetReactions,
            modernPeople_PostComment,
            modernPeople_PostReaction,
            modernPeople_DeleteReaction,
            modernPeople_GetAlbums,
            modernPeople_GetPhotos,
            modernPeople_GetActivity,
            modernPeople_GetAlbum,
            modernPeople_GetPhoto,
            modernPeople_GetUnreadNotificationsCount,
            modernPeople_GetNotifications,
            modernPeople_MarkNotificationsRead,
            modernPeople_PostShare,
            modernPeople_GetMoreWhatsNewActivities,
            modernPeople_GetMoreRecentActivities,
        }
    }
    export namespace Photomail {
        export enum ExifOrientation {
            none,
            clockwise90Degrees,
            clockwise180Degrees,
            clockwise270Degrees,
        }
        export enum ImageResizeOption {
            small,
            large,
            original,
            custom,
        }
    }
    export namespace Platform {
        export enum AbchContactType {
            unknown,
            regular,
            me,
            circle,
            connection,
            implicit,
        }
        export enum AbchShellContactType {
            none,
            fan,
            pstn,
            buddyProfile,
            unknown,
        }
        export enum AccountAuthType {
            none,
            liveId,
            oAuth,
            password,
        }
        export enum AccountIconType {
            exchange,
            outlook,
            other,
        }
        export enum AccountSort {
            name,
            rank,
        }
        export enum AccountType {
            liveId,
            eas,
            pop,
            imap,
            withoutPlugins,
            easAccountFactory,
            imapAccountFactory,
            popAccountFactory,
        }
        export enum ApplicationScenario {
            calendar,
            mail,
            people,
            peopleSearch,
            publish,
            social,
        }
        export enum AttachmentComposeStatus {
            notStarted,
            failed,
            inProgress,
            done,
        }
        export enum AttachmentSyncStatus {
            notStarted = 1,
            failed,
            inProgress,
            done,
        }
        export enum AttachmentUIType {
            ordinary = 1,
            embedded,
            hidden,
        }
        export enum BodyDownloadStatus {
            upToDate,
            failed,
            inProgress,
        }
        export namespace Calendar {
            export enum AttendeeType {
                required = 1,
                optional,
                resource,
            }
            export enum BusyStatus {
                free,
                tentative,
                busy,
                outOfOffice,
                workingElsewhere,
            }
            export enum DataType {
                plainText = 1,
                html,
                rtf,
                mime,
            }
            export enum DayOfWeek {
                sunday = 1,
                monday,
                tuesday = 4,
                wednesday = 8,
                thursday = 16,
                friday = 32,
                saturday = 64,
                weekDays = 62,
                weekendDays = 65,
                all = 127,
            }
            export enum ErrorPriority {
                lowest = 1,
                low = 3,
                medium = 10,
                high = 100,
            }
            export enum ErrorType {
                unknown,
                easParse,
                easApplyToStore,
                easUpload,
                easDelete,
                easConflictResolutionAborted,
                easMeetingResponseRejected,
                unknownHighest,
            }
            export enum EventSortOrder {
                defaultSort,
                snapSort,
                notificationsSort,
                noSortAll,
            }
            export enum EventType {
                single,
                series,
                instanceOfSeries,
                exceptionToSeries,
            }
            export enum FirstDayOfWeek {
                sunday,
                monday,
                tuesday,
                wednesday,
                thursday,
                friday,
                saturday,
            }
            export enum FreeBusyStatus {
                error,
                success,
                ambiguous,
                unknown,
                dlerror,
                tooManyRecipients,
                tooManyMembers,
            }
            export enum GetEventsOptions {
                none,
                noCreateRange,
            }
            export enum MeetingMessageType {
                none,
                initialRequest,
                fullUpdate,
                informationalUpdate,
                outdated,
                delegatorCopy,
                delegateCopy,
            }
            export enum MeetingStatus {
                notAMeeting,
                isAMeeting,
                isReceived,
                isCanceled = 4,
                isForwarded = 8,
                meetingReceived = 3,
                meetingCanceled = 5,
                meetingCanceledAndReceived = 7,
                meetingForwarded = 9,
                meetingReceivedAndForwarded = 11,
                meetingCanceledAndForwarded = 13,
                meetingCanceledReceivedAndForwarded = 15,
                all = 15,
            }
            export enum RangeState {
                created,
                building,
                built,
            }
            export enum RangeType {
                invalid,
                primary,
                extension,
                secondary,
            }
            export enum RecurrenceType {
                daily,
                weekly,
                monthly,
                monthlyOnDay,
                yearly = 5,
                yearlyOnDay,
            }
            export enum ResponseType {
                none,
                organizer,
                tentative,
                accepted,
                declined,
                notResponded,
            }
            export enum Sensitivity {
                normal,
                personal,
                private,
                confidential,
            }
            export enum ServerCapability {
                none,
                htmlBody,
                statusWorkingElsewhere,
                attendeeType = 4,
                attendeeStatus = 8,
                calendarType = 16,
                leapMonth = 32,
                firstDayOfWeek = 64,
                responseRequested = 128,
                disallowNewTimeProposal = 256,
                appointmentReplyTime = 512,
                responseType = 1024,
                attendeesInExceptions = 2048,
                canRespond = 4096,
                canCancel = 8192,
                meetingResponseCommandOnEvent = 16384,
                requestFreeBusy = 32768,
                canForward = 65536,
                canReplaceMime = 131072,
            }
            export enum Status {
                success,
                errorAccountRequired = -2058027008,
                errorAccountInvalid,
                errorCalendarRequired = -2058026992,
                errorCalendarInvalid,
                errorCalendarNameInvalid,
                errorCalendarReadOnly,
                errorUIDGeneration = -2058026976,
                errorUIDConversionToString,
                errorAttendeeInvalidResponseType = -2058026960,
                errorAttendeeOrganizerNotAllowed,
                errorAttendeeInvalidAttendeeType,
                errorAttendeeCommitEventInstead,
                errorRangeStartMustBeLessThanEnd = -2058026944,
                errorTooManyEvents,
                errorIndexBeyondEnd,
                errorInvalidSort,
                errorRangeAlreadyRegistered,
                errorDetailsInvalidDataType = -2058026928,
                errorDetailsInvalidResponseType,
                errorEventRequired = -2058026752,
                errorEventInvalid,
                errorEventEndLessThanStart,
                errorEventDateTooSmall,
                errorEventDateTooLarge,
                errorEventInvalidBusyStatus,
                errorEventInvalidSensitivity,
                errorEventInvalidMeetingStatus,
                errorEventInvalidBeforeCommit,
                errorEventOccurenceFieldReadOnly,
                errorEventExceptionDeleteRequired = -2058026736,
                errorEventInvalidOccurrenceTime,
                errorEventNoException,
                errorEventNoReminder,
                errorNotRecurring = -2058026496,
                errorNotSeries,
                errorTZNameInvalid,
                errorRangeStartLessThanZero,
                errorRangeEndLessThanStart,
                errorInvalidRecurrenceType,
                errorOccurrencesTooSmall,
                errorOccurrencesTooLarge,
                errorIntervalTooSmall,
                errorIntervalTooLarge,
                errorInvalidWeekOfMonth = -2058026480,
                errorInvalidDayOfWeek,
                errorInvalidMonthOfYear,
                errorInvalidDayOfMonth,
                errorInvalidFirstDayOfWeek,
                errorRecurrenceInvalid,
                errorExceptionsOverlap,
                errorExceptionsStartOnSameDay,
                errorReminderForDifferentOccurrence,
                errorUntilLessThanStart,
            }
            export enum WeekOfMonth {
                first = 1,
                second,
                third,
                fourth,
                last,
            }
        }
        export enum CalendarFolderType {
            defaultFolder = 1,
        }
        export enum CalendarMessageType {
            none,
            request,
            responseAccepted,
            responseDeclined,
            responseTentative,
            cancelled,
            other,
        }
        export enum ClientCreateOptions {
            normal,
            delayResources,
            failIfNoUser,
            cacheAuthInTest = 4,
            failIfUnverified = 8,
            createRetailExperienceUser = 16,
            createPrimaryAccountUser = 32,
            getPendingPrimaryAccountUser = 64,
        }
        export enum CollectionChangeType {
            itemAdded,
            itemChanged,
            itemRemoved,
            batchBegin,
            batchEnd,
            reset,
            localSearchComplete,
            serverSearchComplete,
        }
        export enum ConfigArea {
            calendar,
            chat,
            mail,
            people,
            photos,
            platform,
            shared,
            sharing,
            test,
            skyDrive,
            max,
        }
        export enum ConfigCloud {
            prod,
            int,
            dogfood,
            max,
        }
        export enum ConfigureType {
            notSupported,
            createConnectedAccount,
            editOnClient,
            editOnWeb,
        }
        export enum ConnectableFilter {
            normal,
            excludeIfAnyAccountIsConnected,
            includeConnectedAccounts,
        }
        export enum ConnectedFilter {
            normal,
            includeDisabledAccounts,
        }
        export enum ContactFolderType {
            foreignNetwork,
            defaultFolder,
            meContact,
            people,
        }
        export enum ContactIMType {
            windowsLive,
            yahoo,
            office,
            none,
            foreignNetwork,
            skype,
        }
        export enum ContactLinkingType {
            windowsLive,
            none,
        }
        export enum ContactNameType {
            firstAndLast,
        }
        export enum ContactStatus {
            offline,
            away,
            online,
            busy,
            appearOffline,
            maxCount,
        }
        export enum ContactTrustLevel {
            close = 1,
            normal,
            farLevel,
            none,
        }
        export enum FavoriteInsertPosition {
            insertFirst,
            insertLast,
            insertBefore,
            insertAfter,
        }
        export enum FavoritesFilter {
            all,
            favorites,
            nonFavorites,
        }
        export enum FilterCriteria {
            all,
            unread,
            flagged,
            unseen,
        }
        export enum FolderAction {
            messageViewed = 2000,
            messageAction = 2000,
        }
        export enum FolderType {
            mail = 1,
            calendar,
            contacts,
        }
        export enum HintState {
            defaultAccount,
            primaryAccount,
            firstParty,
            superHint,
            hint,
            none,
        }
        export enum IncludeSentItemsInConversationCache {
            min,
            enabled = 0,
            disabled,
            rebuildingEnabled,
            rebuildingDisabled,
            max = 3,
        }
        export enum MailBodyType {
            html = 1,
            plainText,
            calendar,
            sanitized,
            max,
        }
        export enum MailFolderType {
            min,
            userGenerated = 0,
            inbox,
            drafts,
            deletedItems,
            sentItems,
            junkMail,
            outbox,
            allMail,
            starred,
            important,
            junkMailAutoCreate,
            max = 10,
        }
        export enum MailMessageChangeOperation {
            markAsRead,
            markAsUnread,
            flag,
            unflag,
            permanentDelete,
        }
        export enum MailMessageImportance {
            normal = 1,
            low,
            high,
        }
        export enum MailMessageLastVerb {
            unknown,
            forward,
            replyToSender,
            replyToAll,
        }
        export enum MailRuleActionType {
            min,
            move = 0,
            addCategory,
            removeCategory,
            max = 2,
        }
        export enum MailRuleCategoryId {
            min,
            none = 0,
            newsletter,
            social,
            max = 2,
        }
        export enum MailRuleDeferredActionType {
            min,
            none = 0,
            days,
            count,
            max = 2,
        }
        export enum MailViewScenario {
            navPane,
            allPeople,
            allFolders,
            move,
            systemCategories,
        }
        export enum MailViewType {
            none,
            flagged,
            allPinnedPeople = 1000,
            person = 1100,
            draft = 2000,
            outbox = 2100,
            deletedItems = 2200,
            sentItems = 2300,
            junkMail = 2400,
            inbox = 2500,
            userGeneratedFolder = 2600,
            newsletter = 3000,
            social = 3100,
        }
        export namespace Meetings {
            export namespace Private {
                export enum Response {
                    accepted = 1,
                    tentative,
                    declined,
                }
            }
        }
        export enum MriType {
            invalid,
            passport,
            federated,
            telephone = 4,
            skype = 8,
            circle,
            tempGroup,
            networkMember = 13,
            network,
            jaguire = 16,
            yahoo = 32,
        }
        export enum NetworkConnectionStatus {
            disconnected,
            connecting,
            connected,
        }
        export enum NetworkInfoPSAState {
            notSet,
            accept,
            reject,
            maybe,
            error,
        }
        export enum NetworkOffers {
            none,
            contactAgg,
            contactImport,
            contactInvite = 4,
            recentActivityPublish = 8,
            dashboardAgg = 16,
            activityPublish = 32,
            statusPublish = 64,
            clientPublish = 128,
            statusIngestion = 256,
            extensibleEmail = 512,
            clientSubscribe = 1024,
            commentPublish = 2048,
            supportIM = 4096,
            clientMail = 8192,
            clientCalendar = 16384,
            clientContactSync = 32768,
            mediaAgg = 65536,
            socialNotifications = 131072,
            offlineIM = 262144,
            clientMailImap = 8388608,
            allKnown = 262143,
            defaultAccountOffers = 61440,
        }
        export enum OnlineStatusFilter {
            all,
            notOffline,
        }
        export enum OutboxQueue {
            sendMail = 1,
            photoMailSkyDrive,
        }
        export enum PeoplePickerFilter {
            none,
            hasPhone,
            hasEmail,
            hasLocation = 4,
            canChat = 8,
        }
        export enum PeopleSearchType {
            invalid,
            addressWell,
            chatAddressWell,
            searchCharm,
            peoplePicker,
        }
        export enum PhotoMailFlags {
            isSkyDriveAttachments = 1,
            allowRecipientsToEdit,
            imageResizeOption = 12,
            hasDocument = 16,
            hasPhoto = 32,
            hasVideo = 64,
        }
        export enum PMFileType {
            unknown = 1,
            photo,
            video,
            other,
            url,
        }
        export enum PolicyComplianceResults {
            compliant,
            userNotAnAdmin,
            userCanceledPolicyDialog,
            userHasBlankPassword = 4,
            adminsHaveBlankPasswords = 8,
            usersCannotChangePassword = 16,
            connectedAdminProviderIsWeak = 32,
            connectedUserProviderIsWeak = 64,
            connectedAdminPasswordIsWeak = 128,
            connectedUserPasswordIsWeak = 256,
            notProtectedBitLocker = 512,
            notProtected3rdParty = 1024,
            protectionSuspendedBitLocker = 2048,
            protectionSuspended3rdParty = 4096,
            lockNotConfiguredBitLocker = 8192,
            lockNotConfigured3rdParty = 16384,
            osVolumeNotProtectedBitLocker = 32768,
            osVolumeNotProtected3rdParty = 65536,
            protectionNotYetEnabledBitLocker = 131072,
            protectionNotYetEnabled3rdParty = 262144,
            noFeatureLicenseBitLocker = 524288,
            noFeatureLicense3rdParty = 1048576,
            unExpectedFailure = 2097152,
            otherNotSupported = 4194304,
        }
        export namespace Private {
            export enum AccountConstants {
                maximumConcurrentPushConnections = 4,
            }
            export enum AccountState {
                adding,
                deletingLocal,
                deleting,
                normal,
            }
            export enum AutoPinState {
                unknown,
                needed,
                pinned,
            }
            export enum DeprecatedSignatureType {
                defaultLocalized,
                userDefined,
            }
            export enum DownloadWorkItemAction {
                enqueue = 1,
                cancel,
            }
            export enum EasiState {
                unknown,
                easi,
                mailSupported,
            }
            export enum FolderChangeType {
                invalid,
                insert,
                delete,
                move = 4,
                rename = 8,
                moveAndRename = 12,
            }
            export enum FolderDeleteState {
                notDeleted,
                deletedLocally,
                ancestorDeletedLocally,
            }
            export enum FolderPriority {
                critical,
                important,
                other,
            }
            export enum MailChangeCommand {
                invalid,
                processMailMigration,
                updateConversation,
                updateAllConversations,
                updateAllConversationsOnly,
                updateOnMessageAdd,
                updateOnMessageMove,
                updateOnMessageChange,
                markFolderConversationsAsProcessed,
                moveConversation,
                markConversationFlagged,
                markConversationUnflagged,
                markConversationRead,
                markConversationUnread,
                changeViewPinnedStatus,
                clearUnseenMessages,
                updateIncludeSentItemsInThread,
                updateLinkTable,
                updateLinkTableForSystemCategory,
                updateFolderSpecialType,
                updateSearchMail,
                max = 20,
            }
            export enum MailChangeCommandPriority {
                priorityHigh,
                priorityNormal = 100,
                priorityLow = 200,
            }
            export enum SearchMailServerType {
                none,
                eas,
                imap,
            }
            export enum ServerSearchType {
                invalid,
                people,
                mail,
                recipient,
                localMail,
                peopleBackground,
            }
            export enum StashChangeType {
                invalid,
                insert,
                update,
                delete,
                copy,
            }
        }
        export enum RelevanceAction {
            invalid,
            sendMail,
            receiveMail,
        }
        export enum RelevanceEntityType {
            invalid,
            recipient,
        }
        export enum RelevanceScenario {
            invalid,
            toLine,
            peopleView,
        }
        export enum ResourceState {
            none,
            connecting,
            connected,
            disconnecting,
            error,
        }
        export enum ResourceType {
            calendar,
            contacts,
            mail,
            storage,
            accounts,
            catalogScenarioDocument,
            catalogServicesDocument,
            meContactFolder,
            roamingSettings,
            mailRule,
            clientPublish,
            clientSubscribe,
            contactAgg,
            dashboardAgg,
            socialNotifications,
            statusPublish,
        }
        export enum RestartNeededReason {
            accountDisconnected,
            accountSwitched,
            unrecoverableCrash,
        }
        export enum Result {
            success,
            authNotAttempted = -2066743295,
            serverNotAttempted,
            credentialMissing,
            cannotCreatePopAccounts,
            primaryAccountSwitched,
            userCanceled,
            platformSuspended,
            objectNotCommitted,
            cannotMakeMicrosoftAccountAsPrimaryAccount,
            primaryAccountAlreadyConnected,
            primaryAccountNotPending,
            cannotAddAliasOfMicrosoftAccount,
            invalidAuthenticationTarget = -2138701823,
            accountUpdateRequired = -2138701819,
            accountLocked = -2138701817,
            passwordUpdateRequired = -2138701820,
            forceSignIn = -2138701818,
            parentalConsentRequired = -2138701816,
            emailVerificationRequired,
            actionRequired = -2138701812,
            accountSuspendedCompromise = -2138701814,
            accountSuspendedAbuse,
            authRequestThrottled = -2138701808,
            defaultAccountDoesNotExist = -2147023579,
            passwordDoesNotExist = -2146893042,
            passwordLogonFailure = -2147023570,
            nteDecryptionFailure = -2146893780,
            invalidServerCertificate = -2146697191,
            certExpired = -2146762495,
            certChainValidityBadNesting,
            certBadRole,
            certLengthConstraintViolated,
            certWithUnknowExtMarkedCritical,
            certBadPurpose,
            certNotIssuedByParent,
            certMissingImportantField,
            certBadChain = -2146762486,
            certRevoked = -2146762484,
            certUntrustedTestRoot,
            certUntrustedRoot = -2146762487,
            certRevocationCheckFailed = -2146762482,
            certCNNoMatch,
            certWrongUsage,
            certInvalidPolicy = -2146762477,
            certInvalidName,
            certSelectionNeeded = -2066743040,
            autoDiscoveryNotAttempted,
            autoDiscoveryFailed,
            autoDiscoveryNoChange,
            localFolderChangesLost = -2066742781,
            s_FAIL_CONVERSION_DEVICE = 1,
            e_FAIL_SERVER = -2063589369,
            e_INVALID_XMLRESPONSE = -2063589359,
            e_AIRSYNCLAYER_INVALID_OBJECT,
            e_UNEXPECTED_PROTOCOL_VERSION = -2063589353,
            e_XMLPARSE_WRONG_NODE_TYPE = -2063589351,
            e_XMLPARSE_TAG_UNKNOWN,
            e_XMLPARSE_UNEXPECTED_TAG,
            e_XMLPARSE_BAD_ELEMENT,
            e_AIRSYNC_BAD_FORMAT,
            e_AIRSYNC_BAD_VERSION,
            e_WBXML_NOT_SUPPORTED,
            e_WBXML_BAD_FORMAT,
            e_WBXML_BAD_VERSION,
            e_WBXML_TOO_COMPLEX,
            e_WBXML_BAD_CHARSET,
            e_WBXML_BAD_DOCID,
            e_WBXML_UNKNOWN_TOKEN,
            e_FAIL_BAD_REQUEST_NOSSL = -2063589337,
            e_AIRSYNC_UNSUPPORTED_VERSION,
            e_HTTP_UNKNOWN = -2063532032,
            e_HTTP_BAD_REQUEST,
            e_HTTP_DENIED,
            e_HTTP_PAYMENT_REQ,
            e_HTTP_FORBIDDEN,
            e_HTTP_NOT_FOUND,
            e_HTTP_BAD_METHOD,
            e_HTTP_NONE_ACCEPTABLE,
            e_HTTP_PROXY_AUTH_REQ,
            e_HTTP_REQUEST_TIMEOUT,
            e_HTTP_CONFLICT,
            e_HTTP_GONE,
            e_HTTP_LENGTH_REQUIRED,
            e_HTTP_PRECOND_FAILED,
            e_HTTP_REQUEST_TOO_LARGE,
            e_HTTP_URI_TOO_LONG,
            e_HTTP_UNSUPPORTED_MEDIA,
            e_HTTP_REQ_RANGE_NOT_SAT,
            e_HTTP_EXPECTATION_FAILED,
            e_HTTP_RETRY_WITH,
            e_HTTP_SERVER_ERROR,
            e_HTTP_NOT_SUPPORTED,
            e_HTTP_BAD_GATEWAY,
            e_HTTP_SERVICE_UNAVAIL,
            e_HTTP_GATEWAY_TIMEOUT,
            e_HTTP_VERSION_NOT_SUP,
            e_HTTP_DISK_SPACE,
            e_HTTP_INVALID_PROFILE,
            e_HTTP_EXCHANGE_PERMANENTREDIRECT,
            e_HTTP_UNEXPECTED_CONTENT,
            e_GOOGLE_APPS = -2063532000,
            sync_S_MUSTRESYNC = 263168,
            sync_S_MUSTRESYNCFOLDERS,
            e_NON_MSAS = -2063400926,
            e_SECUREID_NOTSUPPORTED = -2063400923,
            e_SYNC_PUSH_WAITFORPUSHENABLED_TIMEOUT = -2063400848,
            e_SYNC_PUSH_FAILED,
            e_SYNC_PUSH_NEEDS_RESTART,
            e_SYNC_CBA_FAILED,
            e_SYNC_IGNORABLE_SERVER_CERT_FAILURE,
            e_CREDENTIALS_UNAVAILABLE = -2063269886,
            e_AIRSYNC_RESET_RETRY = -2063269875,
            e_AIRSYNC_EMPTY_EMAIL,
            e_AIRSYNC_NO_SERVERID,
            e_NEXUS_SYNC_INVALID = -2046820093,
            s_NEXUS_SYNC_SUCCESS = 100663556,
            e_NEXUS_SYNC_PROTOCOL_VER = -2046820091,
            e_NEXUS_SYNC_SYNCKEY,
            e_NEXUS_SYNC_PROTOCOL,
            e_NEXUS_SYNC_SERVER,
            e_NEXUS_SYNC_CONVERSION,
            e_NEXUS_SYNC_CONFLICT,
            e_NEXUS_SYNC_OBJ_NOT_FOUND,
            e_NEXUS_SYNC_DISK_SPACE,
            e_NEXUS_SYNC_NOTIFY_GUID,
            e_NEXUS_SYNC_NOT_PROVISIONED,
            e_NEXUS_SYNC_FOLDERSYNC,
            e_NEXUS_SYNC_EMPTY_SYNC,
            e_NEXUS_SYNC_WAIT_OUT_OF_BOUNDS,
            e_NEXUS_SYNC_TOO_MANY_FOLDERS,
            e_NEXUS_SYNC_RETRY,
            e_NEXUS_SYNC_MAX,
            e_NEXUS_FOLDER_INVALID = -2046819840,
            s_NEXUS_FOLDER_SUCCESS = 100663809,
            e_NEXUS_FOLDER_ALREADY_EXISTS = -2046819838,
            e_NEXUS_FOLDER_SPECIAL_FOLDER,
            e_NEXUS_FOLDER_NOT_FOUND,
            e_NEXUS_FOLDER_PARENT_NOT_FOUND,
            e_NEXUS_FOLDER_DATA_SERVER,
            e_NEXUS_FOLDER_ACCESS_DENIED,
            e_NEXUS_FOLDER_TIME_OUT,
            e_NEXUS_FOLDER_SYNC_KEY,
            e_NEXUS_FOLDER_PROTOCOL,
            e_NEXUS_FOLDER_SYNC_SERVER,
            e_NEXUS_FOLDER_UNKNOWN,
            e_NEXUS_FOLDER_MAX,
            e_NEXUS_NOTIFY_INVALID = -2046819584,
            s_NEXUS_NOTIFY_SUCCESS = 100664065,
            e_NEXUS_NOTIFY_PROTOCOL = -2046819582,
            e_NEXUS_NOTIFY_FOLDER_BINDINGS,
            e_NEXUS_NOTIFY_DEVICE_FILE_ERROR,
            e_NEXUS_NOTIFY_BAD_PROFILE,
            e_NEXUS_NOTIFY_BINDING,
            e_NEXUS_NOTIFY_NOT_SUPPORTED,
            e_NEXUS_NOTIFY_SERVER,
            e_NEXUS_NOTIFY_DEVICE_FILE_LOCKED,
            e_NEXUS_NOTIFY_NOT_PROVISIONED,
            e_NEXUS_NOTIFY_MAX,
            e_NEXUS_MOVE_INVALID = -2046819328,
            e_NEXUS_MOVE_INVALID_SRC,
            e_NEXUS_MOVE_INVALID_DST,
            s_NEXUS_MOVE_SUCCESS = 100664323,
            e_NEXUS_MOVE_SAME_OBJECT = -2046819324,
            e_NEXUS_MOVE_MOVE_FAILURE,
            e_NEXUS_MOVE_COLLISION,
            e_NEXUS_MOVE_LOCKED,
            e_NEXUS_MOVE_MAX,
            e_NEXUS_ITEMESTIMATE_INVALID = -2046819072,
            s_NEXUS_ITEMESTIMATE_SUCCESS = 100664577,
            e_NEXUS_ITEMESTIMATE_PROTOCOL = -2046819070,
            e_NEXUS_ITEMESTIMATE_FOLDER_BINDINGS,
            e_NEXUS_ITEMESTIMATE_DEVICE_FILE_ERROR,
            e_NEXUS_ITEMESTIMATE_BAD_PROFILE,
            e_NEXUS_ITEMESTIMATE_BINDING,
            e_NEXUS_ITEMESTIMATE_NOT_SUPPORTED,
            e_NEXUS_ITEMESTIMATE_SERVER,
            e_NEXUS_ITEMESTIMATE_DEVICE_FILE_LOCKED,
            e_NEXUS_ITEMESTIMATE_NOT_PROVISIONED,
            e_NEXUS_ITEMESTIMATE_INVALID_COLLECTIONID,
            e_NEXUS_ITEMESTIMATE_INVALID_STATE,
            e_NEXUS_ITEMESTIMATE_INVALID_SYNCKEY,
            e_NEXUS_ITEMESTIMATE_MAX,
            e_NEXUS_MEETINGRESPONSE_INVALID = -2046818816,
            s_NEXUS_MEETINGRESPONSE_SUCCESS = 100664833,
            e_NEXUS_MEETINGRESPONSE_INVALID_MREQ = -2046818814,
            e_NEXUS_MEETINGRESPONSE_DATA_SERVER,
            e_NEXUS_MEETINGRESPONSE_SERVER,
            e_NEXUS_MEETINGRESPONSE_MAX,
            e_NEXUS_PING_INVALID = -2046818560,
            s_NEXUS_PING_NOCHANGES = 100665089,
            s_NEXUS_PING_CHANGES,
            e_NEXUS_PING_SENDPARAMS = -2046818557,
            e_NEXUS_PING_PROTOCOL,
            e_NEXUS_PING_HBI_OUT_OF_RANGE,
            e_NEXUS_PING_FOLDERS_OUT_OF_RANGE,
            e_NEXUS_PING_FOLDER_SYNC_REQUIRED,
            e_NEXUS_PING_SERVER,
            e_NEXUS_PING_MAX,
            e_NEXUS_PROVISION_INVALID = -2046818304,
            s_NEXUS_PROVISION_SUCCESS = 100665345,
            e_NEXUS_PROVISION_PROTOCOL = -2046818302,
            e_NEXUS_PROVISION_REMOTEWIPE_FAILED,
            e_NEXUS_PROVISION_SERVER,
            e_NEXUS_PROVISION_DATA_IGNORED,
            s_NEXUS_PROVISION_NO_POLICY = 100665350,
            e_NEXUS_PROVISION_UNKNOWN_TYPE = -2046818297,
            e_NEXUS_PROVISION_CORRUPTION,
            e_NEXUS_PROVISION_WRONG_KEY,
            e_NEXUS_PROVISION_MAX,
            e_NEXUS_SETTINGS_INVALID = -2046818045,
            s_NEXUS_SETTINGS_SUCCESS = 100665604,
            e_NEXUS_SETTINGS_PROTOCOL_ERROR = -2046818043,
            e_NEXUS_SETTINGS_ACCESS_DENIED,
            e_NEXUS_SETTINGS_SERVICE_UNAVAILABLE,
            e_NEXUS_SETTINGS_INVALID_ARG,
            e_NEXUS_SETTINGS_CONFLICTING_ARG,
            e_NEXUS_SETTINGS_DENIED_BY_POLICY,
            e_NEXUS_SETTINGS_MAX,
            e_NEXUS_ITEMOPERATIONS_INVALID = -2046817789,
            s_NEXUS_ITEMOPERATIONS_SUCCESS = 100665860,
            e_NEXUS_ITEMOPERATIONS_PROTOCOL = -2046817787,
            e_NEXUS_ITEMOPERATIONS_SERVER,
            e_NEXUS_ITEMOPERATIONS_BADLINK,
            e_NEXUS_ITEMOPERATIONS_ACCESSDENIED,
            e_NEXUS_ITEMOPERATIONS_NOTFOUND,
            e_NEXUS_ITEMOPERATIONS_CONNECTIONFAILED,
            e_NEXUS_ITEMOPERATIONS_OUTOFRANGE,
            e_NEXUS_ITEMOPERATIONS_UNKNOWNSTORE,
            e_NEXUS_ITEMOPERATIONS_FILEISEMPTY,
            e_NEXUS_ITEMOPERATIONS_DATATOOLARGE,
            e_NEXUS_ITEMOPERATIONS_IOFAILURE,
            e_NEXUS_ITEMOPERATIONS_INVALIDBODYPREFERENCE,
            e_NEXUS_ITEMOPERATIONS_CONVERSIONFAILURE,
            e_NEXUS_ITEMOPERATIONS_INVALIDATTACHMENTID,
            e_NEXUS_ITEMOPERATIONS_ACCESSBLOCKED,
            e_NEXUS_ITEMOPERATIONS_PARTIALSUCCESS,
            e_NEXUS_ITEMOPERATIONS_CREDENTIALSNEEDED,
            e_NEXUS_ITEMOPERATIONS_MAX,
            e_NEXUS_SEARCH_INVALID = -2046817533,
            s_NEXUS_SEARCH_SUCCESS = 100666116,
            e_NEXUS_SEARCH_PROTOCOL = -2046817531,
            e_NEXUS_SEARCH_SERVER,
            e_NEXUS_SEARCH_BADLINK,
            e_NEXUS_SEARCH_ACCESSDENIED,
            e_NEXUS_SEARCH_NOTFOUND,
            e_NEXUS_SEARCH_CONNECTIONFAILED,
            e_NEXUS_SEARCH_TOO_COMPLEX,
            e_NEXUS_SEARCH_INDEX_NOT_LOADED,
            e_NEXUS_SEARCH_TIMEOUT,
            e_NEXUS_SEARCH_NEED_TO_FOLDER_SYNC,
            s_NEXUS_SEARCH_ENDRETRIEVABLERANGE = 100666127,
            e_NEXUS_SEARCH_ACCESSBLOCKED = -2046817520,
            e_NEXUS_SEARCH_CREDENTIALSNEEDED,
            e_NEXUS_SEARCH_MAX,
            e_NEXUS_STATUS_INVALID_CONTENT = -2046817280,
            e_NEXUS_STATUS_INVALID_WBXML,
            e_NEXUS_STATUS_INVALID_XML,
            e_NEXUS_STATUS_INVALID_DATETIME,
            e_NEXUS_STATUS_INVALID_COMBINATIONOFIDS,
            e_NEXUS_STATUS_INVALID_IDS,
            e_NEXUS_STATUS_INVALID_MIME,
            e_NEXUS_STATUS_DEVICEID_MISSINGORINVALID,
            e_NEXUS_STATUS_DEVICETYPE_MISSINGORINVALID,
            e_NEXUS_STATUS_SERVERERROR,
            e_NEXUS_STATUS_SERVERERROR_RETRYLATER,
            e_NEXUS_STATUS_ACTIVEDIRECTORY_ACCESSDENIED,
            e_NEXUS_STATUS_MAILBOX_QUOTAEXCEEDED,
            e_NEXUS_STATUS_MAILBOX_SERVEROFFLINE,
            e_NEXUS_STATUS_MAILBOX_SENDQUOTAEXCEEDED,
            e_NEXUS_STATUS_MESSAGE_RECEIPIENTUNRESOLVED,
            e_NEXUS_STATUS_MESSAGE_REPLYNOTALLOWED,
            e_NEXUS_STATUS_MESSAGE_PREVIOUSLYSENT,
            e_NEXUS_STATUS_MESSAGE_HASNORECIPIENT,
            e_NEXUS_STATUS_MESSAGE_SUBMISSIONFAILED,
            e_NEXUS_STATUS_MESSAGE_REPLYFAILED,
            e_NEXUS_STATUS_MESSAGE_ATTACHMENTSTOOLARGE,
            e_NEXUS_STATUS_USER_HASNOMAILBOX,
            e_NEXUS_STATUS_USER_CANNOTBEANONYMOUS,
            e_NEXUS_STATUS_USER_PRINCIPALNOTFOUND,
            e_NEXUS_STATUS_USER_DISABLEDFORSYNC,
            e_NEXUS_STATUS_USER_ONNEW_MAILBOXCANNOTSYNC,
            e_NEXUS_STATUS_USER_ONLEGACY_MAILBOXCANNOTSYNC,
            e_NEXUS_STATUS_USER_DEVICEISBLOCKED,
            e_NEXUS_STATUS_ACCESSDENIED,
            e_NEXUS_STATUS_ACCOUNTDISABLED,
            e_NEXUS_STATUS_SYNCSTATE_NOTFOUND,
            e_NEXUS_STATUS_SYNCSTATE_LOCKED,
            e_NEXUS_STATUS_SYNCSTATE_CORRUPT,
            e_NEXUS_STATUS_SYNCSTATE_ALREADYEXISTS,
            e_NEXUS_STATUS_SYNCSTATE_VERSIONINVALID,
            e_NEXUS_STATUS_COMMAND_NOTSUPPORTED,
            e_NEXUS_STATUS_VERSION_NOTSUPPORTED,
            e_NEXUS_STATUS_DEVICE_NOTFULLYPROVISIONABLE,
            e_NEXUS_STATUS_DEVICE_REMOTEWIPEREQUESTED,
            e_NEXUS_STATUS_DEVICE_NOTPROVISIONABLE,
            e_NEXUS_STATUS_DEVICE_NOTPROVISIONED,
            e_NEXUS_STATUS_DEVICE_POLICYREFRESH,
            e_NEXUS_STATUS_INVALID_POLICYKEY,
            e_NEXUS_STATUS_EXTERNALLYMANAGED_DEVICESNOTALLOWED,
            e_NEXUS_STATUS_NORECURRENCE_INCALENDAR,
            e_NEXUS_STATUS_UNEXPECTED_ITEMCLASS,
            e_NEXUS_STATUS_REMOTESERVER_HASNOSSL,
            e_NEXUS_STATUS_INVALID_STOREREQUEST,
            e_NEXUS_STATUS_ITEM_NOTFOUND,
            e_NEXUS_STATUS_TOO_MANY_FOLDERS,
            e_NEXUS_STATUS_NO_FOLDERS_FOUND,
            e_NEXUS_STATUS_ITEMS_LOST_AFTER_MOVE,
            e_NEXUS_STATUS_FAILURE_IN_MOVEOPERATION,
            e_NEXUS_STATUS_UNSUPPORTED_CONVERSATION_ACTION,
            e_NEXUS_STATUS_UNSUPPORTED_CONVERSATION_ACTION_FOR_DESTINATION,
            e_NEXUS_STATUS_UM_FEATURE_DISABLED,
            e_NEXUS_STATUS_PHONE_NUMBER_REGISTRATION_FAILURE,
            e_NEXUS_STATUS_INVALID_MAILBOX_ID,
            e_NEXUS_STATUS_AVAILABILITY_REQUEST_TOO_MANY_RECIPIENTS,
            e_NEXUS_STATUS_AVAILABILITY_REQUEST_DL_TO_MANY_MEMBERS,
            e_NEXUS_STATUS_AVAILABILITY_TRANSIENT_FAILURE,
            e_NEXUS_STATUS_AVAILABILITY_FAILURE,
            e_NEXUS_STATUS_BODY_PART_PREFERENCE_TYPE_NOT_SUPPORTED,
            e_NEXUS_STATUS_DEVICE_INFORMATION_REQUIRED,
            e_NEXUS_STATUS_INVALID_ACCOUNT_ID,
            e_NEXUS_STATUS_ACCOUNT_SEND_DISABLED,
            e_NEXUS_STATUS_IRM_FEATURE_DISABLED,
            e_NEXUS_STATUS_IRM_TRANSIENT_ERROR,
            e_NEXUS_STATUS_IRM_PERMANENT_ERROR,
            e_NEXUS_STATUS_IRM_INVALID_TEMPLATE_ID,
            e_NEXUS_STATUS_IRM_OPERATION_NOT_PERMITTED,
            e_NEXUS_STATUS_NO_PICTURE,
            e_NEXUS_STATUS_PICTURE_TOO_LARGE,
            e_NEXUS_STATUS_PICTURE_LIMIT_REACHED,
            e_NEXUS_STATUS_BODY_PART_CONVERSATION_TOO_LARGE,
            e_NEXUS_STATUS_MAXIMUM_DEVICES_REACHED,
            e_NEXUS_APPLY_POLICY_NEEDED,
            e_NEXUS_UNABLE_TO_COMPLY_WITH_POLICY,
            e_NEXUS_BACK_OFF,
            e_SYNC_WINDOW_CHANGE_ABORT,
            e_NEXUS_STATUS_NO_UNSUBSCRIBE_INFORMATION,
            e_NEXUS_STATUS_MESSAGE_IS_INFECTED,
            e_NEXUS_STATUS_RULE_ALREADY_EXISTS,
            e_NEXUS_STATUS_RULE_CANNOT_BE_RUN,
            e_NEXUS_STATUS_INVALID_CATEGORY,
            e_NEXUS_RESOLVERECIPIENTS_INVALID = -2046817023,
            s_NEXUS_RESOLVERECIPIENTS_SUCCESS = 100666626,
            e_NEXUS_RESOLVERECIPIENTS_AMBIGUOUS = -2046817021,
            e_NEXUS_RESOLVERECIPIENTS_AMBIGUOUS_PARTIAL,
            e_NEXUS_RESOLVERECIPIENTS_NOMATCH,
            e_NEXUS_RESOLVERECIPIENTS_PROTOCOL,
            e_NEXUS_RESOLVERECIPIENTS_SERVER,
            e_NEXUS_RESOLVERECIPIENTS_NO_CERT,
            e_NEXUS_RESOLVERECIPIENTS_CERT_MAXED,
            e_NEXUS_RESOLVERECIPIENTS_DL_ERROR,
            e_NEXUS_RESOLVERECIPIENTS_MAX,
            e_NEXUS_USER_CANCELLED_POLICY = -2147023673,
            ixp_E_ALREADY_CONNECTED = -2030042879,
            ixp_E_INCOMPLETE = -2030042877,
            ixp_E_IMAP_CONNECTION_REFUSED = -2030042871,
            ixp_E_IMAP_TAGGED_NO_RESPONSE = -2030042864,
            ixp_E_IMAP_BAD_RESPONSE,
            ixp_E_IMAP_LOGINFAILURE,
            ixp_E_IMAP_UNSOLICITED_BYE,
            ixp_E_IMAP_RECVR_ERROR,
            ixp_E_IMAP_UNRECOGNIZED_RESP,
            ixp_E_IMAP_SVR_SYNTAXERR,
            ixp_E_IMAP_BUFFER_OVERFLOW = -2030042856,
            ixp_E_IMAP_IMPROPER_SVRSTATE,
            ixp_E_IMAP_CHANGEDUID = -2030042848,
            ixp_E_IMAP_UIDORDER,
            mime_E_INVALID_INET_DATE = -2030042845,
            ixp_E_SMTP_RESPONSE_ERROR = -2030042795,
            ixp_E_SMTP_UNKNOWN_RESPONSE_CODE,
            ixp_E_SMTP_REJECTED_RECIPIENTS,
            ixp_E_SMTP_NO_SENDER,
            ixp_E_SMTP_NO_RECIPIENTS,
            ixp_E_SMTP_REJECTED_SENDER = -2030042784,
            ixp_E_SMTP_500_SYNTAX_ERROR,
            ixp_E_SMTP_501_PARAM_SYNTAX,
            ixp_E_SMTP_502_COMMAND_NOTIMPL,
            ixp_E_SMTP_503_COMMAND_SEQ,
            ixp_E_SMTP_504_COMMAND_PARAM_NOTIMPL,
            ixp_E_SMTP_421_NOT_AVAILABLE,
            ixp_E_SMTP_450_MAILBOX_BUSY,
            ixp_E_SMTP_550_MAILBOX_NOT_FOUND,
            ixp_E_SMTP_451_ERROR_PROCESSING,
            ixp_E_SMTP_551_USER_NOT_LOCAL = -2030042768,
            ixp_E_SMTP_452_NO_SYSTEM_STORAGE,
            ixp_E_SMTP_552_STORAGE_OVERFLOW,
            ixp_E_SMTP_553_MAILBOX_NAME_SYNTAX,
            ixp_E_SMTP_554_TRANSACT_FAILED,
            ixp_E_SMTP_530_STARTTLS_REQUIRED,
            ixp_E_SMTP_NO_STARTTLS_SUPPORT,
            ixp_S_SMTP_NO_DSN_SUPPORT,
            ixp_E_SMTP_535_AUTH_FAILED,
            ixp_E_SMTP_454_STARTTLS_FAILED,
            ixp_E_IMAP_BODY_TOO_DEEP = -2030042752,
        }
        export enum SanitizedVersion {
            notSanitized,
            w6RTM,
            current = 1,
            noHtmlBody = 100,
            locallyCreatedMessage,
        }
        export enum ScenarioState {
            none,
            unknown,
            connected,
            upgradeRequired,
            error,
            connectedButDisabled,
            connectable,
            dismissed,
            connectableButOverridden,
            terminated,
        }
        export enum SearchStatusCode {
            invalid,
            success,
            timeOut,
            serverError,
            folderSyncRequired,
            endOfRetrievableRange,
        }
        export enum ServerScenario {
            none,
            chat,
            client_calendar,
            client_contacts,
            client_mail,
            client_mail_imap,
            contacts,
            dashboard_agg,
            media_agg,
            status_publish,
        }
        export enum ServerType {
            eas,
            imap,
            pop,
            smtp,
        }
        export enum ServicePartnerApplicationState {
            notSupported,
            active,
            terminated,
            expiring,
            updated,
        }
        export enum SignatureType {
            enabled = 2,
            disabled,
        }
        export enum SyncType {
            manual,
            poll,
            push,
        }
        export enum SyncWindowSize {
            all,
            oneDay,
            threeDays,
            oneWeek,
            twoWeeks,
            oneMonth,
            threeMonths,
            sixMonths,
        }
        export enum TileIdType {
            sourceObjectId,
            easTileId,
            me,
            roamingEasTileId,
            roamingMailViewId,
            localMailViewId,
            localContactId,
        }
        export enum ToastState {
            favoritesOnly,
            all,
            none,
        }
        export enum UserTileSize {
            invalid = -1,
            tiny,
            extraSmall,
            small,
            medium,
            large,
            extraLarge,
            original,
        }
        export enum VerbType {
            photo,
            privateMessage,
            profile,
            reportAbuse,
        }
    }
}
