// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { IVector } from "../../Foundation/Collections/IVector`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { RevocationAndRenewalItem } from "./RevocationAndRenewalItem";

@GenerateShim('Windows.Media.Protection.RevocationAndRenewalInformation')
export class RevocationAndRenewalInformation { 
    items: IVector<RevocationAndRenewalItem> = null;
}
