// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { AsyncActionProgressHandler } from "./AsyncActionProgressHandler`1";
import { AsyncActionWithProgressCompletedHandler } from "./AsyncActionWithProgressCompletedHandler`1";
import { IAsyncInfo } from "./IAsyncInfo";
export * from "./Interop/AsyncActionWithProgress`1"

export interface IAsyncActionWithProgress<TProgress> extends IAsyncInfo {
    progress: AsyncActionProgressHandler<TProgress>;
    completed: AsyncActionWithProgressCompletedHandler<TProgress>;
    getResults(): void;
}