// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:01 2021
// </auto-generated>
// --------------------------------------------------

import { SearchPaneSuggestionsRequestDeferral } from "./SearchPaneSuggestionsRequestDeferral";
import { SearchSuggestionCollection } from "./SearchSuggestionCollection";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.ApplicationModel.Search.SearchPaneSuggestionsRequest')
export class SearchPaneSuggestionsRequest { 
    isCanceled: boolean = null;
    searchSuggestionCollection: SearchSuggestionCollection = null;
    getDeferral(): SearchPaneSuggestionsRequestDeferral {
        throw new Error('SearchPaneSuggestionsRequest#getDeferral not implemented')
    }
}
