// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:01 2021
// </auto-generated>
// --------------------------------------------------

import { BluetoothCacheMode } from "../BluetoothCacheMode";
import { GattCommunicationStatus } from "./GattCommunicationStatus";
import { GattProtectionLevel } from "./GattProtectionLevel";
import { GattReadResult } from "./GattReadResult";
import { IAsyncOperation } from "../../../Foundation/IAsyncOperation`1";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";
import { IBuffer } from "../../../Storage/Streams/IBuffer";

@GenerateShim('Windows.Devices.Bluetooth.GenericAttributeProfile.GattDescriptor')
export class GattDescriptor { 
    protectionLevel: GattProtectionLevel = null;
    attributeHandle: number = null;
    uuid: string = null;
    readValueAsync(): IAsyncOperation<GattReadResult> {
        throw new Error('GattDescriptor#readValueAsync not implemented')
    }
    readValueWithCacheModeAsync(cacheMode: BluetoothCacheMode): IAsyncOperation<GattReadResult> {
        throw new Error('GattDescriptor#readValueWithCacheModeAsync not implemented')
    }
    writeValueAsync(value: IBuffer): IAsyncOperation<GattCommunicationStatus> {
        throw new Error('GattDescriptor#writeValueAsync not implemented')
    }
    static convertShortIdToUuid(shortId: number): string {
        throw new Error('GattDescriptor#convertShortIdToUuid not implemented')
    }
}
