// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:01 2021
// </auto-generated>
// --------------------------------------------------

import { GattCharacteristic } from "./GattCharacteristic";
import { IVectorView } from "../../../Foundation/Collections/IVectorView`1";
import { IAsyncOperation } from "../../../Foundation/IAsyncOperation`1";
import { IClosable } from "../../../Foundation/IClosable";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Devices.Bluetooth.GenericAttributeProfile.GattDeviceService')
export class GattDeviceService implements IClosable { 
    attributeHandle: number = null;
    deviceId: string = null;
    uuid: string = null;
    getCharacteristics(characteristicUuid: string): IVectorView<GattCharacteristic> {
        throw new Error('GattDeviceService#getCharacteristics not implemented')
    }
    getIncludedServices(serviceUuid: string): IVectorView<GattDeviceService> {
        throw new Error('GattDeviceService#getIncludedServices not implemented')
    }
    close(): void {
        console.warn('GattDeviceService#close not implemented')
    }
    static fromIdAsync(deviceId: string): IAsyncOperation<GattDeviceService> {
        throw new Error('GattDeviceService#fromIdAsync not implemented')
    }
    static getDeviceSelectorFromUuid(serviceUuid: string): string {
        throw new Error('GattDeviceService#getDeviceSelectorFromUuid not implemented')
    }
    static getDeviceSelectorFromShortId(serviceShortId: number): string {
        throw new Error('GattDeviceService#getDeviceSelectorFromShortId not implemented')
    }
    static convertShortIdToUuid(shortId: number): string {
        throw new Error('GattDeviceService#convertShortIdToUuid not implemented')
    }
}
