// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IHttpQueryEngine } from "./IHttpQueryEngine";
import { IHttpQueryResponse } from "./IHttpQueryResponse";
import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Common.Service.HttpQueryEngine')
export class HttpQueryEngine implements IHttpQueryEngine { 
    // constructor();
    // constructor(pHttpQueryImpl: any);
    constructor(...args) { }
    sendAsync(): IAsyncOperation<IHttpQueryResponse> {
        throw new Error('HttpQueryEngine#sendAsync not implemented')
    }
}
