// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:37 2021
// </auto-generated>
// --------------------------------------------------

export enum AppId {
    chat,
    call,
    mail,
    calendar,
    people,
    photo,
    skydrive,
    testapp1,
    testapp2,
    testapp3,
    max,
}
