// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

export enum FoldersSortBy {
    none = 11100,
    dateAddedDescending = 11101,
    titleAscending = 11102,
    dateModifiedDescending = 11103,
}
