// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { IQueryChangedEventArgs } from "./IQueryChangedEventArgs";
import { IQueryPage } from "./IQueryPage";
import { IQueryResult } from "./IQueryResult";
import { EventHandler } from "winrt/Windows/Foundation/EventHandler`1";
import { IAsyncAction } from "winrt/Windows/Foundation/IAsyncAction";
import { IAsyncOperationWithProgress } from "winrt/Windows/Foundation/IAsyncOperationWithProgress`2";
import { IClosable } from "winrt/Windows/Foundation/IClosable";

export interface IQuery extends IClosable {
    currentPage: IQueryPage;
    nextPage: IQueryPage;
    previousPage: IQueryPage;
    execute(): IAsyncOperationWithProgress<IQueryResult, number>;
    pauseAsync(): IAsyncAction;
    resumeAsync(): IAsyncAction;
    onquerychanged: EventHandler<IQueryChangedEventArgs>;
    addEventListener(name: string, handler: any)
    removeEventListener(name: string, handler: any)
}
