// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

export enum ItemCollectionState {
    notInCollection = 1300,
    notInCollectionNoRights = 1301,
    notInCollectionTakenDown = 1302,
    notInCollectionValidRights = 1303,
    cloudOnlyNoRights = 1304,
    cloudOnlyTakenDown = 1305,
    cloudOnlyValidRights = 1306,
    oneDriveOnly = 1307,
    cloudOnlyPendingSync = 1308,
    cloudAndLocalNoRights = 1309,
    cloudAndLocalTakenDown = 1310,
    cloudAndLocalValidRights = 1311,
    oneDriveAndLocal = 1312,
    localOnly = 1313,
    localOnlyNoCatalogId = 1314,
    localOnlyPendingSync = 1315,
}
