// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { MediaAvailability } from "../Platform/MediaAvailability";
import { PlaylistType } from "../Platform/PlaylistType";
import { IPlaylistsQuery } from "./IPlaylistsQuery";
import { IQuery } from "./IQuery";
import { IQueryChangedEventArgs } from "./IQueryChangedEventArgs";
import { IQueryPage } from "./IQueryPage";
import { IQueryResult } from "./IQueryResult";
import { PlaylistsQueryCountOperation } from "./PlaylistsQueryCountOperation";
import { PlaylistsSortBy } from "./PlaylistsSortBy";
import { IIterable } from "winrt/Windows/Foundation/Collections/IIterable`1";
import { EventHandler } from "winrt/Windows/Foundation/EventHandler`1";
import { IAsyncAction } from "winrt/Windows/Foundation/IAsyncAction";
import { AsyncOperationWithProgress, IAsyncOperationWithProgress } from "winrt/Windows/Foundation/IAsyncOperationWithProgress`2";
import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";
import { IClosable } from "winrt/Windows/Foundation/IClosable";
import { Enumerable } from "winrt/Windows/Foundation/Interop/Enumerable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Queries.PlaylistsQuery')
export class PlaylistsQuery implements IPlaylistsQuery, IQuery, IClosable { 
    watchAll: number = null;
    title: string = null;
    primarySortBy: PlaylistsSortBy = null;
    playlistType: PlaylistType = null;
    playlistId: number = null;
    pageSize: number = null;
    mediaAvailability: MediaAvailability = null;
    keyword: IIterable<string> = null;
    groupsEnabled: number = null;
    cloudSyncItemId: string = null;
    currentPage: IQueryPage = null;
    nextPage: IQueryPage = null;
    previousPage: IQueryPage = null;
    executeAsync(): IAsyncOperationWithProgress<IQueryResult, number> {
        return AsyncOperationWithProgress.from(async () => { return { json: "[]" }; })
    }
    getCountAsync(): PlaylistsQueryCountOperation {
        throw new Error('PlaylistsQuery#getCountAsync not implemented')
    }
    setCursorPosition(index: number): void {
        console.warn('PlaylistsQuery#setCursorPosition not implemented')
    }
    getGroupsAsync(): IAsyncOperationWithProgress<IQueryResult, number> {
        throw new Error('PlaylistsQuery#getGroupsAsync not implemented')
    }
    refreshAsync(): IAsyncAction {
        throw new Error('PlaylistsQuery#refreshAsync not implemented')
    }
    getItemIndexAsync(objectId: number): IAsyncOperation<number> {
        throw new Error('PlaylistsQuery#getItemIndexAsync not implemented')
    }
    execute(): IAsyncOperationWithProgress<IQueryResult, number> {
        throw new Error('PlaylistsQuery#execute not implemented')
    }
    pauseAsync(): IAsyncAction {
        throw new Error('PlaylistsQuery#pauseAsync not implemented')
    }
    resumeAsync(): IAsyncAction {
        throw new Error('PlaylistsQuery#resumeAsync not implemented')
    }
    close(): void {
        console.warn('PlaylistsQuery#close not implemented')
    }

    private __queryChanged: Set<EventHandler<IQueryChangedEventArgs>> = new Set();
    @Enumerable(true)
    set onquerychanged(handler: EventHandler<IQueryChangedEventArgs>) {
        this.__queryChanged.add(handler);
    }

    addEventListener(name: string, handler: any) {
        switch (name) {
            case 'querychanged':
                this.__queryChanged.add(handler);
                break;
        }
    }

    removeEventListener(name: string, handler: any) {
        switch (name) {
            case 'querychanged':
                this.__queryChanged.delete(handler);
                break;
        }
    }
}
