// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { IQueryResult } from "./IQueryResult";
import { IVideoStudioDataset } from "./IVideoStudioDataset";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Queries.VideoStudioDataset')
export class VideoStudioDataset implements IVideoStudioDataset, IQueryResult { 
    json: string = null;
}
