// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:07 2021
// </auto-generated>
// --------------------------------------------------

export enum CachedFileOptions {
    none = 0,
    requireUpdateOnAccess = 1,
    useCachedFileWhenOffline = 2,
    denyAccessWhenOffline = 4,
}
