// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { ICollectionBuildEndEventHandlerArgs } from "./ICollectionBuildEndEventHandlerArgs";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Platform.CollectionBuildEndEventHandlerArgs')
export class CollectionBuildEndEventHandlerArgs implements ICollectionBuildEndEventHandlerArgs { 
    error: number = null;
    itemsCollected: number = null;
    itemsTotal: number = null;
    source: number = null;
}
