// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { CanAddToWatchlistReturnValue } from "./CanAddToWatchlistReturnValue";
import { IsInWatchlistReturnValue } from "./IsInWatchlistReturnValue";
import { WatchlistItemType } from "./WatchlistItemType";
import { IAsyncAction } from "winrt/Windows/Foundation/IAsyncAction";
import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";

export interface IWatchlistProvider {
    addToWatchlistAsync(watchlistId: number, serviceMediaId: string, itemType: WatchlistItemType): IAsyncAction;
    removeFromWatchlistAsync(watchlistId: number, serviceMediaId: string, itemType: WatchlistItemType): IAsyncAction;
    isInWatchlistAsync(watchlistId: number, serviceMediaId: string): IAsyncOperation<IsInWatchlistReturnValue>;
    canAddToWatchlistAsync(watchlistId: number, serviceMediaId: string): IAsyncOperation<CanAddToWatchlistReturnValue>;
    trimWatchlistAsync(watchlistId: number): IAsyncAction;
}
