// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:37 2021
// </auto-generated>
// --------------------------------------------------

import { ApplicationId } from "./ApplicationId";
import { IApp } from "./IApp";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.WindowsLive.Config.Shared.App')
export class App implements IApp { 
    readonly currentVersion: string = null;
    readonly id: ApplicationId = null;
    readonly message: string = null;
    readonly minVersion: string = null;
    readonly moreInfoUrl: string = null;
}
