// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:37 2021
// </auto-generated>
// --------------------------------------------------

import { AppId } from "./AppId";
import { IApplication } from "./IApplication";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.WindowsLive.Config.Shared.Application')
export class Application implements IApplication { 
    readonly addAppBarButton: boolean = null;
    readonly addSettingsLink: boolean = null;
    readonly enableLogCollection: boolean = null;
    readonly helpFlyoutUrl: string = null;
    readonly id: AppId = null;
    readonly surveyId: number = null;
}
