// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { IMapView } from "../../Foundation/Collections/IMapView`2";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { Uri } from "../../Foundation/Uri";

@GenerateShim('Windows.Networking.BackgroundTransfer.ResponseInformation')
export class ResponseInformation { 
    actualUri: Uri = null;
    headers: IMapView<string, string> = null;
    isResumable: boolean = null;
    statusCode: number = null;
}
