// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { IIterable } from "../../Foundation/Collections/IIterable`1";
import { IIterator } from "../../Foundation/Collections/IIterator`1";
import { IVectorView } from "../../Foundation/Collections/IVectorView`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { ReadOnlyVector } from "../../Foundation/Interop/ReadOnlyVector`1";
import { CharacterGrouping } from "./CharacterGrouping";

@GenerateShim('Windows.Globalization.Collation.CharacterGroupings')
export class CharacterGroupings extends ReadOnlyVector<CharacterGrouping> { 
    constructor() {
        let groupings = [];
        let str = "abcdefghijklmnopqrstuvwxyz";
        for (var i = 0; i < str.length; i++) {
            groupings.push(new CharacterGrouping(str.charAt(i)));
        }

        super(groupings);
    }
}
