// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IMediaDetail } from "./IMediaDetail";
import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";
import { IRandomAccessStream } from "winrt/Windows/Storage/Streams/IRandomAccessStream";

export interface IMediaInfo {
    getMediaDetail(mediaStream: IRandomAccessStream): IAsyncOperation<IMediaDetail>;
}
