// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { IVector } from "../../Foundation/Collections/IVector`1";
import { PasswordCredential } from "../../Security/Credentials/PasswordCredential";

export interface IWebSocketControl {
    outboundBufferSizeInBytes: number;
    proxyCredential: PasswordCredential;
    serverCredential: PasswordCredential;
    supportedProtocols: IVector<string>;
}
