// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { WebErrorStatus } from "../../Web/WebErrorStatus";

@GenerateShim('Windows.Networking.Sockets.WebSocketError')
export class WebSocketError { 
    static getStatus(hresult: number): WebErrorStatus {
        throw new Error('WebSocketError#getStatus not implemented')
    }
}
