// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:22:59 2021
// </auto-generated>
// --------------------------------------------------

import { ActivationKind } from "./ActivationKind";
import { ApplicationExecutionState } from "./ApplicationExecutionState";
import { IActivatedEventArgs } from "./IActivatedEventArgs";
import { IContactPickerActivatedEventArgs } from "./IContactPickerActivatedEventArgs";
import { SplashScreen } from "./SplashScreen";
import { ContactPickerUI } from "../Contacts/Provider/ContactPickerUI";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.ApplicationModel.Activation.ContactPickerActivatedEventArgs')
export class ContactPickerActivatedEventArgs implements IContactPickerActivatedEventArgs, IActivatedEventArgs { 
    contactPickerUI: ContactPickerUI = null;
    kind: ActivationKind = null;
    previousExecutionState: ApplicationExecutionState = null;
    splashScreen: SplashScreen = null;
}
