// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:22:59 2021
// </auto-generated>
// --------------------------------------------------

import { ActivationKind } from "./ActivationKind";
import { ApplicationExecutionState } from "./ApplicationExecutionState";
import { IActivatedEventArgs } from "./IActivatedEventArgs";
import { IFileOpenPickerActivatedEventArgs } from "./IFileOpenPickerActivatedEventArgs";
import { SplashScreen } from "./SplashScreen";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { FileOpenPickerUI } from "../../Storage/Pickers/Provider/FileOpenPickerUI";

@GenerateShim('Windows.ApplicationModel.Activation.FileOpenPickerActivatedEventArgs')
export class FileOpenPickerActivatedEventArgs implements IFileOpenPickerActivatedEventArgs, IActivatedEventArgs { 
    fileOpenPickerUI: FileOpenPickerUI = null;
    kind: ActivationKind = null;
    previousExecutionState: ApplicationExecutionState = null;
    splashScreen: SplashScreen = null;
}
