// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:22:59 2021
// </auto-generated>
// --------------------------------------------------

import { ActivationKind } from "./ActivationKind";
import { ApplicationExecutionState } from "./ApplicationExecutionState";
import { IActivatedEventArgs } from "./IActivatedEventArgs";
import { IRestrictedLaunchActivatedEventArgs } from "./IRestrictedLaunchActivatedEventArgs";
import { SplashScreen } from "./SplashScreen";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.ApplicationModel.Activation.RestrictedLaunchActivatedEventArgs')
export class RestrictedLaunchActivatedEventArgs implements IRestrictedLaunchActivatedEventArgs, IActivatedEventArgs { 
    sharedContext: any = null;
    kind: ActivationKind = null;
    previousExecutionState: ApplicationExecutionState = null;
    splashScreen: SplashScreen = null;
}
