// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:04 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Graphics.Printing.StandardPrintTaskOptions')
export class StandardPrintTaskOptions { 
    static binding: string = null;
    static collation: string = null;
    static colorMode: string = null;
    static copies: string = null;
    static duplex: string = null;
    static holePunch: string = null;
    static inputBin: string = null;
    static mediaSize: string = null;
    static mediaType: string = null;
    static nup: string = null;
    static orientation: string = null;
    static printQuality: string = null;
    static staple: string = null;
}
