// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:06 2021
// </auto-generated>
// --------------------------------------------------

import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('AppEx.Common.ArticleReader.DateFormatter')
export class DateFormatter implements IStringable { 
    static formatDate(utctime: number): string {
        throw new Error('DateFormatter#formatDate not implemented')
    }
    toString(): string {
        throw new Error('DateFormatter#toString not implemented')
    }
}
