// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:22:59 2021
// </auto-generated>
// --------------------------------------------------

export enum AppointmentDaysOfWeek {
    none = 0,
    sunday = 1,
    monday = 2,
    tuesday = 4,
    wednesday = 8,
    thursday = 16,
    friday = 32,
    saturday = 64,
}
