// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:01 2021
// </auto-generated>
// --------------------------------------------------

import { SelectableWordSegment } from "./SelectableWordSegment";
import { IIterable } from "../../Foundation/Collections/IIterable`1";

export type SelectableWordSegmentsTokenizingHandler = (words: IIterable<SelectableWordSegment>) => void;
