// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:22:59 2021
// </auto-generated>
// --------------------------------------------------

import { BackgroundWorkCostValue } from "./BackgroundWorkCostValue";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.ApplicationModel.Background.BackgroundWorkCost')
export class BackgroundWorkCost { 
    static currentBackgroundWorkCost: BackgroundWorkCostValue = null;
}
