// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:22:59 2021
// </auto-generated>
// --------------------------------------------------

import { BackgroundTaskCanceledEventHandler } from "./BackgroundTaskCanceledEventHandler";
import { BackgroundTaskDeferral } from "./BackgroundTaskDeferral";
import { BackgroundTaskRegistration } from "./BackgroundTaskRegistration";

export interface IBackgroundTaskInstance {
    instanceId: string;
    progress: number;
    suspendedCount: number;
    task: BackgroundTaskRegistration;
    triggerDetails: any;
    getDeferral(): BackgroundTaskDeferral;
    oncanceled: BackgroundTaskCanceledEventHandler;
    addEventListener(name: string, handler: any)
    removeEventListener(name: string, handler: any)
}
