// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { IIterable } from "./IIterable`1";
import { IKeyValuePair } from "./IKeyValuePair`2";
import { IMapView } from "./IMapView`2";

export interface IMap<K, V> extends IIterable<IKeyValuePair<K, V>> {
    size: number;
    lookup(key: K): V;
    hasKey(key: K): boolean;
    getView(): IMapView<K, V>;
    insert(key: K, value: V): boolean;
    remove(key: K): void;
    clear(): void;
}
