// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { IIterable } from "./IIterable`1";
import { IKeyValuePair } from "./IKeyValuePair`2";
import { IMap } from "./IMap`2";
import { IObservableMap } from "./IObservableMap`2";

export interface IPropertySet extends IObservableMap<string, any>, IMap<string, any>, IIterable<IKeyValuePair<string, any>> {
}
