// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------


export interface IShareEvent {
    setMediaName(value: string): IShareEvent;
    setMediaType(value: string): IShareEvent;
    setFromAppId(value: string): IShareEvent;
    setToAppId(value: string): IShareEvent;
    setPage(value: string): IShareEvent;
    send(): void;
}
