// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:10 2021
// </auto-generated>
// --------------------------------------------------

import { IJSONWrapper } from "../IJSONWrapper";
import { IMap } from "winrt/Windows/Foundation/Collections/IMap`2";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('MicrosoftAdvertising.Shared.WinRT.RendererOptions')
export class RendererOptions implements IStringable { 
    // constructor();
    // constructor(jsonWrapper: IJSONWrapper);
    constructor(...args) { }
    addRendererOption(optionName: string, optionValue: string): void {
        console.warn('RendererOptions#addRendererOption not implemented')
    }
    getOptions(): IMap<string, string> {
        throw new Error('RendererOptions#getOptions not implemented')
    }
    getOptionsJson(): string {
        throw new Error('RendererOptions#getOptionsJson not implemented')
    }
    removeRendererOption(optionName: string): void {
        console.warn('RendererOptions#removeRendererOption not implemented')
    }
    toString(): string {
        throw new Error('RendererOptions#toString not implemented')
    }
}
