// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { IVector } from "../../../Foundation/Collections/IVector`1";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Security.Cryptography.Certificates.CertificateQuery')
export class CertificateQuery { 
    thumbprint: number[] = null;
    issuerName: string = null;
    hardwareOnly: boolean = null;
    friendlyName: string = null;
    enhancedKeyUsages: IVector<string> = null;
}
