// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:08 2021
// </auto-generated>
// --------------------------------------------------

import { DateTime } from "../../Foundation/DateTime";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { Uri } from "../../Foundation/Uri";
import { BadgeNotification } from "./BadgeNotification";
import { PeriodicUpdateRecurrence } from "./PeriodicUpdateRecurrence";

@GenerateShim('Windows.UI.Notifications.BadgeUpdater')
export class BadgeUpdater { 
    update(notification: BadgeNotification): void {
        console.warn('BadgeUpdater#update not implemented')
    }
    clear(): void {
        console.warn('BadgeUpdater#clear not implemented')
    }
    startPeriodicUpdate(badgeContent: Uri, requestedInterval: PeriodicUpdateRecurrence): void {
        console.warn('BadgeUpdater#startPeriodicUpdate not implemented')
    }
    startPeriodicUpdateAtTime(badgeContent: Uri, startTime: Date, requestedInterval: PeriodicUpdateRecurrence): void {
        console.warn('BadgeUpdater#startPeriodicUpdateAtTime not implemented')
    }
    stopPeriodicUpdate(): void {
        console.warn('BadgeUpdater#stopPeriodicUpdate not implemented')
    }
}
