// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:04 2021
// </auto-generated>
// --------------------------------------------------

import { IVectorView } from "../../../Foundation/Collections/IVectorView`1";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";
import { IPrintItemListOptionDetails } from "./IPrintItemListOptionDetails";
import { IPrintOptionDetails } from "./IPrintOptionDetails";
import { PrintOptionStates } from "./PrintOptionStates";
import { PrintOptionType } from "./PrintOptionType";

@GenerateShim('Windows.Graphics.Printing.OptionDetails.PrintQualityOptionDetails')
export class PrintQualityOptionDetails implements IPrintOptionDetails, IPrintItemListOptionDetails { 
    state: PrintOptionStates = null;
    errorText: string = null;
    optionId: string = null;
    optionType: PrintOptionType = null;
    value: any = null;
    items: IVectorView<any> = null;
    trySetValue(value: any): boolean {
        throw new Error('PrintQualityOptionDetails#trySetValue not implemented')
    }
}
