// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

export enum AppMode {
    music,
    music2,
    music3,
    video,
    video2,
    video3,
    test,
    amsterdam,
}
