// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:04 2021
// </auto-generated>
// --------------------------------------------------

import { IAsyncAction } from "../../Foundation/IAsyncAction";
import { IAsyncOperation } from "../../Foundation/IAsyncOperation`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { CapturedPhoto } from "./CapturedPhoto";

@GenerateShim('Windows.Media.Capture.LowLagPhotoCapture')
export class LowLagPhotoCapture { 
    captureAsync(): IAsyncOperation<CapturedPhoto> {
        throw new Error('LowLagPhotoCapture#captureAsync not implemented')
    }
    finishAsync(): IAsyncAction {
        throw new Error('LowLagPhotoCapture#finishAsync not implemented')
    }
}
