// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:01 2021
// </auto-generated>
// --------------------------------------------------

import { IXmlNode } from "./IXmlNode";
import { IXmlNodeSelector } from "./IXmlNodeSelector";
import { IXmlNodeSerializer } from "./IXmlNodeSerializer";
import { NodeType } from "./NodeType";
import { XmlDocument } from "./XmlDocument";
import { XmlNamedNodeMap } from "./XmlNamedNodeMap";
import { XmlNodeList } from "./XmlNodeList";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Data.Xml.Dom.DtdNotation')
export class DtdNotation implements IXmlNode, IXmlNodeSerializer, IXmlNodeSelector { 
    __domNode: Node;
    publicId: any = null;
    systemId: any = null;
    prefix: any = null;
    nodeValue: any = null;
    firstChild: IXmlNode = null;
    lastChild: IXmlNode = null;
    localName: any = null;
    namespaceUri: any = null;
    nextSibling: IXmlNode = null;
    nodeName: string = null;
    nodeType: NodeType = null;
    attributes: XmlNamedNodeMap = null;
    ownerDocument: XmlDocument = null;
    parentNode: IXmlNode = null;
    childNodes: XmlNodeList = null;
    previousSibling: IXmlNode = null;
    innerText: string = null;
    hasChildNodes(): boolean {
        throw new Error('DtdNotation#hasChildNodes not implemented')
    }
    insertBefore(newChild: IXmlNode, referenceChild: IXmlNode): IXmlNode {
        throw new Error('DtdNotation#insertBefore not implemented')
    }
    replaceChild(newChild: IXmlNode, referenceChild: IXmlNode): IXmlNode {
        throw new Error('DtdNotation#replaceChild not implemented')
    }
    removeChild(childNode: IXmlNode): IXmlNode {
        throw new Error('DtdNotation#removeChild not implemented')
    }
    appendChild(newChild: IXmlNode): IXmlNode {
        throw new Error('DtdNotation#appendChild not implemented')
    }
    cloneNode(deep: boolean): IXmlNode {
        throw new Error('DtdNotation#cloneNode not implemented')
    }
    normalize(): void {
        console.warn('DtdNotation#normalize not implemented')
    }
    selectSingleNode(xpath: string): IXmlNode {
        throw new Error('DtdNotation#selectSingleNode not implemented')
    }
    selectNodes(xpath: string): XmlNodeList {
        throw new Error('DtdNotation#selectNodes not implemented')
    }
    selectSingleNodeNS(xpath: string, namespaces: any): IXmlNode {
        throw new Error('DtdNotation#selectSingleNodeNS not implemented')
    }
    selectNodesNS(xpath: string, namespaces: any): XmlNodeList {
        throw new Error('DtdNotation#selectNodesNS not implemented')
    }
    getXml(): string {
        throw new Error('DtdNotation#getXml not implemented')
    }
}
