// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:01 2021
// </auto-generated>
// --------------------------------------------------

import { IXmlNode } from "./IXmlNode";
import { IIterable } from "../../../Foundation/Collections/IIterable`1";
import { IIterator } from "../../../Foundation/Collections/IIterator`1";
import { IVectorView } from "../../../Foundation/Collections/IVectorView`1";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";
import { Vector } from "../../../Foundation/Interop/Vector`1";

@GenerateShim('Windows.Data.Xml.Dom.XmlNodeList')
export class XmlNodeList extends Vector<IXmlNode> { }
