// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:39 2021
// </auto-generated>
// --------------------------------------------------

import { ErrorPriority } from "./ErrorPriority";
import { ErrorType } from "./ErrorType";
import { IObject } from "../IObject";

export interface IErrorMessage extends IObject {
    readonly eventHandle: string;
    readonly message: string;
    readonly priority: ErrorPriority;
    readonly type: ErrorType;
}
