// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { MappedError } from "./MappedError";

export interface IErrorMapper {
    getMappedError(hrError: number): MappedError;
}
