// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:37 2021
// </auto-generated>
// --------------------------------------------------

import { ExifOrientation } from "./ExifOrientation";
import { AsyncOperationCompletedHandler } from "winrt/Windows/Foundation/AsyncOperationCompletedHandler`1";
import { AsyncStatus } from "winrt/Windows/Foundation/AsyncStatus";
import { IAsyncInfo } from "winrt/Windows/Foundation/IAsyncInfo";
import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.WindowsLive.Photomail.GetExifRotationOperation')
export class GetExifRotationOperation implements IAsyncOperation<ExifOrientation>, IAsyncInfo { 
    readonly errorCode: number = null;
    readonly id: number = null;
    readonly status: AsyncStatus = null;
    completed: AsyncOperationCompletedHandler<ExifOrientation> = null;
    getResults(): ExifOrientation {
        throw new Error('GetExifRotationOperation#getResults not implemented')
    }
    cancel(): void {
        console.warn('GetExifRotationOperation#cancel not implemented')
    }
    close(): void {
        console.warn('GetExifRotationOperation#close not implemented')
    }
}
