// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:07 2021
// </auto-generated>
// --------------------------------------------------

import { IIterable } from "../../Foundation/Collections/IIterable`1";
import { IKeyValuePair } from "../../Foundation/Collections/IKeyValuePair`2";
import { IMap } from "../../Foundation/Collections/IMap`2";
import { IAsyncAction } from "../../Foundation/IAsyncAction";
import { AsyncOperation, IAsyncOperation } from "../../Foundation/IAsyncOperation`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { DocumentProperties } from "./DocumentProperties";
import { IStorageItemExtraProperties } from "./IStorageItemExtraProperties";
import { ImageProperties } from "./ImageProperties";
import { MusicProperties } from "./MusicProperties";
import { VideoProperties } from "./VideoProperties";
import { StorageFile } from "../StorageFile";

@GenerateShim('Windows.Storage.FileProperties.StorageItemContentProperties')
export class StorageItemContentProperties implements IStorageItemExtraProperties {
    private _storageItem: StorageFile;
    
    constructor(storageItem: StorageFile) {
        this._storageItem = storageItem;
    }

    getMusicPropertiesAsync(): IAsyncOperation<MusicProperties> {
        // throw new Error('StorageItemContentProperties#getMusicPropertiesAsync not implemented')
        return AsyncOperation.from(async () => {
            var props = new MusicProperties();
            await props._readPropertiesAsync(this._storageItem);
            return props;
        });
    }
    getVideoPropertiesAsync(): IAsyncOperation<VideoProperties> {
        throw new Error('StorageItemContentProperties#getVideoPropertiesAsync not implemented')
    }
    getImagePropertiesAsync(): IAsyncOperation<ImageProperties> {
        throw new Error('StorageItemContentProperties#getImagePropertiesAsync not implemented')
    }
    getDocumentPropertiesAsync(): IAsyncOperation<DocumentProperties> {
        throw new Error('StorageItemContentProperties#getDocumentPropertiesAsync not implemented')
    }
    retrievePropertiesAsync(propertiesToRetrieve: IIterable<string>): IAsyncOperation<IMap<string, any>> {
        throw new Error('StorageItemContentProperties#retrievePropertiesAsync not implemented')
    }
    savePropertiesAsync(propertiesToSave: IIterable<IKeyValuePair<string, any>>): IAsyncAction {
        throw new Error('StorageItemContentProperties#savePropertiesAsync not implemented')
    }
    savePropertiesAsyncOverloadDefault(): IAsyncAction {
        throw new Error('StorageItemContentProperties#savePropertiesAsyncOverloadDefault not implemented')
    }
}
