// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:08 2021
// </auto-generated>
// --------------------------------------------------

import { HResult } from "../../Foundation/HResult";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.UI.Notifications.ToastFailedEventArgs')
export class ToastFailedEventArgs { 
    errorCode: number = null;
}
