// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:09 2021
// </auto-generated>
// --------------------------------------------------

import { XmlDocument } from "../../Data/Xml/Dom/XmlDocument";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { ToastNotifier } from "./ToastNotifier";
import { ToastTemplateType } from "./ToastTemplateType";

@GenerateShim('Windows.UI.Notifications.ToastNotificationManager')
export class ToastNotificationManager { 
    static createToastNotifier(): ToastNotifier {
        throw new Error('ToastNotificationManager#createToastNotifier not implemented')
    }
    static createToastNotifierWithId(applicationId: string): ToastNotifier {
        throw new Error('ToastNotificationManager#createToastNotifierWithId not implemented')
    }
    static getTemplateContent(type: ToastTemplateType): XmlDocument {
        throw new Error('ToastNotificationManager#getTemplateContent not implemented')
    }
}
