// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:08 2021
// </auto-generated>
// --------------------------------------------------

export enum GestureSettings {
    none = 0,
    tap = 1,
    doubleTap = 2,
    hold = 4,
    holdWithMouse = 8,
    rightTap = 16,
    drag = 32,
    manipulationTranslateX = 64,
    manipulationTranslateY = 128,
    manipulationTranslateRailsX = 256,
    manipulationTranslateRailsY = 512,
    manipulationRotate = 1024,
    manipulationScale = 2048,
    manipulationTranslateInertia = 4096,
    manipulationRotateInertia = 8192,
    manipulationScaleInertia = 16384,
    crossSlide = 32768,
    manipulationMultipleFingerPanning = 65536,
}
