// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";
import { IBuffer } from "../../../Storage/Streams/IBuffer";

@GenerateShim('Windows.Security.Cryptography.Core.CryptographicHash')
export class CryptographicHash { 
    append(data: IBuffer): void {
        console.warn('CryptographicHash#append not implemented')
    }
    getValueAndReset(): IBuffer {
        throw new Error('CryptographicHash#getValueAndReset not implemented')
    }
}
