// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { ABTestingOverridesConfiguration } from "./ABTestingOverridesConfiguration";
import { AdsConfiguration } from "./AdsConfiguration";
import { AmsterdamConfiguration } from "./AmsterdamConfiguration";
import { DRMConfiguration } from "./DRMConfiguration";
import { FUEConfiguration } from "./FUEConfiguration";
import { FeaturesConfiguration } from "./FeaturesConfiguration";
import { FlightingConfiguration } from "./FlightingConfiguration";
import { FulfillmentConfiguration } from "./FulfillmentConfiguration";
import { GeneralSettingsConfiguration } from "./GeneralSettingsConfiguration";
import { GrovelerConfiguration } from "./GrovelerConfiguration";
import { IConfigurationManager } from "./IConfigurationManager";
import { MBRConfiguration } from "./MBRConfiguration";
import { MDLCConfiguration } from "./MDLCConfiguration";
import { MarketplaceConfiguration } from "./MarketplaceConfiguration";
import { MediaStoreConfiguration } from "./MediaStoreConfiguration";
import { MusicConfiguration } from "./MusicConfiguration";
import { PlaybackConfiguration } from "./PlaybackConfiguration";
import { QueriesConfiguration } from "./QueriesConfiguration";
import { ServiceConfiguration } from "./ServiceConfiguration";
import { ServicesConfiguration } from "./ServicesConfiguration";
import { ShellConfiguration } from "./ShellConfiguration";
import { ShipAssertsConfiguration } from "./ShipAssertsConfiguration";
import { SyncConfiguration } from "./SyncConfiguration";
import { TelemetryConfiguration } from "./TelemetryConfiguration";
import { TransferConfiguration } from "./TransferConfiguration";
import { UnitTestConfiguration } from "./UnitTestConfiguration";
import { VideoConfiguration } from "./VideoConfiguration";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Configuration.ConfigurationManager')
export class ConfigurationManager implements IConfigurationManager { 
    abTestingOverrides: ABTestingOverridesConfiguration = new ABTestingOverridesConfiguration;
    ads: AdsConfiguration = new AdsConfiguration;
    amsterdam: AmsterdamConfiguration = new AmsterdamConfiguration;
    drm: DRMConfiguration = new DRMConfiguration;
    fue: FUEConfiguration = new FUEConfiguration;
    features: FeaturesConfiguration = new FeaturesConfiguration;
    flighting: FlightingConfiguration = new FlightingConfiguration;
    fulfillment: FulfillmentConfiguration = new FulfillmentConfiguration;
    generalSettings: GeneralSettingsConfiguration = new GeneralSettingsConfiguration;
    groveler: GrovelerConfiguration = new GrovelerConfiguration;
    mbr: MBRConfiguration = new MBRConfiguration;
    mdlc: MDLCConfiguration = new MDLCConfiguration;
    marketplace: MarketplaceConfiguration = new MarketplaceConfiguration;
    mediaStore: MediaStoreConfiguration = new MediaStoreConfiguration;
    music: MusicConfiguration = new MusicConfiguration;
    playback: PlaybackConfiguration = new PlaybackConfiguration;
    queries: QueriesConfiguration = new QueriesConfiguration;
    service: ServiceConfiguration = new ServiceConfiguration;
    services: ServicesConfiguration = new ServicesConfiguration;
    shell: ShellConfiguration = new ShellConfiguration;
    shipAsserts: ShipAssertsConfiguration = new ShipAssertsConfiguration;
    sync: SyncConfiguration = new SyncConfiguration;
    telemetry: TelemetryConfiguration = new TelemetryConfiguration;
    transfer: TransferConfiguration = new TransferConfiguration;
    unitTest: UnitTestConfiguration = new UnitTestConfiguration;
    video: VideoConfiguration = new VideoConfiguration;
}
