// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IFlightingConfiguration } from "./IFlightingConfiguration";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Configuration.FlightingConfiguration')
export class FlightingConfiguration implements IFlightingConfiguration { 
    groupIds: string = null;
    experimentIds: string = null;
    deeplinkTunerConfigEnabled: boolean = null;
}
