// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------


export interface IDRMConfiguration {
    lastFullRefresh: Date;
    silentDRMConfiguration: boolean;
    syncLicenseMinCount: number;
    syncLicenseMinHours: number;
    timeBetweenRefreshSessionsMins: number;
    timeBetweenRefreshms: number;
}
