// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IShellConfiguration } from "./IShellConfiguration";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Configuration.ShellConfiguration')
export class ShellConfiguration implements IShellConfiguration { 
    showApplicationPivot: boolean = true;
    retailExperience: boolean = false;
    randomAccessCacheLifespanMS: number = 2000;
    previousSoftBlockVersion: string = null;
    preventSelectionManagerSettingSaves: boolean = null;
    notificationVersion: number = 2;
    musicDeviceView: number = null;
    showRemoveInPreferences: boolean = null;
    musicCollectionView: number = null;
    music2DashboardRefreshTimer: number = null;
    mixIdleTimeoutMS: number = null;
    mixFixedRandom: boolean = null;
    loadClassicApp: boolean = true;
    lastUsedAppNavigationMonikerData: string = null;
    lastUpdateCheck: Date = null;
    applyBackgroundOnAccountCreation: boolean = null;
    lastClientCulture: string = null;
    initializationSequence: number = null;
    ignoreLowPriorityAsserts: boolean = false;
    gamesDashboardRefreshTimer: number = null;
    enableWindowSnap: boolean = null;
    enableWebHostResizeMessage: boolean = null;
    dragAndDropEnabled: boolean = true;
    video2DashboardRefreshTimer: number = null;
    defaultLibraryChunkSize: number = null;
    cloudMatching: number = 1;
    backgroundImage: string = null;
    backgroundColor: number = null;
    backgroundBackStackTrimmingDelay: number = null;
    attachLargeObjectToUnloadedControl: boolean = null;
    attachCookieToRemovedDomElements: boolean = null;
    lastMarketplaceCulture: string = null;
    showAppsCollectionNotification: boolean = null;
    topBarColor: number = null;
    whatsNewShownForRelease: string = null;
    whatsNewReleaseName: string = null;
    whatsNewNonLaunchCountData: string = null;
    webBlendResponseTimeoutMS: number = null;
    webBlendLoadTimeoutMS: number = null;
    videoDashboardRefreshTimer: number = null;
    videoCollectionView: number = null;
    dontPendControlUnloadCleanup: boolean = null;
    useUserEngagementService: boolean = null;
    useStickyPivots: boolean = null;
    useEDSForSearch: boolean = null;
    uiRefresh: boolean = false;
    topBarSelectedHoveredColor: number = null;
    topBarSelectedColor: number = null;
    topBarHoveredColor: number = null;
    whatsNewStringIdsForMusic: string = null;
    suppressWhatsNewShownForRelease: boolean = null;
    startupPage: string = null;
    sounds: boolean = null;
    showWhatsNew: boolean = null;
    showTVPivot: boolean = null;
    showSongInfoInWindowTitle: boolean = null;
    musicDashboardRefreshTimer: number = null;
    showPreviewBranding: boolean = true;
    showPlayInfoInTaskbar: boolean = null;
    showNowPlayingBackgroundOnIdleTimeout: number = null;
    showMoviesPivot: boolean = null;
    showContentTypes: boolean = null;
    showAppsForZuneHDOnlyHeader: boolean = null;
    showAppsForWindowsPhoneOnlyHeader: boolean = null;
    mockNetworkStatusOffline: boolean = false;
}
