// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IVideoConfiguration } from "./IVideoConfiguration";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Configuration.VideoConfiguration')
export class VideoConfiguration implements IVideoConfiguration { 
    interactiveTVDeepLinkUrls: string = null;
    interactiveMovieMediaIDs: string = null;
    interactiveMovieDeepLinkUrls: string = null;
    interactiveAppTextIds: number = null;
    epgSecondaryColorR: number = null;
    lastNightOnTVTuesday: string = null;
    epgSecondaryColorB: number = null;
    epgSecondaryColorA: number = null;
    epgPrimaryColorR: number = null;
    epgPrimaryColorG: number = null;
    epgPrimaryColorB: number = null;
    epgPrimaryColorA: number = null;
    epgMaxItemsPerChannel: number = null;
    epgBackgroundTaskTimeTriggerInMinutes: number = null;
    actorSearchEnabled: boolean = null;
    downloadCopyFileTransferRate: number = null;
    defaultPivotIndex: number = null;
    customerRatingSort: boolean = null;
    contentRestrictionMaxEmptyFeaturedItems: number = null;
    actorSearchSlot8EditValue: number = null;
    supportsGraceNote: boolean = null;
    actorSearchSlot2EditValue: number = null;
    actorSearchSlot17EditValue: number = null;
    actorSearchSlot14EditValue: number = null;
    actorSearchSlot11EditValue: number = null;
    actorSearchSlot0EditValue: number = null;
    enablePresaleAndBundles: boolean = null;
    interactiveTVMediaIDs: string = null;
    requireGoldForInteractive: boolean = null;
    videoPostRollResetDate: Date = null;
    videoPlaySeasonDeepLinkEnabled: boolean = null;
    videoLXDefaultToClassic: boolean = null;
    videoLXAutoResumePersonalVideos: boolean = null;
    videoDownloadQualityDialogUsesSizes: boolean = null;
    actorSearchSlot5EditValue: number = null;
    supportsEditorialTVEpisodes: boolean = null;
    showWelcomeDialog: boolean = null;
    showVideoPostRollMax: number = null;
    showVideoPostRollCount: number = null;
    showDownloadCopyingHelpLink: boolean = null;
    videoPostRollResetInterval: number = null;
    postRollPurchasesEnabled: boolean = null;
    postRollMinDurationForShortEpisodes: number = null;
    postRollEnabled: boolean = null;
    postRollCreditsServiceEnabled: boolean = null;
    postRollCreditsGapInSeconds: number = null;
    postRollCountdownTimeInSeconds: number = null;
    offerIdsVideoFreeWithAds: string = null;
    lastNightOnTVWednesday: string = null;
    epgSecondaryColorG: number = null;
    lastNightOnTVThursday: string = null;
    lastNightOnTVSunday: string = null;
    lastNightOnTVSaturday: string = null;
    lastNightOnTVMonday: string = null;
    lastNightOnTVFriday: string = null;
}
