// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Wed Sep 15 17:20:14 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../Interop/GenerateShim";

@GenerateShim('Windows.Foundation.Diagnostics.LoggingChannelOptions')
export class LoggingChannelOptions { 
    group: string = null;
    // constructor();
    // constructor(group: string);
    constructor(...args) { }
}
