// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------


export interface IProvidersTemplate {
    eventEnabled(eventIndex: number): number;
    traceTemplateEventDescriptor(_MCGEN_EventIndex: number): void;
    traceTemplate_qqq(_MCGEN_EventIndex: number, albumId: number, artistId: number, trackId: number): void;
    traceTemplate_z(_MCGEN_EventIndex: number, albumTitle: string): void;
    traceTemplate_zq(_MCGEN_EventIndex: number, albumTitle: string, artistId: number): void;
    traceTemplate_qq(_MCGEN_EventIndex: number, personId: number, mediaId: number): void;
    traceTemplate_qzq(_MCGEN_EventIndex: number, albumId: number, trackTitle: string, trackNumber: number): void;
    traceTemplate_q(_MCGEN_EventIndex: number, trackId: number): void;
}
