// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------


export interface IServiceEventProviderTemplate {
    eventEnabled(eventIndex: number): number;
    traceTemplate_d(_MCGEN_EventIndex: number, hresult: number): void;
    traceTemplate_z(_MCGEN_EventIndex: number, message: string): void;
    traceTemplateEventDescriptor(_MCGEN_EventIndex: number): void;
    traceTemplate_zz(_MCGEN_EventIndex: number, name: string, value: string): void;
}
