// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------


export interface IShellTemplate {
    eventEnabled(eventIndex: number): number;
    traceTemplate_z(_MCGEN_EventIndex: number, moniker: string): void;
    traceTemplateEventDescriptor(_MCGEN_EventIndex: number): void;
    traceTemplate_zzz(_MCGEN_EventIndex: number, pageMoniker: string, hubMoniker: string, panelMoniker: string): void;
    traceTemplate_tz(_MCGEN_EventIndex: number, result: boolean, message: string): void;
    traceTemplate_dz(_MCGEN_EventIndex: number, id: number, message: string): void;
    traceTemplate_zz(_MCGEN_EventIndex: number, value: string, source: string): void;
    traceTemplate_q(_MCGEN_EventIndex: number, durationMsec: number): void;
    traceTemplate_zq(_MCGEN_EventIndex: number, name: string, durationMsec: number): void;
}
