// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { ILegacyPerfTraceTemplate } from "./ILegacyPerfTraceTemplate";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Instrumentation.Providers.LegacyPerfTraceTemplate')
export class LegacyPerfTraceTemplate implements ILegacyPerfTraceTemplate { 
    eventEnabled(eventIndex: number): number {
        throw new Error('LegacyPerfTraceTemplate#eventEnabled not implemented')
    }
    traceTemplate_qz(_MCGEN_EventIndex: number, httpEvent: number, url: string): void {
        console.warn('LegacyPerfTraceTemplate#traceTemplate_qz not implemented')
    }
    traceTemplate_qqq(_MCGEN_EventIndex: number, reporterTag: number, actionType: number, reason: number): void {
        console.warn('LegacyPerfTraceTemplate#traceTemplate_qqq not implemented')
    }
    traceTemplate_qzqd(_MCGEN_EventIndex: number, type: number, fileName: string, graphType: number, lastHR: number): void {
        console.warn('LegacyPerfTraceTemplate#traceTemplate_qzqd not implemented')
    }
    traceTemplate_qq(_MCGEN_EventIndex: number, launchEvent: number, launchEventData: number): void {
        console.warn('LegacyPerfTraceTemplate#traceTemplate_qq not implemented')
    }
}
