// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { ISocial } from "./ISocial";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Instrumentation.Providers.Social')
export class Social implements ISocial { 
    isAvatarRendererFrameEndEnabled: boolean = null;
    isAvatarRendererFrameStartEnabled: boolean = null;
    isAvatarRendererShutdownEnabled: boolean = null;
    traceAvatarRendererFrameStart(id: string): void {
        console.warn('Social#traceAvatarRendererFrameStart not implemented')
    }
    traceAvatarRendererFrameEnd(id: string, duration: number): void {
        console.warn('Social#traceAvatarRendererFrameEnd not implemented')
    }
    traceAvatarRendererShutdown(id: string): void {
        console.warn('Social#traceAvatarRendererShutdown not implemented')
    }
}
