// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:06 2021
// </auto-generated>
// --------------------------------------------------

import { IImageProvider } from "../IImageProvider";
import { IArticle } from "./IArticle";
import { IArticleInfo } from "./IArticleInfo";
import { ImageResourceDescriptor } from "./ImageResourceDescriptor";
import { Title } from "./Title";
import { IVector } from "winrt/Windows/Foundation/Collections/IVector`1";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('AppEx.Common.ArticleReader.Model.Article')
export class Article implements IImageProvider, IArticle, IStringable { 
    nextArticle: IArticleInfo = null;
    previousArticle: IArticleInfo = null;
    metadata: IArticleInfo = null;
    title: Title = null;
    readonly blocks: IVector<any> = null;
    additionalPrefetchImages: IVector<ImageResourceDescriptor> = null;
    moreArticles: IVector<IArticleInfo> = null;
    renderData: string = null;
    layouts: string = null;
    getImages(): IVector<ImageResourceDescriptor> {
        throw new Error('Article#getImages not implemented')
    }
    toString(): string {
        throw new Error('Article#toString not implemented')
    }
}
