// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:06 2021
// </auto-generated>
// --------------------------------------------------

import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('AppEx.Common.ArticleReader.Model.LaunchUriExtraLink')
export class LaunchUriExtraLink implements IStringable { 
    appLink: string = null;
    externalLink: string = null;
    label: string = null;
    description: string = null;
    toString(): string {
        throw new Error('LaunchUriExtraLink#toString not implemented')
    }
}
