// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:06 2021
// </auto-generated>
// --------------------------------------------------

import { ImageDescriptor } from "./ImageDescriptor";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('AppEx.Common.ArticleReader.Model.ReferralDescriptor')
export class ReferralDescriptor implements IStringable { 
    url: string = null;
    url2: string = null;
    thumbnail: ImageDescriptor = null;
    logo: ImageDescriptor = null;
    title: string = null;
    description: string = null;
    urlAction: string = null;
    urlAction2: string = null;
    toString(): string {
        throw new Error('ReferralDescriptor#toString not implemented')
    }
}
