// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:07 2021
// </auto-generated>
// --------------------------------------------------

import { IArticleInfo } from "./IArticleInfo";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('AppEx.Common.ArticleReader.Model.WebpageInfo')
export class WebpageInfo implements IArticleInfo, IStringable { 
    articleId: string = null;
    readonly articleType: string = null;
    toString(): string {
        throw new Error('WebpageInfo#toString not implemented')
    }
}
