// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:01 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Data.Xml.Dom.XmlDomImplementation')
export class XmlDomImplementation { 
    hasFeature(feature: string, version: any): boolean {
        throw new Error('XmlDomImplementation#hasFeature not implemented')
    }
}
