// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { ICollectionBuildProgressEventHandlerArgs } from "./ICollectionBuildProgressEventHandlerArgs";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Platform.CollectionBuildProgressEventHandlerArgs')
export class CollectionBuildProgressEventHandlerArgs implements ICollectionBuildProgressEventHandlerArgs { 
    isCompleted: number = null;
    itemsCompleted: number = null;
}
