// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { CollectionBuildEndEventHandlerArgs } from "./CollectionBuildEndEventHandlerArgs";
import { CollectionBuildMDLCProgressEventHandlerArgs } from "./CollectionBuildMDLCProgressEventHandlerArgs";
import { CollectionBuildProgressEventHandlerArgs } from "./CollectionBuildProgressEventHandlerArgs";
import { EventHandler } from "winrt/Windows/Foundation/EventHandler`1";
import { TypedEventHandler } from "winrt/Windows/Foundation/TypedEventHandler`2";

export interface ICollectionBuildingManager {
    oncollectionbuildbeginevent: EventHandler<number>;
    oncollectionbuildcloudcollectionv2firsttrackaddedevent: EventHandler<number>;
    oncollectionbuilddeduplicationstrategyrequiredevent: EventHandler<number>;
    oncollectionbuildendevent: TypedEventHandler<ICollectionBuildingManager, CollectionBuildEndEventHandlerArgs>;
    oncollectionbuildmdlcprogressevent: TypedEventHandler<ICollectionBuildingManager, CollectionBuildMDLCProgressEventHandlerArgs>;
    oncollectionbuildmediasyncedevent: EventHandler<number>;
    oncollectionbuildprefetchcompleteevent: EventHandler<number>;
    oncollectionbuildprogressevent: TypedEventHandler<ICollectionBuildingManager, CollectionBuildProgressEventHandlerArgs>;
    oncollectionbuildupsyncprogressevent: TypedEventHandler<ICollectionBuildingManager, CollectionBuildProgressEventHandlerArgs>;
    addEventListener(name: string, handler: any)
    removeEventListener(name: string, handler: any)
}
