// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { GetDetailReturnValue } from "./GetDetailReturnValue";
import { IAsyncAction } from "winrt/Windows/Foundation/IAsyncAction";
import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";

export interface IOfflineDetailProvider {
    addWithMediaAsync(libraryId: number, libraryTypeId: number, expirationDays: number, detailBuffer: string, detailSize: number): IAsyncAction;
    addWithKeyAsync(key: string, expirationDays: number, detailBuffer: string, detailSize: number): IAsyncAction;
    removeWithMediaAsync(libraryId: number, libraryTypeId: number): IAsyncAction;
    removeWithKeyAsync(key: string): IAsyncAction;
    getDetailWithMediaAsync(libraryId: number, libraryTypeId: number): IAsyncOperation<GetDetailReturnValue>;
    getDetailWithKeyAsync(key: string): IAsyncOperation<GetDetailReturnValue>;
    setIfMatchValueWithKeyAsync(key: string, ifMatchValue: string): IAsyncAction;
}
