// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IShareableContent } from "./IShareableContent";
import { MediaAvailability } from "./MediaAvailability";
import { IVectorView } from "winrt/Windows/Foundation/Collections/IVectorView`1";
import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";

export interface ISharingProvider {
    getShareableContentForMediaAsync(piLibraryIds: IVectorView<number>, piLibraryTypes: IVectorView<number>, availabilityFilter: MediaAvailability): IAsyncOperation<IShareableContent>;
}
