// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { SmartDJState } from "./SmartDJState";
import { SmartVJState } from "./SmartVJState";

export interface ITrackMetadata {
    actionableMediaId: string;
    artist: string;
    artistBingId: string;
    artistImageUrl: string;
    artistMediaId: string;
    canSmartDJ: SmartDJState;
    canSmartVJ: SmartVJState;
    contentId: string;
    discNumber: number;
    editedFields: number;
    explicitLyrics: string;
    genre: string;
    period: string;
    releaseDate: string;
    requestId: string;
    sortArtist: string;
    sortTitle: string;
    title: string;
    trackBingId: string;
    trackMediaId: string;
    trackNumber: number;
    unblockFromCloud: boolean;
    uniqueFileId: string;
}
