// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

export enum MediaAvailability {
    undefined = 800,
    available = 801,
    availableOffline = 802,
    availableFromCloud = 803,
    availableFromCloudDriveOnly = 804,
    availableFromCloudOnly = 805,
    availableOnRemovableDrive = 806,
    availableOnInternalDrive = 807,
    thisDeviceOnly = 808,
    oneDrive = 809,
    musicPass = 810,
    purchased = 811,
}
