// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { IIterable } from "../../../Foundation/Collections/IIterable`1";
import { IVectorView } from "../../../Foundation/Collections/IVectorView`1";
import { DateTime } from "../../../Foundation/DateTime";
import { IAsyncOperation } from "../../../Foundation/IAsyncOperation`1";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";
import { CertificateChain } from "./CertificateChain";
import { ChainBuildingParameters } from "./ChainBuildingParameters";
import { IBuffer } from "../../../Storage/Streams/IBuffer";

@GenerateShim('Windows.Security.Cryptography.Certificates.Certificate')
export class Certificate { 
    friendlyName: string = null;
    enhancedKeyUsages: IVectorView<string> = null;
    hasPrivateKey: boolean = null;
    isStronglyProtected: boolean = null;
    issuer: string = null;
    serialNumber: number[] = null;
    subject: string = null;
    validFrom: Date = null;
    validTo: Date = null;
    constructor(certBlob: IBuffer) {
        console.warn('Certificate.ctor not implemented')
    }
    buildChainAsync(certificates: IIterable<Certificate>): IAsyncOperation<CertificateChain> {
        throw new Error('Certificate#buildChainAsync not implemented')
    }
    buildChainWithParametersAsync(certificates: IIterable<Certificate>, parameters: ChainBuildingParameters): IAsyncOperation<CertificateChain> {
        throw new Error('Certificate#buildChainWithParametersAsync not implemented')
    }
    getHashValue(): number[] {
        throw new Error('Certificate#getHashValue not implemented')
    }
    getHashValueWithAlgorithm(hashAlgorithmName: string): number[] {
        throw new Error('Certificate#getHashValueWithAlgorithm not implemented')
    }
    getCertificateBlob(): IBuffer {
        throw new Error('Certificate#getCertificateBlob not implemented')
    }
}
