// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { IVectorView } from "../../../Foundation/Collections/IVectorView`1";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";
import { Certificate } from "./Certificate";
import { ChainValidationParameters } from "./ChainValidationParameters";
import { ChainValidationResult } from "./ChainValidationResult";

@GenerateShim('Windows.Security.Cryptography.Certificates.CertificateChain')
export class CertificateChain { 
    validate(): ChainValidationResult {
        throw new Error('CertificateChain#validate not implemented')
    }
    validateWithParameters(parameter: ChainValidationParameters): ChainValidationResult {
        throw new Error('CertificateChain#validateWithParameters not implemented')
    }
    getCertificates(includeRoot: boolean): IVectorView<Certificate> {
        throw new Error('CertificateChain#getCertificates not implemented')
    }
}
