// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { IAsyncOperation } from "../../../Foundation/IAsyncOperation`1";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Security.Cryptography.Certificates.KeyAttestationHelper')
export class KeyAttestationHelper { 
    static decryptTpmAttestationCredentialAsync(credential: string): IAsyncOperation<string> {
        throw new Error('KeyAttestationHelper#decryptTpmAttestationCredentialAsync not implemented')
    }
    static getTpmAttestationCredentialId(credential: string): string {
        throw new Error('KeyAttestationHelper#getTpmAttestationCredentialId not implemented')
    }
}
