// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:01 2021
// </auto-generated>
// --------------------------------------------------

export enum GattCharacteristicProperties {
    none = 0,
    broadcast = 1,
    read = 2,
    writeWithoutResponse = 4,
    write = 8,
    notify = 16,
    indicate = 32,
    authenticatedSignedWrites = 64,
    extendedProperties = 128,
    reliableWrites = 256,
    writableAuxiliaries = 512,
}
