// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { IVectorView } from "../../../Foundation/Collections/IVectorView`1";
import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";
import { OnlineIdServiceTicket } from "./OnlineIdServiceTicket";

@GenerateShim('Windows.Security.Authentication.OnlineId.UserIdentity')
export class UserIdentity { 
    firstName: string = null;
    id: string = null;
    isBetaAccount: boolean = null;
    isConfirmedPC: boolean = null;
    lastName: string = null;
    safeCustomerId: string = null;
    signInName: string = null;
    tickets: IVectorView<OnlineIdServiceTicket> = null;
}
