// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:00 2021
// </auto-generated>
// --------------------------------------------------

import { ContactFieldCategory } from "./ContactFieldCategory";
import { ContactFieldType } from "./ContactFieldType";
import { IContactField } from "./IContactField";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { Uri } from "../../Foundation/Uri";

@GenerateShim('Windows.ApplicationModel.Contacts.ContactInstantMessageField')
export class ContactInstantMessageField implements IContactField { 
    displayText: string = null;
    launchUri: Uri = null;
    service: string = null;
    userName: string = null;
    category: ContactFieldCategory = null;
    name: string = null;
    type: ContactFieldType = null;
    value: string = null;
    // constructor(userName: string);
    // constructor(userName: string, category: ContactFieldCategory);
    // constructor(userName: string, category: ContactFieldCategory, service: string, displayText: string, verb: Uri);
    constructor(...args) { }
}
