// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:00 2021
// </auto-generated>
// --------------------------------------------------

import { ContactPhoneKind } from "./ContactPhoneKind";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.ApplicationModel.Contacts.ContactPhone')
export class ContactPhone { 
    number: string = null;
    kind: ContactPhoneKind = null;
    description: string = null;
}
