// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:00 2021
// </auto-generated>
// --------------------------------------------------

import { ContactFieldType } from "./ContactFieldType";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.ApplicationModel.Contacts.KnownContactField')
export class KnownContactField { 
    static email: string = null;
    static instantMessage: string = null;
    static location: string = null;
    static phoneNumber: string = null;
    static convertNameToType(name: string): ContactFieldType {
        throw new Error('KnownContactField#convertNameToType not implemented')
    }
    static convertTypeToName(type: ContactFieldType): string {
        throw new Error('KnownContactField#convertTypeToName not implemented')
    }
}
