// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Thu Apr  8 00:47:24 2021
// </auto-generated>
// --------------------------------------------------

import { Result } from "./Result";
import { DateTime } from "winrt/Windows/Foundation/DateTime";

export interface IDeviceAssociationResult {
    contextUrl: string;
    errorCode: number;
    errorMessage: string;
    limit: number;
    nextTime: Date;
    result: Result;
}
