// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:09 2021
// </auto-generated>
// --------------------------------------------------

import { IpcHelper } from "../../../IpcHelper";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { ActivatedDeferralV1 } from "../../Foundation/Interop/IpcConstants";

@GenerateShim('Windows.UI.WebUI.ActivatedDeferral')
export class ActivatedDeferral { 
    private __deferralId : string;
    constructor(deferralId: string) {
        this.__deferralId = deferralId;
    }

    complete(): void {
        IpcHelper.post(ActivatedDeferralV1, { deferralId: this.__deferralId, type: 'completed' })
    }
}
