// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:03 2021
// </auto-generated>
// --------------------------------------------------

export interface ComputedProperties {
    sessionTimestamp: string;
    machineId: string;
    visitorId: string;
    isUserLive: string;
    hardwareInfo: string;
    oemid: string;
    clientVersion: string;
    buildBranchInfo: string;
    computerArchitecture: string;
    marketplaceLocation: string;
    timeZone: string;
    userLanguage: string;
    isTest: string;
    userAge: string;
    userGender: string;
    userEnvironment: string;
    oslanguage: string;
    sessionGuid: string;
    previousSessionGuid: string;
}
