// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:07 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { AccessListEntry } from "./AccessListEntry";

@GenerateShim('Windows.Storage.AccessCache.ItemRemovedEventArgs')
export class ItemRemovedEventArgs { 
    removedEntry: AccessListEntry = null;
}
