// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:07 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { StorageItemAccessList } from "./StorageItemAccessList";
import { StorageItemMostRecentlyUsedList } from "./StorageItemMostRecentlyUsedList";

@GenerateShim('Windows.Storage.AccessCache.StorageApplicationPermissions')
export class StorageApplicationPermissions { 
    static futureAccessList: StorageItemAccessList = null;
    static mostRecentlyUsedList: StorageItemMostRecentlyUsedList = null;
}
