// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:10 2021
// </auto-generated>
// --------------------------------------------------

import { PrefetchItem } from "./Utilities/PrefetchItem";
import { IAsyncAction } from "winrt/Windows/Foundation/IAsyncAction";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { AsyncAction } from "winrt/Windows/Foundation/Interop/AsyncAction";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('News.NewsUtil')
export class NewsUtil implements IStringable { 
    static readonly instance: NewsUtil = new NewsUtil();
    bdiTimeToString(bdiTime: number): string {
        throw new Error('NewsUtil#bdiTimeToString not implemented')
    }
    getDomainFromUrl(url: string): string {
        throw new Error('NewsUtil#getDomainFromUrl not implemented')
    }
    getStringHashCode(str: string): string {
        throw new Error('NewsUtil#getStringHashCode not implemented')
    }
    getTodayDateString(): string {
        throw new Error('NewsUtil#getTodayDateString not implemented')
    }
    initializePrefetchManager(groupId: string): IAsyncAction {
        return AsyncAction.from(async () => console.warn('NewsUtil#initializePrefetchManager not implemented'));
    }
    isBlockListed(article_url: string): boolean {
        throw new Error('NewsUtil#isBlockListed not implemented')
    }
    isDomainBlockListed(domain_uri: string): boolean {
        throw new Error('NewsUtil#isDomainBlockListed not implemented')
    }
    prefetchItems(groupId: string, items: PrefetchItem[]): void {
        console.warn('NewsUtil#prefetchItems not implemented')
    }
    toString(): string {
        throw new Error('NewsUtil#toString not implemented')
    }
}
