// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IAsyncAction } from "../../Foundation/IAsyncAction";
import { IAsyncOperation } from "../../Foundation/IAsyncOperation`1";
import { IClosable } from "../../Foundation/IClosable";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { IBuffer } from "../../Storage/Streams/IBuffer";

@GenerateShim('Windows.Devices.SmartCards.SmartCardChallengeContext')
export class SmartCardChallengeContext implements IClosable { 
    challenge: IBuffer = null;
    verifyResponseAsync(response: IBuffer): IAsyncOperation<boolean> {
        throw new Error('SmartCardChallengeContext#verifyResponseAsync not implemented')
    }
    provisionAsync(response: IBuffer, formatCard: boolean): IAsyncAction {
        throw new Error('SmartCardChallengeContext#provisionAsync not implemented')
    }
    provisionAsyncWithNewCardId(response: IBuffer, formatCard: boolean, newCardId: string): IAsyncAction {
        throw new Error('SmartCardChallengeContext#provisionAsyncWithNewCardId not implemented')
    }
    changeAdministrativeKeyAsync(response: IBuffer, newAdministrativeKey: IBuffer): IAsyncAction {
        throw new Error('SmartCardChallengeContext#changeAdministrativeKeyAsync not implemented')
    }
    close(): void {
        console.warn('SmartCardChallengeContext#close not implemented')
    }
}
