// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:01 2021
// </auto-generated>
// --------------------------------------------------

import { IVector } from "../../Foundation/Collections/IVector`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { StorageFolder } from "../../Storage/StorageFolder";

@GenerateShim('Windows.ApplicationModel.Search.LocalContentSuggestionSettings')
export class LocalContentSuggestionSettings { 
    enabled: boolean = null;
    aqsFilter: string = null;
    locations: IVector<StorageFolder> = null;
    propertiesToMatch: IVector<string> = null;
}
