// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:01 2021
// </auto-generated>
// --------------------------------------------------

import { IIterable } from "../../Foundation/Collections/IIterable`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { IRandomAccessStreamReference } from "../../Storage/Streams/IRandomAccessStreamReference";

@GenerateShim('Windows.ApplicationModel.Search.SearchSuggestionCollection')
export class SearchSuggestionCollection { 
    size: number = null;
    appendQuerySuggestion(text: string): void {
        console.warn('SearchSuggestionCollection#appendQuerySuggestion not implemented')
    }
    appendQuerySuggestions(suggestions: IIterable<string>): void {
        console.warn('SearchSuggestionCollection#appendQuerySuggestions not implemented')
    }
    appendResultSuggestion(text: string, detailText: string, tag: string, image: IRandomAccessStreamReference, imageAlternateText: string): void {
        console.warn('SearchSuggestionCollection#appendResultSuggestion not implemented')
    }
    appendSearchSeparator(label: string): void {
        console.warn('SearchSuggestionCollection#appendSearchSeparator not implemented')
    }
}
