// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IBlockRefresh } from "./IBlockRefresh";
import { IRefreshEntitlementsResult } from "./IRefreshEntitlementsResult";
import { IVectorView } from "winrt/Windows/Foundation/Collections/IVectorView`1";
import { IVector } from "winrt/Windows/Foundation/Collections/IVector`1";
import { IAsyncAction } from "winrt/Windows/Foundation/IAsyncAction";
import { IAsyncOperation } from "winrt/Windows/Foundation/IAsyncOperation`1";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Entertainment.Fulfillment.Video.Entitlements')
export class Entitlements { 
    static isBlockRefreshPending: boolean = null;
    static blockRefreshAsync(): IAsyncOperation<IBlockRefresh> {
        throw new Error('Entitlements#blockRefreshAsync not implemented')
    }
    static checkServiceAvailabilityAsync(productGroups: IVectorView<IVectorView<string>>): IAsyncOperation<boolean> {
        throw new Error('Entitlements#checkServiceAvailabilityAsync not implemented')
    }
    static purchaseOfferAsync(signedOffer: string): IAsyncAction {
        throw new Error('Entitlements#purchaseOfferAsync not implemented')
    }
    static queryForOfferInstanceIdsAsync(productIds: IVectorView<string>): IAsyncOperation<IVector<string>> {
        throw new Error('Entitlements#queryForOfferInstanceIdsAsync not implemented')
    }
    static refreshAsync(refreshOnlyProductIds: IVectorView<string>, fResetFilteredProductIds: boolean, fDontShortCircuitAndForceUpdateAllRights: boolean, fRestoreDeletedPurchasesToCollection: boolean, fMarkRentalExpirationsAsTrusted: boolean): IAsyncOperation<IRefreshEntitlementsResult> {
        throw new Error('Entitlements#refreshAsync not implemented')
    }
}
