// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:22:59 2021
// </auto-generated>
// --------------------------------------------------

import { BackgroundTaskRegistration } from "./BackgroundTaskRegistration";
import { IBackgroundCondition } from "./IBackgroundCondition";
import { IBackgroundTrigger } from "./IBackgroundTrigger";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.ApplicationModel.Background.BackgroundTaskBuilder')
export class BackgroundTaskBuilder { 
    taskEntryPoint: string = null;
    name: string = null;
    cancelOnConditionLoss: boolean = null;
    setTrigger(trigger: IBackgroundTrigger): void {
        console.warn('BackgroundTaskBuilder#setTrigger not implemented')
    }
    addCondition(condition: IBackgroundCondition): void {
        console.warn('BackgroundTaskBuilder#addCondition not implemented')
    }
    register(): BackgroundTaskRegistration {
        // throw new Error('BackgroundTaskBuilder#register not implemented')
        return new BackgroundTaskRegistration();
    }
}
