// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:22:59 2021
// </auto-generated>
// --------------------------------------------------

import { IBackgroundCondition } from "./IBackgroundCondition";
import { SystemConditionType } from "./SystemConditionType";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.ApplicationModel.Background.SystemCondition')
export class SystemCondition implements IBackgroundCondition { 
    conditionType: SystemConditionType = null;
    constructor(conditionType: SystemConditionType) {
        console.warn('SystemCondition.ctor not implemented')
    }
}
