// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:11 2021
// </auto-generated>
// --------------------------------------------------

import { XmlDocument } from "../../Data/Xml/Dom/XmlDocument";
import { ISyndicationNode } from "./ISyndicationNode";

export interface ISyndicationText extends ISyndicationNode {
    text: string;
    type: string;
    xml: XmlDocument;
}
