// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:03 2021
// </auto-generated>
// --------------------------------------------------

export enum AttributeTargets {
    all = 4294967295,
    delegate = 1,
    enum = 2,
    event = 4,
    field = 8,
    interface = 16,
    method = 64,
    parameter = 128,
    property = 256,
    runtimeClass = 512,
    struct = 1024,
    interfaceImpl = 2048,
}
