// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:07 2021
// </auto-generated>
// --------------------------------------------------

import { AttributeFilter } from "./AttributeFilter";
import { PageInformation } from "./PageInformation";
import { SortDirection } from "./SortDirection";
import { IVector } from "winrt/Windows/Foundation/Collections/IVector`1";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('AppEx.Common.EntityCollection.Query.EntityQuery')
export class EntityQuery implements IStringable { 
    filters: IVector<AttributeFilter> = null;
    sortIdentifier: string = null;
    sortDirection: SortDirection = null;
    readonly page: PageInformation = null;
    readonly attributes: IVector<string> = null;
    addFilter(attribute: string, value: any[]): void {
        console.warn('EntityQuery#addFilter not implemented')
    }
    toString(): string {
        throw new Error('EntityQuery#toString not implemented')
    }
}
