// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:07 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";
import { PickerClosingOperation } from "./PickerClosingOperation";

@GenerateShim('Windows.Storage.Pickers.Provider.PickerClosingEventArgs')
export class PickerClosingEventArgs { 
    closingOperation: PickerClosingOperation = null;
    isCanceled: boolean = null;
}
