// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:38 2021
// </auto-generated>
// --------------------------------------------------

import { IConfigObject } from "./IConfigObject";
import { IObject } from "./IObject";
import { IStorageFile } from "winrt/Windows/Storage/IStorageFile";
import { IBuffer } from "winrt/Windows/Storage/Streams/IBuffer";

export interface IConfigInstance extends IConfigObject, IObject {
    readonly area_String: string;
    readonly buffer: IBuffer;
    readonly cloud_String: string;
    readonly file: IStorageFile;
    readonly market_String: string;
    uri: string;
    put_BeginDate(value: Date): void;
    put_EndDate(value: Date): void;
    put_File(value: IStorageFile): void;
    put_Buffer(value: IBuffer): void;
    put_XmlData(value: string): void;
    put_Hash(value: string): void;
}
