// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:38 2021
// </auto-generated>
// --------------------------------------------------

import { CalendarFolderType } from "./CalendarFolderType";
import { ContactFolderType } from "./ContactFolderType";
import { FolderAction } from "./FolderAction";
import { FolderType } from "./FolderType";
import { ICollection } from "./ICollection";
import { IObject } from "./IObject";
import { MailFolderType } from "./MailFolderType";

export interface IFolder extends IObject {
    readonly accountId: string;
    readonly canHaveChildren: boolean;
    readonly canMove: boolean;
    readonly canRename: boolean;
    folderName: string;
    folderType: FolderType;
    readonly hasProcessedConversations: boolean;
    readonly hasSynced: boolean;
    readonly isFolderThreadingCapable: boolean;
    readonly isLocalMailFolder: boolean;
    readonly isPinnedToNavPane: boolean;
    parentFolder: IFolder;
    readonly selectionDisabled: boolean;
    specialCalendarFolderType: CalendarFolderType;
    readonly specialContactFolderType: ContactFolderType;
    readonly specialMailFolderType: MailFolderType;
    readonly syncFolderContents: boolean;
    syncStatus: number;
    readonly underDeletedItems: boolean;
    markViewed(): void;
    getChildFolderCollection(fAllTypes: boolean): ICollection;
    startSyncFolderContents(fForceSynchronization: boolean): void;
    recordAction(value: FolderAction): void;
    ensureNameUnique(): void;
}
