// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:38 2021
// </auto-generated>
// --------------------------------------------------

import { AttachmentComposeStatus } from "./AttachmentComposeStatus";
import { AttachmentSyncStatus } from "./AttachmentSyncStatus";
import { AttachmentUIType } from "./AttachmentUIType";
import { IMailMessage } from "./IMailMessage";
import { IObject } from "./IObject";
import { PMFileType } from "./PMFileType";
import { IRandomAccessStream } from "winrt/Windows/Storage/Streams/IRandomAccessStream";

export interface IMailAttachment extends IObject {
    bodyFile: string;
    readonly bodyUri: string;
    composeStatus: AttachmentComposeStatus;
    contentId: string;
    contentLocation: string;
    contentType: string;
    fileAccessToken: string;
    fileName: string;
    photoMailFileType: PMFileType;
    readonly size: number;
    readonly syncStatus: AttachmentSyncStatus;
    transcodedFilename: string;
    transcodedSize: number;
    uiType: AttachmentUIType;
    getBody(): IRandomAccessStream;
    createBody(pBody: IRandomAccessStream): void;
    createBodyFromFile(fileName: string, fileSize: number): void;
    downloadBody(): void;
    cancelDownload(): void;
    clone(pNewParent: IMailMessage): IMailAttachment;
}
