//
// Copyright (c) Microsoft. All rights reserved.
//

Jx.delayGroup("CanvasAutoReplaceDef", function () {
ModernCanvas.AutoReplaceManager.Classes.basic = {};
ModernCanvas.AutoReplaceManager.Classes.basic.element = {
"00a9": "&copy;",
"00ae": "&reg;",
"2122": "&trade;"
};
ModernCanvas.AutoReplaceManager.Classes.basic.realTime = [
["(c)", "string", "&copy;"],
["(C)", "string", "&copy;"],
["(e)", "string", "&euro;"],
["(E)", "string", "&euro;"],
["...", "string", "&hellip;"],
["(r)", "string", "&reg;"],
["(R)", "string", "&reg;"],
["(tm)", "string", "&trade;"],
["(Tm)", "string", "&trade;"],
["(tM)", "string", "&trade;"],
["(TM)", "string", "&trade;"],
["<--", "string", "&larr;"],
["-->", "string", "&rarr;"],
["<->", "string", "&harr;"],
["<==", "string", "&lArr;"],
["==>", "string", "&rArr;"],
["<=>", "string", "&hArr;"],
["\ue000\"", "string", "&ldquo;", false],
[" \"", "string", "&nbsp;&ldquo;", false],
["\xa0\"", "string", "&nbsp;&ldquo;", false],
["(\"", "string", "(&ldquo;", false],
["[\"", "string", "[&ldquo;", false],
["{\"", "string", "{&ldquo;", false],
["<\"", "string", "<&ldquo;", false],
["\"", "string", "&rdquo;", false],
["\ue000'", "string", "&lsquo;", false],
[" '", "string", "&nbsp;&lsquo;", false],
["\xa0'", "string", "&nbsp;&lsquo;", false],
["('", "string", "(&lsquo;", false],
["['", "string", "[&lsquo;", false],
["{'", "string", "{&lsquo;", false],
["<'", "string", "<&lsquo;", false],
["'", "string", "&rsquo;", false],
["A", "string", "&Agrave;", "grave"],
["A", "string", "&Aacute;", "acute"],
["A", "string", "&Acirc;", "circumflex"],
["A", "string", "&Atilde;", "tilde"],
["A", "string", "&Auml;", "diaeresis"],
["A", "string", "&Aring;", "ring"],
["A", "string", "&AElig;", "ligature"],
["C", "string", "&Ccedil;", "cedilla"],
["D", "string", "&ETH;", "acute"],
["E", "string", "&Egrave;", "grave"],
["E", "string", "&Eacute;", "acute"],
["E", "string", "&Ecirc;", "circumflex"],
["E", "string", "&Euml;", "diaeresis"],
["I", "string", "&Igrave;", "grave"],
["I", "string", "&Iacute;", "acute"],
["I", "string", "&Icirc;", "circumflex"],
["I", "string", "&Iuml;", "diaeresis"],
["N", "string", "&Ntilde;", "tilde"],
["O", "string", "&Ograve;", "grave"],
["O", "string", "&Oacute;", "acute"],
["O", "string", "&Ocirc;", "circumflex"],
["O", "string", "&Ouml;", "diaeresis"],
["O", "string", "&OElig;", "ligature"],
["O", "string", "&Otilde;", "tilde"],
["O", "string", "&Oslash;", "slash"],
["U", "string", "&Ugrave;", "grave"],
["U", "string", "&Uacute;", "acute"],
["U", "string", "&Ucirc;", "circumflex"],
["U", "string", "&Uuml;", "diaeresis"],
["Y", "string", "&Yacute;", "acute"],
["Y", "string", "&Yuml;", "diaeresis"],
["a", "string", "&agrave;", "grave"],
["a", "string", "&aacute;", "acute"],
["a", "string", "&acirc;", "circumflex"],
["a", "string", "&atilde;", "tilde"],
["a", "string", "&auml;", "diaeresis"],
["a", "string", "&aring;", "ring"],
["a", "string", "&aelig;", "ligature"],
["c", "string", "&ccedil;", "cedilla"],
["d", "string", "&eth;", "acute"],
["e", "string", "&egrave;", "grave"],
["e", "string", "&eacute;", "acute"],
["e", "string", "&ecirc;", "circumflex"],
["e", "string", "&euml;", "diaeresis"],
["i", "string", "&igrave;", "grave"],
["i", "string", "&iacute;", "acute"],
["i", "string", "&icirc;", "circumflex"],
["i", "string", "&iuml;", "diaeresis"],
["n", "string", "&ntilde;", "tilde"],
["o", "string", "&ograve;", "grave"],
["o", "string", "&oacute;", "acute"],
["o", "string", "&ocirc;", "circumflex"],
["o", "string", "&ouml;", "diaeresis"],
["o", "string", "&oelig;", "ligature"],
["o", "string", "&otilde;", "tilde"],
["o", "string", "&oslash;", "slash"],
["s", "string", "&szlig;", "ligature"],
["u", "string", "&ugrave;", "grave"],
["u", "string", "&uacute;", "acute"],
["u", "string", "&ucirc;", "circumflex"],
["u", "string", "&uuml;", "diaeresis"],
["y", "string", "&yacute;", "acute"],
["y", "string", "&yuml;", "diaeresis"],
];
ModernCanvas.AutoReplaceManager.Classes.basic.bulk = {};
});
