// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft.Entertainment 255.255.255.255 at Mon Mar 29 16:23:02 2021
// </auto-generated>
// --------------------------------------------------


export interface IXboxTemplate {
    eventEnabled(eventIndex: number): number;
    traceTemplate_zz(_MCGEN_EventIndex: number, newState: string, oldState: string): void;
    traceTemplate_zdz(_MCGEN_EventIndex: number, tag: string, hresult: number, errorText: string): void;
    traceTemplate_qf(_MCGEN_EventIndex: number, controlKey: number, executionTimeMilliseconds: number): void;
    traceTemplate_qfq(_MCGEN_EventIndex: number, controlKey: number, executionTimeMilliseconds: number, responseCode: number): void;
    traceTemplate_xf(_MCGEN_EventIndex: number, seekPosition: number, executionTimeMilliseconds: number): void;
    traceTemplate_xfq(_MCGEN_EventIndex: number, seekPosition: number, executionTimeMilliseconds: number, responseCode: number): void;
    traceTemplate_xqxx(_MCGEN_EventIndex: number, position: number, transportState: number, positionBeforeLastSeek: number, lastSeekPosition: number): void;
    traceTemplate_fq(_MCGEN_EventIndex: number, executionTimeMilliseconds: number, responseCode: number): void;
    traceTemplateEventDescriptor(_MCGEN_EventIndex: number): void;
    traceTemplate_qz(_MCGEN_EventIndex: number, titleId: number, mediaAssetId: string): void;
    traceTemplate_dz(_MCGEN_EventIndex: number, hresult: number, errorMessage: string): void;
    traceTemplate_z(_MCGEN_EventIndex: number, text: string): void;
    traceTemplate_zqq(_MCGEN_EventIndex: number, text: string, selectionStart: number, selectionLength: number): void;
    traceTemplate_q(_MCGEN_EventIndex: number, titleId: number): void;
    traceTemplate_qqt(_MCGEN_EventIndex: number, titleId: number, titlePort: number, enabled: boolean): void;
    traceTemplate_qqqd(_MCGEN_EventIndex: number, status: number, titleId: number, titlePort: number, hresult: number): void;
    traceTemplate_qq(_MCGEN_EventIndex: number, clientExclusiveModeStatus: number, consoleExclusiveModeStatus: number): void;
    traceTemplate_t(_MCGEN_EventIndex: number, localTransportConnected: boolean): void;
    traceTemplate_dzztt(_MCGEN_EventIndex: number, hresult: number, errorMessage: string, sessionState: string, isCurrentWinRTSessionReassigned: boolean, isCurrentWinRTSessionNull: boolean): void;
    traceTemplate_zt(_MCGEN_EventIndex: number, sessionState: string, isRetry: boolean): void;
    traceTemplate_qfz(_MCGEN_EventIndex: number, titleId: number, startTimeMilliseconds: number, firstAction: string): void;
}
