// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:11 2021
// </auto-generated>
// --------------------------------------------------

import { PrefetchItemStatus } from "./PrefetchItemStatus";
import { IVector } from "winrt/Windows/Foundation/Collections/IVector`1";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Platform.DataServices.PrefetchItemStatusEventArgs')
export class PrefetchItemStatusEventArgs implements IStringable { 
    itemId: string = null;
    status: PrefetchItemStatus = null;
    prefetchItemValidityDataList: IVector<string> = null;
    toString(): string {
        throw new Error('PrefetchItemStatusEventArgs#toString not implemented')
    }
}
