// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:40 2021
// </auto-generated>
// --------------------------------------------------

import { IRemoteProcess } from "./IRemoteProcess";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.WindowsLive.Platform.Service.RemoteProcess')
export class RemoteProcess implements IRemoteProcess { 
}
