// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:10 2021
// </auto-generated>
// --------------------------------------------------

import { XmlDocument } from "../../Data/Xml/Dom/XmlDocument";
import { IVectorView } from "../../Foundation/Collections/IVectorView`1";
import { IVector } from "../../Foundation/Collections/IVector`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { Uri } from "../../Foundation/Uri";
import { ISyndicationNode } from "../Syndication/ISyndicationNode";
import { ISyndicationText } from "../Syndication/ISyndicationText";
import { SyndicationAttribute } from "../Syndication/SyndicationAttribute";
import { SyndicationCategory } from "../Syndication/SyndicationCategory";
import { SyndicationFormat } from "../Syndication/SyndicationFormat";

@GenerateShim('Windows.Web.AtomPub.ResourceCollection')
export class ResourceCollection implements ISyndicationNode { 
    accepts: IVectorView<string> = null;
    categories: IVectorView<SyndicationCategory> = null;
    title: ISyndicationText = null;
    uri: Uri = null;
    nodeValue: string = null;
    nodeNamespace: string = null;
    nodeName: string = null;
    language: string = null;
    baseUri: Uri = null;
    attributeExtensions: IVector<SyndicationAttribute> = null;
    elementExtensions: IVector<ISyndicationNode> = null;
    getXmlDocument(format: SyndicationFormat): XmlDocument {
        throw new Error('ResourceCollection#getXmlDocument not implemented')
    }
}
