// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:08 2021
// </auto-generated>
// --------------------------------------------------

import { IAsyncOperationWithProgress } from "../../Foundation/IAsyncOperationWithProgress`2";
import { IClosable } from "../../Foundation/IClosable";
import { IBuffer } from "./IBuffer";
import { InputStreamOptions } from "./InputStreamOptions";

export interface IInputStream extends IClosable {
    readAsync(buffer: IBuffer, count: number, options: InputStreamOptions): IAsyncOperationWithProgress<IBuffer, number>;
}
