// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { IVectorView } from "../../Foundation/Collections/IVectorView`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { PasswordCredential } from "./PasswordCredential";

@GenerateShim('Windows.Security.Credentials.PasswordVault')
export class PasswordVault { 
    add(credential: PasswordCredential): void {
        console.warn('PasswordVault#add not implemented')
    }
    remove(credential: PasswordCredential): void {
        console.warn('PasswordVault#remove not implemented')
    }
    retrieve(resource: string, userName: string): PasswordCredential {
        throw new Error('PasswordVault#retrieve not implemented')
    }
    findAllByResource(resource: string): IVectorView<PasswordCredential> {
        throw new Error('PasswordVault#findAllByResource not implemented')
    }
    findAllByUserName(userName: string): IVectorView<PasswordCredential> {
        throw new Error('PasswordVault#findAllByUserName not implemented')
    }
    retrieveAll(): IVectorView<PasswordCredential> {
        throw new Error('PasswordVault#retrieveAll not implemented')
    }
}
