// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:00 2021
// </auto-generated>
// --------------------------------------------------

import { ContactFieldCategory } from "./ContactFieldCategory";
import { ContactLocationField } from "./ContactLocationField";

export interface IContactLocationFieldFactory {
    createLocation_Default(unstructuredAddress: string): ContactLocationField;
    createLocation_Category(unstructuredAddress: string, category: ContactFieldCategory): ContactLocationField;
    createLocation_All(unstructuredAddress: string, category: ContactFieldCategory, street: string, city: string, region: string, country: string, postalCode: string): ContactLocationField;
}
