// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:00 2021
// </auto-generated>
// --------------------------------------------------

import { ContactField } from "./ContactField";
import { ContactFieldCategory } from "./ContactFieldCategory";
import { ContactFieldType } from "./ContactFieldType";

export interface IContactFieldFactory {
    createField_Default(value: string, type: ContactFieldType): ContactField;
    createField_Category(value: string, type: ContactFieldType, category: ContactFieldCategory): ContactField;
    createField_Custom(name: string, value: string, type: ContactFieldType, category: ContactFieldCategory): ContactField;
}
