// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:07 2021
// </auto-generated>
// --------------------------------------------------

import { NewsDescriptor } from "./NewsDescriptor";
import { IVector } from "winrt/Windows/Foundation/Collections/IVector`1";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('AppEx.Common.NewsCluster.Response.NewsResponse')
export class NewsResponse implements IStringable { 
    readonly newsItems: IVector<NewsDescriptor> = null;
    constructor(newsItems: IVector<NewsDescriptor>) {
        console.warn('NewsResponse.ctor not implemented')
    }
    toString(): string {
        throw new Error('NewsResponse#toString not implemented')
    }
}
