// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { UsbBulkInEndpointDescriptor } from "./UsbBulkInEndpointDescriptor";
import { UsbReadOptions } from "./UsbReadOptions";
import { IAsyncAction } from "../../Foundation/IAsyncAction";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { IInputStream } from "../../Storage/Streams/IInputStream";

@GenerateShim('Windows.Devices.Usb.UsbBulkInPipe')
export class UsbBulkInPipe { 
    readOptions: UsbReadOptions = null;
    endpointDescriptor: UsbBulkInEndpointDescriptor = null;
    inputStream: IInputStream = null;
    maxTransferSizeBytes: number = null;
    clearStallAsync(): IAsyncAction {
        throw new Error('UsbBulkInPipe#clearStallAsync not implemented')
    }
    flushBuffer(): void {
        console.warn('UsbBulkInPipe#flushBuffer not implemented')
    }
}
