// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { PushNotificationType } from "./PushNotificationType";
import { RawNotification } from "./RawNotification";
import { BadgeNotification } from "../../UI/Notifications/BadgeNotification";
import { TileNotification } from "../../UI/Notifications/TileNotification";
import { ToastNotification } from "../../UI/Notifications/ToastNotification";

@GenerateShim('Windows.Networking.PushNotifications.PushNotificationReceivedEventArgs')
export class PushNotificationReceivedEventArgs { 
    cancel: boolean = null;
    badgeNotification: BadgeNotification = null;
    notificationType: PushNotificationType = null;
    rawNotification: RawNotification = null;
    tileNotification: TileNotification = null;
    toastNotification: ToastNotification = null;
}
