// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:40 2021
// </auto-generated>
// --------------------------------------------------

import { AsyncActionProgressHandler } from "winrt/Windows/Foundation/AsyncActionProgressHandler`1";
import { AsyncActionWithProgressCompletedHandler } from "winrt/Windows/Foundation/AsyncActionWithProgressCompletedHandler`1";
import { AsyncStatus } from "winrt/Windows/Foundation/AsyncStatus";
import { IAsyncActionWithProgress } from "winrt/Windows/Foundation/IAsyncActionWithProgress`1";
import { IAsyncInfo } from "winrt/Windows/Foundation/IAsyncInfo";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.WindowsLive.Shared.Telemetry.WliReportingTask')
export class WliReportingTask implements IAsyncActionWithProgress<number>, IAsyncInfo { 
    readonly errorCode: number = null;
    readonly id: number = null;
    readonly status: AsyncStatus = null;
    progress: AsyncActionProgressHandler<number> = null;
    completed: AsyncActionWithProgressCompletedHandler<number> = null;
    getResults(): void {
        console.warn('WliReportingTask#getResults not implemented')
    }
    cancel(): void {
        console.warn('WliReportingTask#cancel not implemented')
    }
    close(): void {
        console.warn('WliReportingTask#close not implemented')
    }
}
