// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:04 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { ApplicationData } from "../../Storage/ApplicationData";

@GenerateShim('Windows.Management.Core.ApplicationDataManager')
export class ApplicationDataManager { 
    static createForPackageFamily(packageFamilyName: string): ApplicationData {
        throw new Error('ApplicationDataManager#createForPackageFamily not implemented')
    }
}
