// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:08 2021
// </auto-generated>
// --------------------------------------------------

type JsonItem = any
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Bing.AppEx.Telemetry.ContentViewProgress')
export class ContentViewProgress implements IStringable { 
    percent: number = null;
    page: number = null;
    pageCount: number = null;
    mediaDuration: number = null;
    // constructor();
    // constructor(json: JsonItem);
    constructor(...args) { }
    toJson(): JsonItem {
        throw new Error('ContentViewProgress#toJson not implemented')
    }
    toString(): string {
        throw new Error('ContentViewProgress#toString not implemented')
    }
}
