// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:08 2021
// </auto-generated>
// --------------------------------------------------

import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Bing.AppEx.Telemetry.ContentType')
export class ContentType implements IStringable { 
    static readonly unknown: string = null;
    static readonly package: string = null;
    static readonly image: string = null;
    static readonly cluster: string = null;
    static readonly article: string = null;
    static readonly map: string = null;
    static readonly chart: string = null;
    static readonly audio: string = null;
    static readonly video: string = null;
    static readonly table: string = null;
    static readonly slideshow: string = null;
    static readonly link: string = null;
    toString(): string {
        throw new Error('ContentType#toString not implemented')
    }
}
