// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:08 2021
// </auto-generated>
// --------------------------------------------------

import { DisplayMode } from "./DisplayMode";
import { DisplayOrientation } from "./DisplayOrientation";
import { IFlightEvent } from "./IFlightEvent";

export interface IDisplayChangeFlightEvent extends IFlightEvent {
    displayChangeOrgMode: DisplayMode;
    displayChangeOrgOrientation: DisplayOrientation;
}
