// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:09 2021
// </auto-generated>
// --------------------------------------------------

import { ContentSource } from "./ContentSource";
type JsonItem = any
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Bing.AppEx.Telemetry.ImpressionSource')
export class ImpressionSource implements IStringable { 
    sourceId: number = null;
    name: string = null;
    partner: string = null;
    partnerCode: string = null;
    wasLogged: boolean = null;
    // constructor();
    // constructor(json: JsonItem);
    constructor(...args) { }
    equals(obj: any): boolean {
        throw new Error('ImpressionSource#equals not implemented')
    }
    getHashCode(): number {
        throw new Error('ImpressionSource#getHashCode not implemented')
    }
    toContentSource(): ContentSource {
        throw new Error('ImpressionSource#toContentSource not implemented')
    }
    toJson(): JsonItem {
        throw new Error('ImpressionSource#toJson not implemented')
    }
    toString(): string {
        throw new Error('ImpressionSource#toString not implemented')
    }
}
