// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:09 2021
// </auto-generated>
// --------------------------------------------------

type ContentItem = any
import { ContentWorth } from "./ContentWorth";
type JsonItem = any
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Bing.AppEx.Telemetry.ImpressionContent')
export class ImpressionContent implements IStringable { 
    k: number = null;
    sourceId: number = null;
    contentId: string = null;
    type: string = null;
    date: Date = null;
    uri: string = null;
    slug: string = null;
    isSummary: boolean = null;
    worth: ContentWorth = null;
    isAd: boolean = null;
    adCampaignId: string = null;
    wasLogged: boolean = null;
    wasViewed: boolean = null;
    // constructor();
    // constructor(json: JsonItem);
    constructor(...args) { }
    equals(obj: any): boolean {
        throw new Error('ImpressionContent#equals not implemented')
    }
    getHashCode(): number {
        throw new Error('ImpressionContent#getHashCode not implemented')
    }
    toContentItem(): ContentItem {
        throw new Error('ImpressionContent#toContentItem not implemented')
    }
    toJson(): JsonItem {
        throw new Error('ImpressionContent#toJson not implemented')
    }
    toString(): string {
        throw new Error('ImpressionContent#toString not implemented')
    }
}
