// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:09 2021
// </auto-generated>
// --------------------------------------------------

import { IFlightEvent } from "./IFlightEvent";
import { IMap } from "winrt/Windows/Foundation/Collections/IMap`2";

export interface IPreferencesFlightEvent extends IFlightEvent {
    setPreference(name: string, value: string): void;
    getPreference(name: string): string;
    preferenceExists(name: string): boolean;
    getPreferenceDictionary(): IMap<string, string>;
    setPreferenceJson(jsonText: string): void;
}
