// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from LibWrap 255.255.255.255 at Fri Mar 26 17:24:55 2021
// </auto-generated>
// --------------------------------------------------

import { IClosable } from "winrt/Windows/Foundation/IClosable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('LibWrap.Binary')
export class Binary implements IClosable { 
    set(bytes: number[]): void {
        console.warn('Binary#set not implemented')
    }
    getAsBase64(): string {
        throw new Error('Binary#getAsBase64 not implemented')
    }
    append(other: Binary): void {
        console.warn('Binary#append not implemented')
    }
    close(): void {
        console.warn('Binary#close not implemented')
    }
}
