// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:08 2021
// </auto-generated>
// --------------------------------------------------

export enum PointerUpdateKind {
    other,
    leftButtonPressed,
    leftButtonReleased,
    rightButtonPressed,
    rightButtonReleased,
    middleButtonPressed,
    middleButtonReleased,
    xbutton1Pressed,
    xbutton1Released,
    xbutton2Pressed,
    xbutton2Released,
}
