// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:03 2021
// </auto-generated>
// --------------------------------------------------

import { IVectorView } from "../Foundation/Collections/IVectorView`1";
import { GenerateShim } from "../Foundation/Interop/GenerateShim";
import { JapanesePhoneme } from "./JapanesePhoneme";

@GenerateShim('Windows.Globalization.JapanesePhoneticAnalyzer')
export class JapanesePhoneticAnalyzer { 
    static getWords(input: string): IVectorView<JapanesePhoneme> {
        throw new Error('JapanesePhoneticAnalyzer#getWords not implemented')
    }
    static getWordsWithMonoRubyOption(input: string, monoRuby: boolean): IVectorView<JapanesePhoneme> {
        throw new Error('JapanesePhoneticAnalyzer#getWordsWithMonoRubyOption not implemented')
    }
}
