// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:39 2021
// </auto-generated>
// --------------------------------------------------

import { FolderChangeType } from "./FolderChangeType";

export interface IFolderChange {
    readonly accountStoreId: number;
    readonly folderChangeType: FolderChangeType;
    readonly folderName: string;
    readonly oldFolderName: string;
    readonly oldParentStoreId: number;
    readonly parentServerId: string;
    readonly parentStoreId: number;
    readonly realStoreId: number;
    readonly serverId: string;
    readonly stashStoreId: number;
    completeSuccessfulChange(hstrNewServerId: string, hstrNewSyncKey: string): void;
    rollbackChange(fEnforceFolderListConstraints: boolean): void;
}
