// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:39 2021
// </auto-generated>
// --------------------------------------------------

import { ICollection } from "../ICollection";
import { IMailConversationPrivate } from "./IMailConversationPrivate";
import { IMailMessagePrivate } from "./IMailMessagePrivate";

export interface IMailConversationManagerPrivate {
    getConversationIdForNewMessage(pMessagePriv: IMailMessagePrivate, dtMigration: Date): string;
    getAllConversationInAccount(hstrAccountId: string): ICollection;
    getAllConversations(): ICollection;
    loadConversation(hstrObjectId: string): IMailConversationPrivate;
}
