// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:40 2021
// </auto-generated>
// --------------------------------------------------

import { IRecipient } from "../IRecipient";
import { IMailConversationAggregator } from "./IMailConversationAggregator";
import { IMailConversationPrivate } from "./IMailConversationPrivate";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.WindowsLive.Platform.Private.MailConversationAllVisibleAggregator')
export class MailConversationAllVisibleAggregator implements IMailConversationAggregator { 
    aggregateReadState(pConversation: IMailConversationPrivate): boolean {
        throw new Error('MailConversationAllVisibleAggregator#aggregateReadState not implemented')
    }
    aggregateDisplayTime(pConversation: IMailConversationPrivate): Date {
        throw new Error('MailConversationAllVisibleAggregator#aggregateDisplayTime not implemented')
    }
    aggregateFromRecipient(pConversation: IMailConversationPrivate): IRecipient {
        throw new Error('MailConversationAllVisibleAggregator#aggregateFromRecipient not implemented')
    }
    aggregateAll(pConversation: IMailConversationPrivate): { pRead: boolean, pDate: Date, pFromRecipient: IRecipient } {
        throw new Error('MailConversationAllVisibleAggregator#aggregateAll not implemented')
    }
    shouldForwardFlattenedSenderNotifications(): boolean {
        throw new Error('MailConversationAllVisibleAggregator#shouldForwardFlattenedSenderNotifications not implemented')
    }
    hasFromRecipientChanged(pCurrentRecipient: IRecipient, pCachedRecipient: IRecipient): boolean {
        throw new Error('MailConversationAllVisibleAggregator#hasFromRecipientChanged not implemented')
    }
}
