// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:11 2021
// </auto-generated>
// --------------------------------------------------

import { IVectorView } from "../../Foundation/Collections/IVectorView`1";
import { IStringable } from "../../Foundation/IStringable";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { SocketSslErrorSeverity } from "../../Networking/Sockets/SocketSslErrorSeverity";
import { Certificate } from "../../Security/Cryptography/Certificates/Certificate";
import { ChainValidationResult } from "../../Security/Cryptography/Certificates/ChainValidationResult";

@GenerateShim('Windows.Web.Http.HttpTransportInformation')
export class HttpTransportInformation implements IStringable { 
    serverCertificate: Certificate = null;
    serverCertificateErrorSeverity: SocketSslErrorSeverity = null;
    serverCertificateErrors: IVectorView<ChainValidationResult> = null;
    serverIntermediateCertificates: IVectorView<Certificate> = null;
    toString(): string {
        throw new Error('HttpTransportInformation#toString not implemented')
    }
}
