// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Networking.Connectivity.DataUsage')
export class DataUsage { 
    bytesReceived: number = null;
    bytesSent: number = null;
}
