// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:04 2021
// </auto-generated>
// --------------------------------------------------

import { IAsyncOperation } from "../Foundation/IAsyncOperation`1";
import { GenerateShim } from "../Foundation/Interop/GenerateShim";
import { ImageDisplayProperties } from "./ImageDisplayProperties";
import { MediaPlaybackType } from "./MediaPlaybackType";
import { MusicDisplayProperties } from "./MusicDisplayProperties";
import { VideoDisplayProperties } from "./VideoDisplayProperties";
import { StorageFile } from "../Storage/StorageFile";
import { RandomAccessStreamReference } from "../Storage/Streams/RandomAccessStreamReference";

@GenerateShim('Windows.Media.SystemMediaTransportControlsDisplayUpdater')
export class SystemMediaTransportControlsDisplayUpdater { 
    type: MediaPlaybackType = null;
    thumbnail: RandomAccessStreamReference = null;
    appMediaId: string = null;
    imageProperties: ImageDisplayProperties = null;
    musicProperties: MusicDisplayProperties = null;
    videoProperties: VideoDisplayProperties = null;
    copyFromFileAsync(type: MediaPlaybackType, source: StorageFile): IAsyncOperation<boolean> {
        throw new Error('SystemMediaTransportControlsDisplayUpdater#copyFromFileAsync not implemented')
    }
    clearAll(): void {
        console.warn('SystemMediaTransportControlsDisplayUpdater#clearAll not implemented')
    }
    update(): void {
        console.warn('SystemMediaTransportControlsDisplayUpdater#update not implemented')
    }
}
