// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:10 2021
// </auto-generated>
// --------------------------------------------------

import { IAdSource } from "../../../Media/Advertising/IAdSource";
import { IResolveableAdSource } from "../../../Media/Advertising/IResolveableAdSource";
import { IMap } from "winrt/Windows/Foundation/Collections/IMap`2";
import { IAsyncAction } from "winrt/Windows/Foundation/IAsyncAction";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { AsyncAction } from "winrt/Windows/Foundation/Interop/AsyncAction";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";
import { Uri } from "winrt/Windows/Foundation/Uri";

@GenerateShim('Microsoft.PlayerFramework.Js.Advertising.RemoteAdSource')
export class RemoteAdSource implements IResolveableAdSource, IAdSource, IStringable { 
    readonly isLoaded: boolean = null;
    payload: any = null;
    key: string = null;
    type: string = null;
    allowMultipleAds: boolean = null;
    maxRedirectDepth: number | null = null;
    uri: Uri = null;
    headers: IMap<string, string> = null;
    // constructor();
    // constructor(uri: Uri);
    // constructor(uri: Uri, type: string);
    constructor(...args) { }
    loadPayload(): IAsyncAction {
        return AsyncAction.from(async () => console.warn('RemoteAdSource#loadPayload not implemented'));
    }
    toString(): string {
        throw new Error('RemoteAdSource#toString not implemented')
    }
}
