// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { CompassReading } from "./CompassReading";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Devices.Sensors.CompassReadingChangedEventArgs')
export class CompassReadingChangedEventArgs { 
    reading: CompassReading = null;
}
