// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:05 2021
// </auto-generated>
// --------------------------------------------------

import { IIterable } from "../../Foundation/Collections/IIterable`1";
import { IIterator } from "../../Foundation/Collections/IIterator`1";
import { IKeyValuePair } from "../../Foundation/Collections/IKeyValuePair`2";
import { IMapView } from "../../Foundation/Collections/IMapView`2";
import { IMap } from "../../Foundation/Collections/IMap`2";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Media.MediaProperties.MediaPropertySet')
export class MediaPropertySet implements IMap<string, any>, IIterable<IKeyValuePair<string, any>> { 
    [Symbol.iterator]() {
        return null;
    }

    size: number = null;
    lookup(key: string): any {
        throw new Error('MediaPropertySet#lookup not implemented')
    }
    hasKey(key: string): boolean {
        throw new Error('MediaPropertySet#hasKey not implemented')
    }
    getView(): IMapView<string, any> {
        throw new Error('MediaPropertySet#getView not implemented')
    }
    insert(key: string, value: any): boolean {
        throw new Error('MediaPropertySet#insert not implemented')
    }
    remove(key: string): void {
        console.warn('MediaPropertySet#remove not implemented')
    }
    clear(): void {
        console.warn('MediaPropertySet#clear not implemented')
    }
    first(): IIterator<IKeyValuePair<string, any>> {
        throw new Error('MediaPropertySet#first not implemented')
    }
}
