// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:08 2021
// </auto-generated>
// --------------------------------------------------

import { NewsTopicType } from "../Shared/NewsTopicType";
import { IStringable } from "winrt/Windows/Foundation/IStringable";
import { GenerateShim } from "winrt/Windows/Foundation/Interop/GenerateShim";

@GenerateShim('Microsoft.Amp.PersonalDataPlatform.DataClient.News.DataModel.Windows.WindowsTopicDataModel')
export class WindowsTopicDataModel implements IStringable { 
    topicType: NewsTopicType = null;
    title: string = null;
    query: string = null;
    market: string = null;
    searchCount: number | null = null;
    ageCount: number | null = null;
    type: string = null;
    equals(topic: any): boolean {
        throw new Error('WindowsTopicDataModel#equals not implemented')
    }
    getHashCode(): number {
        throw new Error('WindowsTopicDataModel#getHashCode not implemented')
    }
    toString(): string {
        throw new Error('WindowsTopicDataModel#toString not implemented')
    }
}
