// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:05 2021
// </auto-generated>
// --------------------------------------------------

export enum VideoEncodingQuality {
    auto,
    hd1080p,
    hd720p,
    wvga,
    ntsc,
    pal,
    vga,
    qvga,
}
