// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { SmartCardPinCharacterPolicyOption } from "./SmartCardPinCharacterPolicyOption";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Devices.SmartCards.SmartCardPinPolicy')
export class SmartCardPinPolicy { 
    uppercaseLetters: SmartCardPinCharacterPolicyOption = null;
    specialCharacters: SmartCardPinCharacterPolicyOption = null;
    minLength: number = null;
    maxLength: number = null;
    lowercaseLetters: SmartCardPinCharacterPolicyOption = null;
    digits: SmartCardPinCharacterPolicyOption = null;
}
