// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:11 2021
// </auto-generated>
// --------------------------------------------------

import { XmlDocument } from "../../Data/Xml/Dom/XmlDocument";
import { IVector } from "../../Foundation/Collections/IVector`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { Uri } from "../../Foundation/Uri";
import { ISyndicationNode } from "./ISyndicationNode";
import { ISyndicationText } from "./ISyndicationText";
import { SyndicationAttribute } from "./SyndicationAttribute";
import { SyndicationFormat } from "./SyndicationFormat";
import { SyndicationTextType } from "./SyndicationTextType";

@GenerateShim('Windows.Web.Syndication.SyndicationContent')
export class SyndicationContent implements ISyndicationText, ISyndicationNode { 
    sourceUri: Uri = null;
    xml: XmlDocument = null;
    type: string = null;
    text: string = null;
    nodeValue: string = null;
    nodeNamespace: string = null;
    nodeName: string = null;
    language: string = null;
    baseUri: Uri = null;
    attributeExtensions: IVector<SyndicationAttribute> = null;
    elementExtensions: IVector<ISyndicationNode> = null;
    // constructor();
    // constructor(sourceUri: Uri);
    // constructor(text: string, type: SyndicationTextType);
    constructor(...args) { }
    getXmlDocument(format: SyndicationFormat): XmlDocument {
        throw new Error('SyndicationContent#getXmlDocument not implemented')
    }
}
