// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:37 2021
// </auto-generated>
// --------------------------------------------------

import { ScenarioId } from "./ScenarioId";
import { TransactionContext } from "./TransactionContext";
import { TransactionId } from "./TransactionId";

export interface ITransactionContextFactory {
    createTransactionContext_WithoutBiciContext(scenarioId: ScenarioId, market: number): TransactionContext;
    createTransactionContext_WithBiciContext(scenarioId: ScenarioId, market: number, experienceId: string, requestId: string): TransactionContext;
    createTransactionContext_WithBiciContextAndTransactionId(scenarioId: ScenarioId, market: number, experienceId: string, requestId: string, transactionId: TransactionId): TransactionContext;
    createTransactionContext_FromBase64String(hstrBase64EncodedTxContext: string): TransactionContext;
}
