// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { HidCollection } from "./HidCollection";
import { HidReportType } from "./HidReportType";
import { IVectorView } from "../../Foundation/Collections/IVectorView`1";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Devices.HumanInterfaceDevice.HidBooleanControlDescription')
export class HidBooleanControlDescription { 
    id: number = null;
    parentCollections: IVectorView<HidCollection> = null;
    reportId: number = null;
    reportType: HidReportType = null;
    usageId: number = null;
    usagePage: number = null;
}
