// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Platform 3.0.0.0 at Fri Jun  4 19:45:10 2021
// </auto-generated>
// --------------------------------------------------

import { IMap } from "winrt/Windows/Foundation/Collections/IMap`2";
import { IVector } from "winrt/Windows/Foundation/Collections/IVector`1";

export interface IJSONWrapper {
    extractNamedJsonArray(jsonNode: any, keyName: string, isOptional: boolean): IVector<any>;
    extractNamedJsonAsString(jsonNode: any, keyName: string, isOptional: boolean): string;
    extractNamedJsonObject(jsonNode: any, keyName: string, isOptional: boolean): any;
    extractStringPropertyValue(jsonNode: any, keyName: string, isOptional: boolean): string;
    extractBooleanPropertyValue(jsonNode: any, keyName: string, isOptional: boolean): boolean;
    extractNumberPropertyValue(jsonNode: any, keyName: string, isOptional: boolean): number | null;
    parse(jsonData: string): any;
    buildJsonArrayAndStringify(objectName: string, values: IVector<IMap<string, string>>): string;
}
