// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Microsoft 255.255.255.255 at Wed Apr 14 20:25:39 2021
// </auto-generated>
// --------------------------------------------------

import { IObject } from "../IObject";
import { MailChangeCommand } from "./MailChangeCommand";

export interface IMailChangeItem extends IObject {
    readonly command: MailChangeCommand;
    targetObjectId: string;
    targetStoreId: number;
}
