// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:09 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { ActivatedDeferral } from "./ActivatedDeferral";

@GenerateShim('Windows.UI.WebUI.ActivatedOperation')
export class ActivatedOperation { 
    getDeferral(): ActivatedDeferral {
        return new ActivatedDeferral();
    }
}
