// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:09 2021
// </auto-generated>
// --------------------------------------------------

import { ActivationKind } from "../../ApplicationModel/Activation/ActivationKind";
import { ApplicationExecutionState } from "../../ApplicationModel/Activation/ApplicationExecutionState";
import { IActivatedEventArgs } from "../../ApplicationModel/Activation/IActivatedEventArgs";
import { IPrintTaskSettingsActivatedEventArgs } from "../../ApplicationModel/Activation/IPrintTaskSettingsActivatedEventArgs";
import { SplashScreen } from "../../ApplicationModel/Activation/SplashScreen";
import { PrintTaskConfiguration } from "../../Devices/Printers/Extensions/PrintTaskConfiguration";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { ActivatedOperation } from "./ActivatedOperation";
import { IActivatedEventArgsDeferral } from "./IActivatedEventArgsDeferral";

@GenerateShim('Windows.UI.WebUI.WebUIPrintTaskSettingsActivatedEventArgs')
export class WebUIPrintTaskSettingsActivatedEventArgs implements IPrintTaskSettingsActivatedEventArgs, IActivatedEventArgs, IActivatedEventArgsDeferral { 
    configuration: PrintTaskConfiguration = null;
    activatedOperation: ActivatedOperation = null;
    kind: ActivationKind = null;
    previousExecutionState: ApplicationExecutionState = null;
    splashScreen: SplashScreen = null;
}
