// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:06 2021
// </auto-generated>
// --------------------------------------------------

import { GenerateShim } from "../../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Security.Cryptography.Core.HashAlgorithmNames')
export class HashAlgorithmNames { 
    static md5: string = "MD5";
    static sha1: string = "SHA1";
    static sha256: string = "SHA256";
    static sha384: string = "SHA384";
    static sha512: string = "SHA512";
}
