// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:22:59 2021
// </auto-generated>
// --------------------------------------------------

import { ActivationKind } from "./ActivationKind";
import { ApplicationExecutionState } from "./ApplicationExecutionState";
import { IActivatedEventArgs } from "./IActivatedEventArgs";
import { IContactActivatedEventArgs } from "./IContactActivatedEventArgs";
import { IContactMessageActivatedEventArgs } from "./IContactMessageActivatedEventArgs";
import { SplashScreen } from "./SplashScreen";
import { Contact } from "../Contacts/Contact";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.ApplicationModel.Activation.ContactMessageActivatedEventArgs')
export class ContactMessageActivatedEventArgs implements IContactMessageActivatedEventArgs, IContactActivatedEventArgs, IActivatedEventArgs { 
    verb: string = null;
    contact: Contact = null;
    serviceId: string = null;
    serviceUserId: string = null;
    kind: ActivationKind = null;
    previousExecutionState: ApplicationExecutionState = null;
    splashScreen: SplashScreen = null;
}
