// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:22:59 2021
// </auto-generated>
// --------------------------------------------------

import { IActivatedEventArgs } from "./IActivatedEventArgs";
import { IContactActivatedEventArgs } from "./IContactActivatedEventArgs";
import { Contact } from "../Contacts/Contact";
import { ContactAddress } from "../Contacts/ContactAddress";

export interface IContactMapActivatedEventArgs extends IContactActivatedEventArgs, IActivatedEventArgs {
    address: ContactAddress;
    contact: Contact;
}
