// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IImageScannerFormatConfiguration } from "./IImageScannerFormatConfiguration";
import { ImageScannerAutoCroppingMode } from "./ImageScannerAutoCroppingMode";
import { ImageScannerColorMode } from "./ImageScannerColorMode";
import { ImageScannerResolution } from "./ImageScannerResolution";
import { Rect } from "../../Foundation/Rect";
import { Size } from "../../Foundation/Size";

export interface IImageScannerSourceConfiguration extends IImageScannerFormatConfiguration {
    actualResolution: ImageScannerResolution;
    autoCroppingMode: ImageScannerAutoCroppingMode;
    brightness: number;
    brightnessStep: number;
    colorMode: ImageScannerColorMode;
    contrast: number;
    contrastStep: number;
    defaultBrightness: number;
    defaultColorMode: ImageScannerColorMode;
    defaultContrast: number;
    desiredResolution: ImageScannerResolution;
    maxBrightness: number;
    maxContrast: number;
    maxResolution: ImageScannerResolution;
    maxScanArea: Size;
    minBrightness: number;
    minContrast: number;
    minResolution: ImageScannerResolution;
    minScanArea: Size;
    opticalResolution: ImageScannerResolution;
    selectedScanRegion: Rect;
    isAutoCroppingModeSupported(value: ImageScannerAutoCroppingMode): boolean;
    isColorModeSupported(value: ImageScannerColorMode): boolean;
}
