// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IImageScannerFormatConfiguration } from "./IImageScannerFormatConfiguration";
import { IImageScannerSourceConfiguration } from "./IImageScannerSourceConfiguration";
import { ImageScannerAutoCroppingMode } from "./ImageScannerAutoCroppingMode";
import { ImageScannerColorMode } from "./ImageScannerColorMode";
import { ImageScannerFormat } from "./ImageScannerFormat";
import { ImageScannerResolution } from "./ImageScannerResolution";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";
import { Rect } from "../../Foundation/Rect";
import { Size } from "../../Foundation/Size";

@GenerateShim('Windows.Devices.Scanners.ImageScannerFlatbedConfiguration')
export class ImageScannerFlatbedConfiguration implements IImageScannerFormatConfiguration, IImageScannerSourceConfiguration { 
    format: ImageScannerFormat = null;
    defaultFormat: ImageScannerFormat = null;
    selectedScanRegion: Rect = null;
    desiredResolution: ImageScannerResolution = null;
    contrast: number = null;
    colorMode: ImageScannerColorMode = null;
    brightness: number = null;
    autoCroppingMode: ImageScannerAutoCroppingMode = null;
    actualResolution: ImageScannerResolution = null;
    brightnessStep: number = null;
    contrastStep: number = null;
    defaultBrightness: number = null;
    defaultColorMode: ImageScannerColorMode = null;
    defaultContrast: number = null;
    maxBrightness: number = null;
    maxContrast: number = null;
    maxResolution: ImageScannerResolution = null;
    maxScanArea: Size = null;
    minBrightness: number = null;
    minContrast: number = null;
    minResolution: ImageScannerResolution = null;
    minScanArea: Size = null;
    opticalResolution: ImageScannerResolution = null;
    isFormatSupported(value: ImageScannerFormat): boolean {
        throw new Error('ImageScannerFlatbedConfiguration#isFormatSupported not implemented')
    }
    isAutoCroppingModeSupported(value: ImageScannerAutoCroppingMode): boolean {
        throw new Error('ImageScannerFlatbedConfiguration#isAutoCroppingModeSupported not implemented')
    }
    isColorModeSupported(value: ImageScannerColorMode): boolean {
        throw new Error('ImageScannerFlatbedConfiguration#isColorModeSupported not implemented')
    }
}
