// --------------------------------------------------
// <auto-generated>
//     This code was generated by tswinrt.
//     Generated from Windows 255.255.255.255 at Fri Mar 26 17:23:02 2021
// </auto-generated>
// --------------------------------------------------

import { IImageScannerFormatConfiguration } from "./IImageScannerFormatConfiguration";
import { ImageScannerFormat } from "./ImageScannerFormat";
import { GenerateShim } from "../../Foundation/Interop/GenerateShim";

@GenerateShim('Windows.Devices.Scanners.ImageScannerAutoConfiguration')
export class ImageScannerAutoConfiguration implements IImageScannerFormatConfiguration { 
    format: ImageScannerFormat = null;
    defaultFormat: ImageScannerFormat = null;
    isFormatSupported(value: ImageScannerFormat): boolean {
        throw new Error('ImageScannerAutoConfiguration#isFormatSupported not implemented')
    }
}
